from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x481a28;end=0x481a98
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-format-string-null-policy-prefix-byte-emission-middle-21602-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# String null policy and prefix-byte emission\n\nPartial/unaccepted;112 instruction bytes481A28..481A98. Continues481836232frame. Stringhandlerloadcursorword[R9],freshargumentwordpostincrement4→R4,storeadvancedcursor[R9];SP20=R4. Nonnull→481B92 unresolvedstringlengthpath. Null:loadpointerSP172 thenfreshbyte[pointer+1] (initialfifthargumentlowbyteatSP67);zero→481B88 unresolvednullreplacement. Nonzero:R4=FFFFFFFF;R0ADR4824FC;call4D40A0 withliveR1/R2/R3;R4=FFFFFFFF-helperR0mod2^32;nonzero→4824E4error;zero→4824AC commonunresolvedoutput. Helpersemanticsunresolved,do notassumeabortfromname.\n\nSeparateentry481A5C (otherhandlerjoins):call482684(R0=R6,R1=SP8,R2=SP,R3=1);fullnonzero→4824E4;zero→R4--mod2^32,repeatwhileR4nonzero. Entrycountpreconditionunresolved;zeroentrywouldwrap. ThenstoreR6SP192callbackslot;R4=wordSP28prefixcount,R7=SP72prefixbuffer. Count0→481A98. Other:reloadR6SP192once;loopfreshbyte[R7]postincrement→R1,R0=wordSP16;BLXR6 withliveR2/R3;fullresultSP16;zero→4824E4. NonzeroincrementSP52countermod2^32,decrementR4,repeat. AfterloopstoreR6SP192again. Preservecallbackfullstate/results andregister/stackeffects;continuationunresolved,no C/freeze/fullcoverage/equality claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
