from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47ea90;end=0x47eaf6
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-counter-decrease-drain-swap-guarded-shared-init-21402-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Counter-decrease list draining/swap and guarded shared initialization\n\nPartial/unaccepted;102instructionbytes47EA90..47EAF6,twoentries.\nEA90 PUSH R7,LR8. LoopR1=literalEB78pointer;freshword[R1]thenfreshword[result]nonzero→independentlyfreshword[R1],freshword[result+12],freshword[result] intoR0;47E83A(R0,FFFFFFFF,liveR2,R3);repeat. Zerotest→freshword[R1]R0;R2=literalEB7Cpointer;freshword[R2]R3;storeR3word[R1],thenR0word[R2]. Orderedexchangeafterdrain,no atomicity/nullchainguards. POP R0,PC returns savedentryR7,not exchangedpointer/callbackresult. Refines21396counterdecreasehelperwithterminationstilldependentoncallbacks.\nEAB8 PUSH R2,R3,R4,R5,R6,LR24;4420D0(liveargs);R4=literalEB6Cpointer;freshwordnonzero skipsinit. Zero→R5=literalEB84;45607C(R5,liveargs);R6=literalEB88;45607C(R6,liveargs);storeR5word[pointerEB78],storeR6word[pointerEB7C]. SP0=0overwritessavedentryR2;4415CA(50,16,literalEB90,literalEB8C)withfifthstackarg0;storefullresultword[R4],nozeroresultcheck. Always4420E8(liveargs);POP R0,R1,R4,R5,R6,PC24 returnsSP0/SP4 (initialsavedentryR2/R3;SP0zerooninit,subjectcallee writes),restorespreservedregs. Entryguardsandwritesretainorder,initializationmayrepeatifstoredresultzero. No C/freeze/completenessclaim;externalhelpersownershipremainunresolved.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
