from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47f7ae;end=0x47f85e
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-indexed-record-clear-prefix-special-guards-protected-write-21454-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Indexed record clear prefix with special guards and protected write\n\nPartial/unaccepted;176instructionbytes47F7AE..47F85E,prefixonly. PUSH R3,R4,R5,LR16,SUBSP24→40frame;R5fullentryindex. EF18(SP+4,LOW8(index),liveR2/R3) fullresultR4;nonzeroR0=R4branchesF908outsideprefix. Zero freshSP4pointer→word TSTfreshSP8mask;intersectionzeroR0=0branchesF908. OtherwiseLOW8(index)==29: freshwordthrough480100&255 unsigned<34 AND freshwordthroughFAE0bit21nonzero returns3viaF908; othercaseSP0=1,480826(literal480108value,literal480104value,1,0,fifth1),fullresultR4nonzeroreturnedviaF908. No normalizationofliteralR0/helperresult.\n\nLOW8(index)==28: independentlyfreshwordthrough48010Cclearsbit24store;thenfreshwordthrough480110clearsbit0store;independentfreshwordthroughsamepointerclearsbits1..3store. Allremainingpaths48032C(live),473940(live)→SP20;freshSP4pointer→word &~freshSP8mask, independentlyreloadSP4pointerusedstore;loadSP20 MSR PRIMASK,R0. ContinueF85Ewith40frameactive,R5index,R4priorzerohelperresult;recordSP4..19andSP20savedhelperresult. No unwind/wholefunctionclaim; preserveorderedRMWandfreshpointers. Externalhelpers/pointedownershipunresolved;noMMIO/C/freeze/fullcoverageclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
