from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x480bc2;end=0x480c56
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-modes-five-six-fresh-selector-validation-helper-errors-tail-21548-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Modes five/six and default: selector validation and helper errors\n\nPartial/unaccepted;148 instruction bytes480BC2..480C56. Continuation4809C4;16-byte frame,R4entryR1 pointer. Mode5 calls4C44BC withR0=2,R1=52 and liveR2/R3. Nonzero full helper result branches480A1A epilogue, preservingR0; no subsequent writes. On zero:nonnullR4→freshword[R4] v;accept v==0 or unsigned(v-3mod2^32)<5 (3..7);otherwise return6 via480A1A. Acceptednonnull: pointer480EB4 freshword→SP0;reloadclear0x7000→SP0;reload intoR1 then a SECOND freshword[R4] shifted12mod2^32 AND0x7000 ORR1→SP0;reloadstoreword. Validation value must not replace second read. NullR4 path: same initialword/scratchclear but OR0x4000, then store. Both successpaths freshword atpointer480EC8 OR0x80 store;branch480A18 setsR0=0 thenepilogue.\n\nMode6: freshword atpointer480EB4 OR0x7000 store;freshword atpointer480EC8 clear0x80 store;call4C4530 withR0=2,R1=52 and liveR2/R3. Nonzero fullhelperresult→480A1A;zero→480A18 returns0. These writes precede helper failure and are not rolled back. No R4 dereference orSP0 scratch store on mode6. Default selectors7..255 return6 via480A1A withoutmodewrites/helpercall.\n\nCommonPOP R1,R4,R5,PC releases16. Mode5successful returnsR1scratchSP0 final configuration;earlyhelperfailure/invalidselector,mode6/default retain savedentryR3 inSP0 unless helper aliases stack. Preserve distinct fresh reads,scratch accesses,helper liveargs and effects. No C/freeze/fullcoverage/equality claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
