from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47fca2;end=0x47fdb4
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21075/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Fresh version-dependent offset and ordered field copies\n\nPartial/unaccepted;274 instruction bytes47FCA2..47FDB4;24frame active; R4=480100 pointer,R2=480184 pointer,R1=480148 guard pointer from preceding fragments. Define V()=freshword[R4]&255 and S()=freshword throughliteral48018C,each invocation distinct and short-circuited. Initial predicate: freshword480188 bits4..5==3 AND ((V()==33 AND S()!=0) OR V()>=34). False skipsFD4C. True: if ((V()==33 AND unsignedS()>=3) OR (V()==34 AND S()==1) OR (V()==35 AND S()==0)), freshword[R2]+7 wrapping stored[R2],skipFD4C. Otherwise if ((V()==33 AND unsignedS()<3) OR (V()==34 AND S()==0)), freshword[R2]+6 wrappingstored[R2]. Else unchanged. Preserve each V()/S() reload; changing values can select paths unlike a cached version/state table.\n\nFD4C ordered fullword copies/extractions: freshword480190→word480194; freshword480198 bits25..29→word48019C, independentlyfreshsameword bits11..15→word4801A0; freshword4801A4 bits25..29→word4801A8, independentlyfreshsameword bits11..15→word4801AC;freshword4801B0 bits8..12→word4801B4;freshword4801B8 bits17..21→word4801BC. Then byte[R1]=1 (guardpointer480148). No helpercalls/frameunwindinfragment; continueFDB4,which earlier nonzero-guardbranch also targets and skips all these writes. Literal labels are loaded pointer values, not dereferences of literal slots. Ownership/MMIO/C/freeze/fullcoverage unresolved/notclaimed.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
