from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x46921c;end=0x46928c
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-global-byte-guard-entry-saved-input-byte-and-context-predicate-19488-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Guarded entry 0x46921C..0x46928C\n\nPartial/unaccepted; 112 instruction bytes. PUSH R0/R4/R5/LR then SUB SP16 creates32-byte frame. SP16 holds original R0 word; SP20/24 saved R4/R5; SP28 saved LR. Diagnostic SP0/SP4 are local slots and do not overwrite saved original input.\n\nR0=literal 0x469B44; load unsigned byte [R0]. Byte zero branches 0x46926E. Nonzero calls 0x43D0CE with live R0/R1/R2/R3. Fresh result bit1 diagnostic: SP4=literal0x469B48; SP0=88; R3=literal0x469B4C; R2=literal0x469B38; R1=literal0x469B3C; R0=4 -> 0x43D574. Separate fresh mask bit0 or conditional third fresh bit2 enables R1=literal0x469B50, R2=R1, R0=0x10000000, liveR3 ->0x43CE9E. This nonzero guard arm branches0x469384 outside chunk.\n\nZero guard arm: R0=1, R1=literal0x469B54, store byte1 at[R1]. Call0x46919E with live arguments; save full returned bool toR5. Fresh unsigned byte fromSP16 is low8 original R0; bytezero branches0x46931C. Nonzero calls0x443484 with R0 that byte and live otherargs; FULL childresultzero branches0x46931C, nonzero continues0x46928C diagnostics outsidechunk. Preserve distinct global literal addresses and saved-input byte read. No interpretation of lock/state or child contracts; no wholefunction completion, C, runtime or gateclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
