from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x482174;end=0x482200
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21235/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text("# Scientific and hexadecimal marker selection, first digit and fractional copy\n\nPartial/unaccepted; 140 instruction bytes 482174..482200, middle of 481836 formatter's 232-byte frame. Entry 482174: if full R11==97 set R11=112 and branch 4821B4; otherwise branch 4821AA, where full R11==65 changes it to 80, other values retained. Separate general-format entry 482180: R0=SXTH(R6); if signed R0<R8, freshly read byte SP64 and LSL28; if PL (flag bit 3 clear), assign R8=R0. Then R8-=1 modulo 2^32; MI clamps R8=0. Full R11==103 selects R11=101, otherwise R11=69; branch 4821B4.\n\nCommon 4821B4: load old count SP32 into R0, store old+1 before loading destination SP20 and fresh byte [R4] with postincrement R4. Store this byte at destination+old count. CMP R8,0 flags survive the intervening loads/store: signed >0 goes to separator 4821D0; otherwise freshly read SP64 byte, test bit 3, and branch unresolved 482206 if clear. Separator path independently reloads old SP32, stores count+1, compares R8,0, reloads SP20, writes low byte R7 at destination+old count; signed <=0 branches 482206.\n\nPositive precision: decrement full R6 modulo 2^32, R0=SXTH(R6); if signed R8<R0 assign full R6=R8. Reload R0=SP20, R3=SP32; R2=SXTH(R6), R1=R4; R0+=R3 modulo 2^32. Call 439BE4 with R3=old count (not destination base), no helper semantics assumption. After call freshly reload SP32 into R1, R6=SXTH(current R6), add R6 to count modulo 2^32 and store SP32. Fallthrough 482200 unresolved. Preserve postincrement ordering, condition-code lifetime, truncations and call boundary. No C, corpus freeze, whole coverage or equality claim.\n")
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
