# SPDX-License-Identifier: MIT
"""Generate the compact reducer's scale table from powers of two and pi.

No firmware data is read by values() or source(). Stock is only a verification
oracle in build(), after the complete source-authored table has been compiled.
"""
import json
import struct
import subprocess
from decimal import Decimal, localcontext, ROUND_HALF_EVEN
from build_gx8002_backup_cfft import ROOT, IMAGE, IMAGE_SHA, sha, Elf32, FLAGS
from verify_gx8002_reducer_accuracy import pi


def values(precision):
    with localcontext() as ctx:
        ctx.prec = precision
        period = 2 * pi(precision)
        result = []
        for index in range(18):
            power = Decimal(2) ** (54 + 52 * index)
            quotient = (power / period).to_integral_value(rounding=ROUND_HALF_EVEN)
            result.append(float((power - quotient * period) / power))
        return result


def source():
    low, high = values(440), values(520)
    assert [v.hex() for v in low] == [v.hex() for v in high]
    return '''/* SPDX-License-Identifier: MIT
 * Generated by generate_gx8002_reducer_scale.py.
 * scale[i] = remainder(2^(54+52*i), 2*pi) / 2^(54+52*i).
 * Quotient uses nearest integer, ties to even; constants round to binary64.
 */
#include <float.h>
_Static_assert(sizeof(double) == 8 && DBL_MANT_DIG == 53 && DBL_MAX_EXP == 1024,
               "binary64 required");
__attribute__((section(".reducer_scale"), used))
const double open_cfw_gx8002_reducer_scale[18] = {
''' + ''.join('    ' + v.hex() + ',\n' for v in high) + '};\n'


def build():
    out = ROOT / 'build/gx8002-reducer-scale'; out.mkdir(exist_ok=True)
    text = source(); c = out / 'scale.c'; c.write_text(text)
    obj, path = out / 'scale.o', out / 'scale.elf'
    pre = str(ROOT / 'build/csky-macos/install/bin/csky-unknown-elf-')
    command = [pre + 'gcc', *FLAGS, '-c', str(c), '-o', str(obj)]
    subprocess.run(command, check=True)
    ld = out / 'scale.ld'
    ld.write_text('SECTIONS { .reducer_scale 0x10015508 : { *(.reducer_scale) } }\n')
    subprocess.run([pre + 'ld', '-T', str(ld), str(obj), '-o', str(path)], check=True)
    elf = Elf32(path.read_bytes(), 'generated reducer scale')
    sections = [s for s in elf.sections if s['flags'] & 2 and s['size']]
    assert len(sections) == 1
    section = sections[0]; body = elf.contents(section)
    assert section['address'] == 0x10015508 and len(body) == 144
    assert not any(elf.relocations(s['index']) for s in elf.sections)
    assert not any(s['name'] and s['section'] == 0 for s in elf.symbols())
    assert body == b''.join(struct.pack('<d', v) for v in values(520))
    stock = IMAGE.read_bytes(); assert sha(stock) == IMAGE_SHA
    assert body == stock[0x4de48:0x4ded8]
    result = {'formula': 'remainder(2^(54+52*i), 2*pi) / 2^(54+52*i), i=0..17',
              'pi_method': 'Machin identity with Decimal arctangent series',
              'precision_crosscheck_digits': [440, 520], 'entries': 18,
              'source_sha256': sha(text.encode()), 'command': command,
              'elf_sha256': sha(path.read_bytes()), 'table_sha256': sha(body),
              'offset': 0x4de48, 'runtime_address': 0x10015508, 'bytes': len(body),
              'stock_sha256': IMAGE_SHA, 'stock_identical': True, 'source_admitted': False,
              'limits': ['Table formula established for all 18 stored entries; this does not validate the stock reducer algorithm.',
                         'Standalone macOS build only; integrated ownership and loader verification pending.']}
    (ROOT / 'docs/research/gx8002-reducer-scale.json').write_text(json.dumps(result, indent=2) + '\n')
    return result


if __name__ == '__main__':
    r = build(); print(r['bytes'], r['table_sha256'])
