#!/usr/bin/env python3
from __future__ import annotations
import csv,hashlib,io,json
from pathlib import Path
R=Path(__file__).resolve().parent.parent;O=R/'components/bootloader/core_overlay/overlay.json';C=R/'tools/manifests/g2-bootloader-post-mspi-frontier.tsv';B=R/'blobs/official/g2-2.2.6.10/ota_s200_bootloader.bin';S=R/'components/bootloader/core_overlay/runtime_spotmgr_temperature_init_42ac54.c';F='open_cfw_bootloader_spotmgr_temperature_init_42ac54';A=0x42AC54;Z=0x42ACA4;H='4c910800d808fd71ce61510588a4bbe388e62974b65a756a73913bdf27482ea4';U='3636b7608940cd6452c1a6127ea5f177682849cc3740f5c98f9a4483a4794450';SH='c7ca1c2524bba42f8b264ddc676e5d568881ce1e8a0e209518b5d00cdf40c908';RS=((0x14,'open_cfw_bootloader_spotmgr_temperature_enable_41bf84',0x41BF84),(0x26,'open_cfw_bootloader_spotmgr_temperature_config_41ca2c',0x41CA2C),(0x38,'open_cfw_bootloader_delay_us_status_change_41d21c',0x41D21C));FL=['-mcpu=cortex-m55','-mthumb','-Oz','-ffreestanding','-fno-builtin','-ffunction-sections','-fdata-sections','-fno-unwind-tables','-fno-asynchronous-unwind-tables','-Wall','-Wextra','-Werror','-fno-ident','-mllvm','-enable-machine-outliner=never']
def h(b):return hashlib.sha256(b).hexdigest()
def main():
 s=S.read_bytes();assert(len(s),h(s))==(2053,SH);assert h(B.read_bytes()[A-0x410000:Z-0x410000])==H;rr=[{'offset':o,'type':'R_ARM_THM_CALL','symbol':n,'symbol_type':'STT_NOTYPE','target_address':t}for o,n,t in RS];p={'size':80,'sha256':H,'unrelocated_sha256':U};e={'function':F,'runtime_address':A,'source':{'path':S.relative_to(R).as_posix(),'size':len(s),'sha256':SH,'license':'BSD-3-Clause','origin':'Apollo510-compatible SPOT-manager temperature monitor initialization','upstream':'AmbiqSuite SDK 5.1.0 Apollo510 SPOT manager','upstream_commit':'5efc0228528a8adce5eae0d226fac85d2551eb3b','evidence':'docs/research/g2-bootloader-spotmgr-temperature-init-42ac54-source-closure.md'},'toolchain':{'target':'arm-none-eabi','reviewed_version_prefix':'Apple clang version 21.0.0','flags':FL},'strict_relocation_contract':True,'expected':p,'stock':{'size':80,'sha256':H},'relocations':rr,'allow_discarded_alloc_sections':True,'toolchain_profiles':{'linux-clang':{'reviewed_version_prefix':'Homebrew clang version 22.1.8','expected':p,'stock':{'size':80,'sha256':H},'relocations':rr}}};o=json.loads(O.read_text());o['in_place_leaves']=sorted([x for x in o['in_place_leaves']if x.get('function')!=F]+[e],key=lambda x:int(x['runtime_address']));t=O.with_name('.overlay.json.tmp');t.write_text(json.dumps(o,indent=2)+'\n');t.replace(O)
 with C.open(newline='')as f:r=csv.DictReader(f,delimiter='\t');fs=r.fieldnames;rows=list(r)
 for x in rows:
  if int(x['start'],16)==A:x.update(kind='source_function',name='spotmgr_temperature_init_42ac54',disposition='source_owned_production',provider='AmbiqSuite Apollo510 SPOT-manager temperature initialization',license_status='BSD-3-Clause',evidence='exact dual-toolchain body, dispatch ingress, three provider edges, and host gate/error routes');break
 else:raise SystemExit('census row missing')
 q=io.StringIO(newline='');w=csv.DictWriter(q,fieldnames=fs,delimiter='\t',lineterminator='\n');w.writeheader();w.writerows(rows);C.write_text(q.getvalue());print('registered SPOT-manager temperature init at 0x0042AC54')
if __name__=='__main__':main()
