#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Report what the transparent build actually established, byte by byte.

The point of this ledger is to keep an honest boundary between three very
different claims:

    recovered   bytes produced by compiling C that came out of the decompiler
    declared    vendor-derived data emitted as source arrays, not reconstructed
    trapped     bytes where nothing was established, and the image says so

"No opaque bytes" means every byte has a source unit behind it.  It does not
mean every byte is understood, and it does not mean the image runs.  This
report states all three numbers so the difference cannot be glossed over.

Usage:
    tools/report_transparent_coverage.py --build build/transparent
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent


def percent(part: int, whole: int) -> str:
    return f"{100.0 * part / whole:.1f}%" if whole else "n/a"


def release_readiness_blockers(summary: dict[str, Any]) -> list[str]:
    """Return strict source-release blockers represented by this ledger.

    Transparent source representation is useful evidence, but it is not a
    release criterion by itself.  A releasable zero-opacity image cannot hide
    unknown behavior in a trap or re-encode proprietary data as a C array.
    Every attempted unit must also compile and fit in the resulting image.
    """
    blockers = []
    if summary["opaque_bytes"] != 0:
        blockers.append(f"{summary['opaque_bytes']} opaque bytes remain")
    if summary["trapped_bytes"] != 0:
        blockers.append(f"{summary['trapped_bytes']} trap bytes remain")
    if summary["declared_data_bytes"] != 0:
        blockers.append(
            f"{summary['declared_data_bytes']} vendor-derived declared-data bytes remain"
        )
    if summary["units_compiled"] != summary["units_total"]:
        blockers.append(
            f"only {summary['units_compiled']} of {summary['units_total']} source units compile"
        )
    if summary["units_placed"] != summary["units_total"]:
        blockers.append(
            f"only {summary['units_placed']} of {summary['units_total']} source units are placed"
        )
    return blockers


def render(build_dir: Path) -> tuple[str, dict[str, Any]]:
    database = json.loads((build_dir / "DB-SUMMARY.json").read_text(encoding="utf-8"))
    manifest = json.loads(
        (build_dir / "source/MANIFEST.json").read_text(encoding="utf-8")
    )
    image = json.loads(
        (build_dir / "image/IMAGE-REPORT.json").read_text(encoding="utf-8")
    )

    total = image["image"]["size"]
    byte_counts = image["bytes"]
    code = byte_counts.get("code", 0)
    padding = byte_counts.get("code-padding", 0)
    data = byte_counts.get("data", 0)
    trapped = byte_counts.get("trap", 0)
    compile_report = manifest.get("compile", {})

    lines = [
        "# Transparent-source coverage ledger",
        "",
        "Generated by `tools/report_transparent_coverage.py`. Every number here",
        "is recomputed from the build; none is carried forward by hand.",
        "",
        "## What the image is made of",
        "",
        "| Origin | Bytes | Share |",
        "| --- | ---: | ---: |",
        f"| Recovered code, compiled from decompiled C | {code:,} | {percent(code, total)} |",
        f"| Envelope padding after placed code | {padding:,} | {percent(padding, total)} |",
        f"| Declared data arrays (vendor-derived) | {data:,} | {percent(data, total)} |",
        f"| Traps where nothing was established | {trapped:,} | {percent(trapped, total)} |",
        f"| **Opaque bytes copied without a source unit** | **{image['opaque_bytes']}** | **0.0%** |",
        f"| Total | {total:,} | 100.0% |",
        "",
        "## Where the code came from",
        "",
        f"* {database['function_count']:,} functions recovered from the image,"
        f" covering {database['code_bytes']:,} bytes.",
        f"* {compile_report.get('compiled', 0):,} of"
        f" {compile_report.get('attempted', 0):,} translation units compile"
        f" ({percent(compile_report.get('compiled', 0), compile_report.get('attempted', 1))}),"
        f" {compile_report.get('compiled_bytes', 0):,} bytes of recovered code.",
        f"* {image['units_placed']:,} functions fit their stock envelope and were placed.",
        "",
        "### Evidence tier of each recovered function",
        "",
        "| Tier | Functions | Bytes |",
        "| --- | ---: | ---: |",
    ]
    for tier, count in database["tier_counts"].items():
        lines.append(f"| {tier} | {count:,} | {database['tier_bytes'].get(tier, 0):,} |")

    lines += [
        "",
        "### Non-code regions, by classification",
        "",
        "| Classification | Regions | Bytes |",
        "| --- | ---: | ---: |",
    ]
    for name, count in database["gap_counts"].items():
        lines.append(f"| {name} | {count:,} | {database['gap_bytes'].get(name, 0):,} |")

    lines += [
        "",
        "## Why bytes are trapped rather than recovered",
        "",
        "| Reason | Count |",
        "| --- | ---: |",
    ]
    for reason, count in sorted(
        image["placement_failures"].items(), key=lambda pair: -pair[1]
    )[:15]:
        lines.append(f"| {reason} | {count:,} |")

    overflow = image.get("envelope_overflow") or {}
    if overflow.get("histogram"):
        order = [
            "<= 2 bytes over", "<= 4 bytes over", "<= 8 bytes over",
            "<= 16 bytes over", "<= 32 bytes over", "<= 64 bytes over",
            "<= 128 bytes over", "<= 256 bytes over", "> 256 bytes over",
        ]
        histogram = overflow["histogram"]
        counted = sum(histogram.values())
        lines += [
            "",
            "### By how much recovered code overshoots its stock envelope",
            "",
            "One row per function, measured at its best optimization variant.",
            "The stock image reaches constants through shared literal pools in",
            "two bytes; recovered code materialises the same address inline in",
            "eight. That is why the distribution piles up just over the line.",
            "",
            "| Overshoot | Functions |",
            "| --- | ---: |",
        ]
        for band in order:
            if band in histogram:
                lines.append(f"| {band} | {histogram[band]:,} |")
        lines += [
            "",
            f"Total overshoot across {counted:,} unplaceable functions:"
            f" {overflow.get('total_bytes', 0):,} bytes.",
        ]

    if image.get("size_variants_used"):
        lines += [
            "",
            "### Optimization variant that made each placed function fit",
            "",
            "| Variant | Functions |",
            "| --- | ---: |",
        ]
        for variant, count in sorted(
            image["size_variants_used"].items(), key=lambda pair: -pair[1]
        ):
            lines.append(f"| {variant} | {count:,} |")

    lines += [
        "",
        "## What this does not establish",
        "",
        "* **The image is not known to run.** Decompiler output is recovered",
        "  structure, not reviewed behavior. A unit that compiles has been made",
        "  well-formed; nothing here shows it computes what the stock code did.",
        "* **Declared data is not reconstructed data.** Fonts, bitmaps and",
        "  tables are vendor bytes rendered as source. Emitting them as arrays",
        "  makes them visible and editable; it does not explain them.",
        "* **Traps are honest failures.** Where the corpus establishes nothing,",
        "  the image halts rather than running invented behavior.",
        "",
        f"For reference, {image['stock_reference']['bytes_identical_to_stock']:,}"
        f" of {total:,} bytes"
        f" ({percent(image['stock_reference']['bytes_identical_to_stock'], total)})"
        " happen to match the stock payload -- almost all of that is the",
        "declared data, which is byte-identical by construction.",
        "",
    ]

    summary = {
        "total_bytes": total,
        "recovered_code_bytes": code,
        "declared_data_bytes": data,
        "trapped_bytes": trapped,
        "opaque_bytes": image["opaque_bytes"],
        "units_compiled": compile_report.get("compiled", 0),
        "units_total": compile_report.get("attempted", 0),
        "units_placed": image["units_placed"],
    }
    return "\n".join(lines), summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build", type=Path, default=REPO_ROOT / "build/transparent")
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "docs/transparent-source-ledger.md",
    )
    parser.add_argument(
        "--require-release-ready",
        action="store_true",
        help=(
            "fail unless opacity, traps, vendor-derived declared data, compile "
            "failures, and placement failures are all zero"
        ),
    )
    args = parser.parse_args(argv)

    try:
        text, summary = render(args.build.resolve())
    except FileNotFoundError as failure:
        print(f"error: {failure}", file=sys.stderr)
        return 2

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(json.dumps(summary, indent=2, sort_keys=True))
    if args.require_release_ready:
        blockers = release_readiness_blockers(summary)
        if blockers:
            print(
                json.dumps({"release_ready": False, "blockers": blockers}, indent=2),
                file=sys.stderr,
            )
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
