/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 2025, Ambiq Micro, Inc.
 * All rights reserved.
 *
 * Bounded Apollo510 SPOT-manager timer initialization adapted from
 * AmbiqSuite SDK 5.1.0. Reviewed stock and SDK evidence is recorded in
 * EVIDENCE.md.
 */

typedef __UINTPTR_TYPE__ open_cfw_spotmgr_timer_init_uintptr;

#define OPEN_CFW_SPOTMGR_TIMER_INIT_CTRL0_ADDRESS 0x400083E0U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE0_ADDRESS 0x400083E8U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE1_ADDRESS 0x400083ECU
#define OPEN_CFW_SPOTMGR_TIMER_INIT_MODE0_ADDRESS 0x400083F0U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_INTEN_ADDRESS 0x40008060U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_INTCLR_ADDRESS 0x40008068U

#define OPEN_CFW_SPOTMGR_TIMER_INIT_ENABLE_MASK 0x00000001U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_CTRL0_VALUE 0x00000110U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_MODE0_VALUE 0x00000100U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE_VALUE 0xFFFFFFFFU
#define OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE_BOTH_MASK 0xC0000000U
#define OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE0_MASK 0x40000000U

#ifndef OPEN_CFW_SPOTMGR_TIMER_INIT_READ32
#define OPEN_CFW_SPOTMGR_TIMER_INIT_READ32(address) \
    (*(const volatile unsigned int *)( \
        open_cfw_spotmgr_timer_init_uintptr)(address))
#endif

#ifndef OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32
#define OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(address, value) \
    (*(volatile unsigned int *)( \
        open_cfw_spotmgr_timer_init_uintptr)(address) = (value))
#endif

/*
 * ABI-compatible source replacement for AmbiqSuite's public
 * am_hal_spotmgr_timer_init at 0x004801FC...0x0048023F.
 */
__attribute__((used, noinline))
void open_cfw_spotmgr_timer_init(void)
{
    unsigned int value;

    value = OPEN_CFW_SPOTMGR_TIMER_INIT_READ32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_CTRL0_ADDRESS
    );
    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_CTRL0_ADDRESS,
        value & ~OPEN_CFW_SPOTMGR_TIMER_INIT_ENABLE_MASK
    );

    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_CTRL0_ADDRESS,
        OPEN_CFW_SPOTMGR_TIMER_INIT_CTRL0_VALUE
    );
    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_MODE0_ADDRESS,
        OPEN_CFW_SPOTMGR_TIMER_INIT_MODE0_VALUE
    );
    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE0_ADDRESS,
        OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE_VALUE
    );
    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE1_ADDRESS,
        OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE_VALUE
    );
    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_INTCLR_ADDRESS,
        OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE_BOTH_MASK
    );

    value = OPEN_CFW_SPOTMGR_TIMER_INIT_READ32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_INTEN_ADDRESS
    );
    OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32(
        OPEN_CFW_SPOTMGR_TIMER_INIT_INTEN_ADDRESS,
        value | OPEN_CFW_SPOTMGR_TIMER_INIT_COMPARE0_MASK
    );
}

#undef OPEN_CFW_SPOTMGR_TIMER_INIT_WRITE32
#undef OPEN_CFW_SPOTMGR_TIMER_INIT_READ32
