from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x4826fc;end=0x48277e
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21261/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Zero-argument wrapper and sparse or packed byte-key lookup\n\nPartial/unaccepted;130 instructionbytes4826FC..48277E. Separate4826FC wrapper PUSH{R7,LR}8bytes,R2=entryR1,R1=0,call454746 withentryR0/liveR3;POP{R0,PC} returns savedentryR7 ratherthan helperresult. Frameless482708 freshly readsbyte[entryR0+8],returns1ifequals255else0,BXLR.\n\n482716 lookup PUSH{R4,R5,R6,LR}16bytes;R6=entryR0 descriptor,R5=entryR1 key,R4=entryR2 output. Call482708(R0=R6,liveR1/R2/R3). Nonzero result: freshword[R6]→R1 table,R2=0. Loop freshbyte[R1+8*R2 modulo] firsttestsNUL;zero→return0. Otherwise independently reread samebyte and compareUXTB(R5);mismatchR2++modrepeat. Match freshword[R1+8*R2+4]→R0,store[R4],return1.\n\nZero predicate: freshword[R6]→R0, freshbyte[R6+8]→R1, compute retainedkeybaseR0+=4*R1 modulo;R1=0. Eachiteration independently rereadsbyte[R6+8]countR2;unsignedR1>=R2→return0. Freshbyte[keybase+R1] compareUXTB(R5);mismatchincrementR1andretest. Match independentlyreloadword[R6]→R0, freshword[R0+4*R1]→R0,store[R4],return1. BothreturnsPOP{R4,R5,R6,PC}. No outputwriteonmiss/no nullguards;preserve repeated fresh reads and packedkeybase computedfrominitialcount versus reloadedloopcount. Next48277E belongsanotherhelper. No C,freeze,wholecoverage or equalityclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
