from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47efcc;end=0x47f0a0
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21035/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Mode update, bounded bit-two polling, conditional cleanup and status return\n\nPartial/unaccepted;212 instruction bytes 47EFCC..47F0A0, continuation of map21432 (40-byte frame active; R5 entry mode; SP4 saved 473940 result). Mode-two path: fresh word through literal F950, bit24 clear sets R4=1 and skips mode update/poll. Otherwise R8=literal FAB4 pointer, fresh word bits0..1 replaced with LOW8(R5)&3; R4=4, R9=0. Before each fresh bit2 read, unsigned counter>=20 exits; bit2=1 sets R4=0, otherwise 4807A0(1, live other arguments), counter++ and repeat. Thus at most20 reads/delay calls; no read after twentieth delay. At F018, LOW8(R6)!=0 independently reloads word[R7] and clears bit5; then 4803DC(live arguments), regardless of status.\n\nNon-mode-two entry F02C: R6=literal FAB4 pointer, identical fresh bits0..1 update; R4=4,R7=0; same unsigned limit20/read-bit2/delay loop, no F018 cleanup or 4803DC call. Shared F05A: status0 writes LOW8(entry mode) to byte through literal FAB8, then LOW8(mode)!=2 writes byte SP1=0 and calls480312(0,0,SP+1,live R3). Status nonzero only LOW8(mode)==2 writes byte SP0=0 and calls480312(0,0,SP,live R3). These stack byte writes alter saved entry R1 word; helper pointer writes remain possible. Common F094 loads SP4 into R0, MSR PRIMASK,R0, returns full R4 in R0; POP R1..R9,PC releases40. Restored R1 may reflect local/helper byte mutations; R2 receives saved helper result at SP4. External helper semantics and pointed addresses unresolved; no MMIO or hardware timing assumption. No C/freeze/whole-corpus claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
