from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x482112;end=0x482174
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-fixed-float-leading-zero-separator-fraction-copy-layout-21632-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Fixed floating layout leading zero, separator and fractional copy\n\nPartial/unaccepted; 98 instruction bytes 482112..482174. Continues the 481836 formatter with its 232-byte frame. R11=SXTH(R5); if signed R11>0 branch to unresolved 482286. Otherwise load SP32 count into R0, store count+1 modulo 2^32 before loading SP20 destination and storing ASCII 48 at destination+old count. Signed R8>0 takes separator insertion directly; otherwise freshly read byte SP64, test bit 3 via LSL28 sign, and skip separator if clear. Separator insertion independently reloads/increments/stores SP32 then reloads SP20 and stores low byte R7 at destination+old count.\n\nCMN R8,R11 supplies overflow-aware signed LT condition (N!=V); if LT R5=-R8 modulo 2^32, otherwise retain original full R5. Then R5=SXTH(R5), R0=-R5 modulo 2^32, R5+=R8 modulo 2^32; R2=SXTH(R6); store R0 to SP44. If signed R5<R2 assign R6=R5, otherwise retain full R6. Reload R3=word SP20 and R0=word SP32; R6=SXTH(R6); store R6 to SP36. Set R2=R6, R1=R4 digit pointer, R0=R0+R3 modulo 2^32; call 439BE4 with these and live R3=destination base. Helper semantics and result are not assumed. After call subtract current R6 from current R5 modulo 2^32, store SP48, branch unresolved 48231A. Preserve halfword truncation, ordered fresh loads/stores, full argument bit patterns and call clobber boundary. No C, freeze, whole coverage or byte-equality claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
