INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Generic)

IF(NOT "$ENV{MW_INSTALL_PATH}" STREQUAL "")
    SET(MW_INSTALL_PATH $ENV{MW_INSTALL_PATH})
    SET(CMAKE_PREFIX_PATH  "$ENV{MW_INSTALL_PATH}/arc/bin/")
ELSE()
    FIND_PROGRAM(CCAC_PATH ccac)
    IF("${CCAC_PATH}" STREQUAL "CCAC_PATH-NOTFOUND")
        MESSAGE(FATAL_ERROR "Request CCAC compiler to be defined in PATH environment variable.")
    ENDIF()
    STRING(LENGTH ${CCAC_PATH} STRLENGTH)
    MATH(EXPR STRSIZE "${STRLENGTH} - 12")
    STRING(SUBSTRING ${CCAC_PATH} 0 ${STRSIZE} MW_INSTALL_PATH)
ENDIF()

CMAKE_FORCE_C_COMPILER(ccac GNU)
CMAKE_FORCE_CXX_COMPILER(ccac GNU)
SET(CMAKE_ASM_COMPILER ccac)
SET(CMAKE_AR ${CMAKE_PREFIX_PATH}arac CACHE FILEPATH "Archiver")

# Make arguments for eclipse
SET(CMAKE_ECLIPSE_MAKE_ARGUMENTS "-C ${CMAKE_BINARY_DIR}"
    CACHE STRING "Make arguments."
)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)

SET(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES
    "${MW_INSTALL_PATH}/arc/inc"
    "${MW_INSTALL_PATH}/arc/incc"
)

SET(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES
    "${MW_INSTALL_PATH}/arc/inc"
    "${MW_INSTALL_PATH}/arc/incc"
)

SET(CMAKE_C_CREATE_STATIC_LIBRARY
    "<CMAKE_AR> qcr <TARGET> <LINK_FLAGS> <OBJECTS>"
)

SET(CMAKE_C_ARCHIVE_APPEND
    "<CMAKE_AR> qr <TARGET> <LINK_FLAGS> <OBJECTS>"
)

SET(CMAKE_CXX_CREATE_STATIC_LIBRARY
    "<CMAKE_AR> qcr <TARGET> <LINK_FLAGS> <OBJECTS>"
)

SET(CMAKE_CXX_ARCHIVE_APPEND
    "<CMAKE_AR> qr <TARGET> <LINK_FLAGS> <OBJECTS>"
)

SET(CMAKE_ASM_CREATE_STATIC_LIBRARY
    "<CMAKE_AR> qcr <TARGET> <LINK_FLAGS> <OBJECTS>"
)

SET(CMAKE_ASM_ARCHIVE_APPEND
    "<CMAKE_AR> qr <TARGET> <LINK_FLAGS> <OBJECTS>"
)
