/* SPDX-License-Identifier: MIT */
#include "pt_protocol_handlers_transfer.h"

static int valid(const uint8_t*r,uint8_t n,uint8_t m){return r!=NULL&&n>=m;}
static uint32_t get32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8U)|((uint32_t)p[2]<<16U)|((uint32_t)p[3]<<24U);}
static uint16_t crc16(const uint8_t*d,size_t n){uint16_t c=0xFFFFU;size_t i;unsigned int b;for(i=0U;i<n;++i){c^=(uint16_t)d[i]<<8U;for(b=0U;b<8U;++b)c=(uint16_t)((c&0x8000U)!=0U?(c<<1U)^0x1021U:c<<1U);}return c;}
static int status_payload(uint8_t command,uint8_t status,uint8_t tag,uint8_t*p,uint8_t*l){return open_cfw_pt_make_status_payload(command,status,tag,p,l);}

void open_cfw_pt_transfer_initialize(struct open_cfw_pt_transfer_service*s,const struct open_cfw_pt_transfer_providers*p,uint8_t*staging,size_t staging_capacity){if(s==NULL)return;s->providers=p;s->expected_sequence=0U;s->staging=staging;s->staging_capacity=staging_capacity;s->staging_length=0U;s->payload_open=0;}

static int h2a(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint8_t status;if(!valid(r,n,4U)||s==NULL||s->providers==NULL||s->providers->storage_self_test==NULL||s->providers->storage_self_test(&status,s->providers->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return status_payload(0x35U,status,3U,p,l);}
static int h52(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;if(!valid(r,n,4U)||s==NULL||s->providers==NULL||s->providers->ota_initialize==NULL||s->providers->ota_dispatch==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;s->expected_sequence=0U;s->staging_length=0U;if(s->providers->ota_initialize(s->providers->context)!=0||s->providers->ota_dispatch(0U,NULL,0U,s->providers->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return status_payload(0x52U,0U,3U,p,l);}
static int h53(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint8_t status;if(!valid(r,n,132U)||s==NULL||s->providers==NULL||s->providers->ota_dispatch==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;if(r[3]!=0x80U)status=3U;else if(s->providers->ota_dispatch(1U,r+4U,128U,s->providers->context)!=0||s->providers->ota_dispatch(2U,NULL,0U,s->providers->context)!=0)status=1U;else status=0U;return status_payload(0x53U,status,3U,p,l);}

static int flush(struct open_cfw_pt_transfer_service*s){int result;if(s->staging_length==0U)return 0;result=s->providers->ota_dispatch(4U,s->staging,s->staging_length,s->providers->context);s->staging_length=0U;return result;}
static int h54(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint16_t declared,expected_crc;size_t bytes,i;uint8_t final,sequence,status=1U;if(!valid(r,n,9U)||s==NULL||s->providers==NULL||s->providers->ota_dispatch==NULL||s->staging==NULL||s->staging_capacity<1000U)return OPEN_CFW_PT_INVALID_ARGUMENT;declared=(uint16_t)r[3]|((uint16_t)r[4]<<8U);final=r[5]!=0U;sequence=r[6];if(declared<4U)return status_payload(0x54U,1U,3U,p,l);bytes=(size_t)declared-4U;if(bytes>1000U||7U+bytes+2U>(size_t)n)return status_payload(0x54U,1U,3U,p,l);expected_crc=(uint16_t)r[7U+bytes]|((uint16_t)r[8U+bytes]<<8U);if(sequence==s->expected_sequence){if(crc16(r+7U,bytes)!=expected_crc)return status_payload(0x54U,1U,3U,p,l);if(s->staging_length+bytes>s->staging_capacity&&flush(s)!=0)return status_payload(0x54U,1U,3U,p,l);for(i=0U;i<bytes;++i)s->staging[s->staging_length+i]=r[7U+i];s->staging_length+=bytes;s->expected_sequence=(uint8_t)(sequence+1U);if((s->staging_length>=s->staging_capacity||final)&&flush(s)!=0)return status_payload(0x54U,1U,3U,p,l);status=0U;}else if(s->expected_sequence==(uint8_t)(sequence+1U)){s->expected_sequence=(uint8_t)(sequence+1U);status=0U;}return status_payload(0x54U,status,3U,p,l);}

static int h55(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint8_t status;(void)r;(void)n;if(s==NULL||s->providers==NULL||s->providers->ota_dispatch==NULL||s->providers->ota_status==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;if(s->providers->ota_dispatch(3U,NULL,0U,s->providers->context)!=0||s->providers->ota_status(&status,s->providers->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return status_payload(0x55U,status,3U,p,l);}
static int h58(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;if(!valid(r,n,8U)||s==NULL||s->providers==NULL||s->providers->read_metadata_32==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;p[0]=0x58U;p[1]=1U;p[2]=2U;p[3]=32U;*l=36U;if(s->providers->read_metadata_32(p+4U,32U,s->providers->context)!=0)return status_payload(0x58U,1U,2U,p,l);return 0;}
static int h59(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint8_t ready;if(!valid(r,n,4U)||s==NULL||s->providers==NULL||s->providers->storage_ready==NULL||s->providers->open_payload==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;if(s->providers->storage_ready(&ready,s->providers->context)!=0||ready==0U)return status_payload(0x59U,1U,2U,p,l);if(s->payload_open&&s->providers->close_payload!=NULL)(void)s->providers->close_payload(s->providers->context);s->payload_open=0;if(s->providers->open_payload(s->providers->context)!=0)return status_payload(0x59U,1U,2U,p,l);s->payload_open=1;return status_payload(0x59U,0U,2U,p,l);}
static int h5a(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint8_t count,sum=0U;size_t received,i;uint32_t offset;if(!valid(r,n,9U)||s==NULL||s->providers==NULL||s->providers->read_payload_at==NULL||!s->payload_open)return status_payload(0x5AU,1U,2U,p,l);offset=get32(r+4U)+32U;count=r[8];if(count>240U)return status_payload(0x5AU,1U,2U,p,l);if(s->providers->read_payload_at(offset,p+4U,count,&received,s->providers->context)!=0||received>count)return status_payload(0x5AU,1U,2U,p,l);p[0]=0x5AU;p[1]=1U;p[2]=2U;p[3]=(uint8_t)(received+1U);for(i=0U;i<received;++i)sum=(uint8_t)(sum+p[4U+i]);p[4U+received]=sum;*l=(uint8_t)(5U+received);return 0;}
static int h5b(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){struct open_cfw_pt_transfer_service*s=c;uint8_t status;if(!valid(r,n,9U)||s==NULL||s->providers==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;if(s->payload_open&&s->providers->close_payload!=NULL)(void)s->providers->close_payload(s->providers->context);s->payload_open=0;status=r[4]==0U?0U:1U;return status_payload(0x5BU,status,2U,p,l);}
static int h60(const uint8_t*r,uint8_t n,uint8_t*p,uint8_t*l,void*c){size_t i;(void)c;if(!valid(r,n,250U))return status_payload(0xF3U,1U,2U,p,l);for(i=0U;i<246U;++i)if(r[4U+i]!=(uint8_t)i)return status_payload(0xF3U,1U,2U,p,l);return status_payload(0xF3U,0U,2U,p,l);}

int open_cfw_pt_bind_transfer_handlers(struct open_cfw_pt_protocol*protocol,struct open_cfw_pt_transfer_service*service){static const struct{uint8_t command;open_cfw_pt_handler_fn handler;}bindings[]={
{0x2AU,h2a},{0x52U,h52},{0x53U,h53},{0x54U,h54},{0x55U,h55},{0x58U,h58},{0x59U,h59},{0x5AU,h5a},{0x5BU,h5b},{0x60U,h60},};size_t i;if(protocol==NULL||service==NULL||service->providers==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;for(i=0U;i<sizeof(bindings)/sizeof(bindings[0]);++i)if(open_cfw_pt_protocol_bind(protocol,bindings[i].command,bindings[i].handler,service)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return 0;}
