/* SPDX-License-Identifier: MIT */
#include "pt_protocol_handlers_services.h"

static int valid(const uint8_t *r,uint8_t n,uint8_t m){return r!=NULL&&n>=m;}
static int mode(const struct open_cfw_pt_service_providers *x){uint8_t v;if(x==NULL||x->get_product_mode==NULL||x->get_product_mode(&v,x->context)!=0)return -1;return v==1U;}
static void put32(uint8_t *p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);p[2]=(uint8_t)(v>>16U);p[3]=(uint8_t)(v>>24U);}
static int header(uint8_t c,uint8_t tag,uint8_t n,uint8_t *p,uint8_t *l){if(p==NULL||l==NULL)return -1;p[0]=c;p[1]=1U;p[2]=tag;p[3]=n;*l=(uint8_t)(4U+n);return 0;}

static int handler_0b(const uint8_t *r,uint8_t n,uint8_t *p,uint8_t *l,void *c){const struct open_cfw_pt_service_providers*x=c;if(!valid(r,n,4U)||x==NULL||x->read_box_summary_7==NULL||header(0x11U,3U,7U,p,l)!=0)return OPEN_CFW_PT_INVALID_ARGUMENT;return x->read_box_summary_7(p+4U,7U,x->context)==0?0:OPEN_CFW_PT_HANDLER_FAILED;}
static int handler_11(const uint8_t *r,uint8_t n,uint8_t *p,uint8_t *l,void *c){const struct open_cfw_pt_service_providers*x=c;if(!valid(r,n,4U)||x==NULL||x->read_box_detail_6==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;if(n>5U){if(x->set_box_state==NULL||x->set_box_state((uint8_t)(r[4]&0x7FU),(uint8_t)(r[4]>>7U),n>6U,n>6U&&r[5]==2U,x->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;}if(header(0x13U,2U,6U,p,l)!=0)return OPEN_CFW_PT_INVALID_ARGUMENT;return x->read_box_detail_6(p+4U,6U,x->context)==0?0:OPEN_CFW_PT_HANDLER_FAILED;}
static int handler_24(const uint8_t *r,uint8_t n,uint8_t *p,uint8_t *l,void *c){const struct open_cfw_pt_service_providers*x=c;int m;uint8_t result=5U;if(!valid(r,n,25U))return OPEN_CFW_PT_INVALID_ARGUMENT;m=mode(x);if(m<0)return OPEN_CFW_PT_HANDLER_FAILED;if(m&&x->write_and_verify_time_21!=NULL)result=x->write_and_verify_time_21(r+4U,21U,x->context)==0?0U:1U;return open_cfw_pt_make_status_payload(0x29U,result,3U,p,l);}
static int handler_31(const uint8_t *r,uint8_t n,uint8_t *p,uint8_t *l,void *c){const struct open_cfw_pt_service_providers*x=c;uint8_t result;if(!valid(r,n,4U)||x==NULL||x->uart_sync_test==NULL||x->uart_sync_test(&result,x->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return open_cfw_pt_make_status_payload(0x43U,result,3U,p,l);}
static int handler_3d(const uint8_t *r,uint8_t n,uint8_t *p,uint8_t *l,void *c){const struct open_cfw_pt_service_providers*x=c;uint32_t measurement;uint8_t status;int m;if(!valid(r,n,5U)||x==NULL||x->calibrate_ambient==NULL||p==NULL||l==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;m=mode(x);if(m<0)return OPEN_CFW_PT_HANDLER_FAILED;if(!m){measurement=0U;status=5U;}else if(x->calibrate_ambient(r[4],&measurement,&status,x->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;p[0]=0x2EU;p[1]=1U;p[2]=3U;p[3]=6U;p[4]=status;p[5]=r[4];put32(p+6U,measurement);*l=10U;return 0;}
static int handler_49(const uint8_t *r,uint8_t n,uint8_t *p,uint8_t *l,void *c){const struct open_cfw_pt_service_providers*x=c;uint8_t result;if(!valid(r,n,4U)||x==NULL||x->lens_sync_test==NULL||x->lens_sync_test(&result,x->context)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return open_cfw_pt_make_status_payload(0x49U,result,3U,p,l);}

int open_cfw_pt_bind_service_handlers(struct open_cfw_pt_protocol *protocol,const struct open_cfw_pt_service_providers *providers){static const struct{uint8_t command;open_cfw_pt_handler_fn handler;}bindings[]={
{0x0BU,handler_0b},{0x11U,handler_11},{0x24U,handler_24},{0x31U,handler_31},{0x3DU,handler_3d},{0x49U,handler_49},};size_t i;if(protocol==NULL||providers==NULL)return OPEN_CFW_PT_INVALID_ARGUMENT;for(i=0U;i<sizeof(bindings)/sizeof(bindings[0]);++i)if(open_cfw_pt_protocol_bind(protocol,bindings[i].command,bindings[i].handler,(void*)providers)!=0)return OPEN_CFW_PT_HANDLER_FAILED;return 0;}
