/*
 * SPDX-License-Identifier: MIT
 *
 * Source-owned exact helpers from the AM-064 retained island.
 */

#if defined(OPEN_CFW_AM064_D039E_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d039e(void)
{
    __asm__ volatile(
        "push {r4, r5, r6, lr}\n"
        "movs r4, r0\n"
        "movs r5, r1\n"
        "movs r6, r2\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfdb4\n"
        "bl .\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d039e_0026\n"
        "movw r2, #0x2c9\n"
        "ldr.w r1, [pc, #0x2f4]\n"
        "ldr.w r0, [pc, #0x5bc]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d09b4\n"
        "bl .\n"
        "nop.w\n"
        "L_open_cfw_runtime_am064_d039e_0026:\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d01bc\n"
        "bl .\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d039e_0050\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d01d4\n"
        "bl .\n"
        "movs r6, r0\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfe88\n"
        "bl .\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfde8\n"
        "bl .\n"
        "movs r1, r6\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d019a\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d039e_0050:\n"
        "pop {r4, r5, r6, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D03F0_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d03f0(void)
{
    __asm__ volatile(
        "push {r4, r5, r6, lr}\n"
        "movs r4, r0\n"
        "movs r5, r1\n"
        "movs r6, r2\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfdb4\n"
        "bl .\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d03f0_0026\n"
        "movw r2, #0x2d6\n"
        "ldr.w r1, [pc, #0x2a4]\n"
        "ldr.w r0, [pc, #0x570]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d09b4\n"
        "bl .\n"
        "nop.w\n"
        "L_open_cfw_runtime_am064_d03f0_0026:\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d01bc\n"
        "bl .\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d03f0_0052\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d01d4\n"
        "bl .\n"
        "movs r5, r0\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfdf6\n"
        "bl .\n"
        "movs r1, r5\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d033a\n"
        "bl .\n"
        "movs r1, r0\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d019a\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d03f0_0052:\n"
        "pop {r4, r5, r6, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0444_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0444(void)
{
    __asm__ volatile(
        "push {r3, r4, r5, r6, r7, lr}\n"
        "movs r4, r0\n"
        "movs r5, r1\n"
        "movs r6, r2\n"
        "movs r7, r5\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d01bc\n"
        "bl .\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d0444_003c\n"
        "ldr.w r0, [pc, #0x508]\n"
        "ldr r0, [r0]\n"
        "subs r6, r6, r0\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d01d4\n"
        "bl .\n"
        "movs r7, r0\n"
        "movs r0, r7\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfde8\n"
        "bl .\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfe88\n"
        "bl .\n"
        "movs r1, r5\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d019a\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0444_003c:\n"
        "movs r0, r7\n"
        "pop {r1, r4, r5, r6, r7, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0484_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0484(void)
{
    __asm__ volatile(
        "push {r2, r3, r4, r5, r6, lr}\n"
        "movs r6, r0\n"
        "movs r5, r1\n"
        "movs r0, #0\n"
        "str r0, [sp]\n"
        "movs r0, #0\n"
        "str r0, [sp, #4]\n"
        "movs r4, #0\n"
        "cmp r5, #0\n"
        "beq L_open_cfw_runtime_am064_d0484_0030\n"
        "add r2, sp, #4\n"
        "mov r1, sp\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cff9a\n"
        "bl .\n"
        "ldr r0, [sp]\n"
        "cmp r0, #0x18\n"
        "bge L_open_cfw_runtime_am064_d0484_0030\n"
        "add r2, sp, #4\n"
        "mov r1, sp\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cffc2\n"
        "bl .\n"
        "movs r4, r0\n"
        "L_open_cfw_runtime_am064_d0484_0030:\n"
        "cmp r4, #0\n"
        "beq L_open_cfw_runtime_am064_d0484_005e\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfd70\n"
        "bl .\n"
        "cmp r0, r5\n"
        "bhs L_open_cfw_runtime_am064_d0484_0052\n"
        "movw r2, #0x309\n"
        "ldr.w r1, [pc, #0x1e4]\n"
        "ldr.w r0, [pc, #0x4b4]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d09b4\n"
        "bl .\n"
        "nop.w\n"
        "L_open_cfw_runtime_am064_d0484_0052:\n"
        "ldr r3, [sp, #4]\n"
        "ldr r2, [sp]\n"
        "movs r1, r4\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d003a\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0484_005e:\n"
        "movs r0, r4\n"
        "pop {r1, r2, r4, r5, r6, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D04E6_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d04e6(void)
{
    __asm__ volatile(
        "push {r4, r5, r6, lr}\n"
        "movs r6, r0\n"
        "movs r5, r1\n"
        "movs r4, r2\n"
        "movs r0, #0\n"
        "cmp r5, #0\n"
        "beq L_open_cfw_runtime_am064_d04e6_003c\n"
        "cmp r4, #0\n"
        "bne L_open_cfw_runtime_am064_d04e6_0026\n"
        "movw r2, #0x315\n"
        "ldr.w r1, [pc, #0x1ac]\n"
        "ldr.w r0, [pc, #0x480]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d09b4\n"
        "bl .\n"
        "nop.w\n"
        "L_open_cfw_runtime_am064_d04e6_0026:\n"
        "movs r2, r4\n"
        "movs r1, r5\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d039e\n"
        "bl .\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfeac\n"
        "bl .\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfe10\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d04e6_003c:\n"
        "pop {r4, r5, r6, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0524_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0524(void)
{
    __asm__ volatile(
        "str r0, [r0, #8]\n"
        "str r0, [r0, #0xc]\n"
        "movs r1, #0\n"
        "str r1, [r0, #0x10]\n"
        "movs r1, #0\n"
        "b L_open_cfw_runtime_am064_d0524_001e\n"
        "L_open_cfw_runtime_am064_d0524_000c:\n"
        "lsls r3, r1, #7\n"
        "add r3, r0\n"
        "add.w r3, r3, r2, lsl #2\n"
        "str r0, [r3, #0x74]\n"
        "adds r2, r2, #1\n"
        "L_open_cfw_runtime_am064_d0524_0018:\n"
        "cmp r2, #0x20\n"
        "blt L_open_cfw_runtime_am064_d0524_000c\n"
        "adds r1, r1, #1\n"
        "L_open_cfw_runtime_am064_d0524_001e:\n"
        "cmp r1, #0x18\n"
        "bge L_open_cfw_runtime_am064_d0524_002e\n"
        "movs r2, #0\n"
        "add.w r3, r0, r1, lsl #2\n"
        "str r2, [r3, #0x14]\n"
        "movs r2, #0\n"
        "b L_open_cfw_runtime_am064_d0524_0018\n"
        "L_open_cfw_runtime_am064_d0524_002e:\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0554_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0554(void)
{
    __asm__ volatile(
        "push {r2, r3, r4, r5, r6, lr}\n"
        "movs r5, r0\n"
        "movs r6, r1\n"
        "movs r4, r2\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfe04\n"
        "bl .\n"
        "cmp r4, #0\n"
        "beq L_open_cfw_runtime_am064_d0554_0018\n"
        "ldr.w r2, [pc, #0x420]\n"
        "b L_open_cfw_runtime_am064_d0554_001c\n"
        "L_open_cfw_runtime_am064_d0554_0018:\n"
        "ldr.w r2, [pc, #0x41c]\n"
        "L_open_cfw_runtime_am064_d0554_001c:\n"
        "str r0, [sp]\n"
        "movs r3, r6\n"
        "movs r1, r5\n"
        "ldr.w r0, [pc, #0x418]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000733ee\n"
        "bl .\n"
        "pop {r0, r1, r4, r5, r6, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0608_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0608(void)
{
    __asm__ volatile(
        "push {r3, r4, r5, r6, r7, lr}\n"
        "movs r5, r0\n"
        "movs r4, r1\n"
        "movs r7, r2\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d05fa\n"
        "bl .\n"
        "movs r6, r0\n"
        "movs r1, #4\n"
        "subs r7, r7, r6\n"
        "movs r0, r7\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfeee\n"
        "bl .\n"
        "movs r7, r0\n"
        "ands r0, r4, #3\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d0608_0030\n"
        "movs r1, #4\n"
        "ldr.w r0, [pc, #0x368]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000733ee\n"
        "bl .\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d0608_00a2\n"
        "L_open_cfw_runtime_am064_d0608_0030:\n"
        "ldr r0, [pc, #0x218]\n"
        "ldr r1, [r0]\n"
        "cmp r7, r1\n"
        "blo L_open_cfw_runtime_am064_d0608_0040\n"
        "ldr r1, [pc, #0xa4]\n"
        "ldr r1, [r1]\n"
        "cmp r1, r7\n"
        "bhs L_open_cfw_runtime_am064_d0608_0058\n"
        "L_open_cfw_runtime_am064_d0608_0040:\n"
        "ldr r1, [pc, #0x9c]\n"
        "ldr r2, [r1]\n"
        "adds r2, r2, r6\n"
        "ldr r0, [r0]\n"
        "adds r6, r0, r6\n"
        "movs r1, r6\n"
        "ldr.w r0, [pc, #0x344]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000733ee\n"
        "bl .\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d0608_00a2\n"
        "L_open_cfw_runtime_am064_d0608_0058:\n"
        "ldr.w r0, [pc, #0x300]\n"
        "ldr r1, [r0]\n"
        "rsbs r1, r1, #0\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfe1a\n"
        "bl .\n"
        "movs r6, r0\n"
        "movs r1, r7\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfd84\n"
        "bl .\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfdc0\n"
        "bl .\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfdf6\n"
        "bl .\n"
        "movs r1, r6\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d019a\n"
        "bl .\n"
        "movs r0, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfe88\n"
        "bl .\n"
        "movs r5, r0\n"
        "movs r1, #0\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfd84\n"
        "bl .\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfdce\n"
        "bl .\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000cfde8\n"
        "bl .\n"
        "movs r0, r4\n"
        "L_open_cfw_runtime_am064_d0608_00a2:\n"
        "pop {r1, r4, r5, r6, r7, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D06B4_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d06b4(void)
{
    __asm__ volatile(
        "push {r4, lr}\n"
        "movs r4, r0\n"
        "ands r0, r4, #3\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d06b4_0018\n"
        "movs r1, #4\n"
        "ldr r0, [pc, #0x2e0]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000733ee\n"
        "bl .\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d06b4_0020\n"
        "L_open_cfw_runtime_am064_d06b4_0018:\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d0524\n"
        "bl .\n"
        "movs r0, r4\n"
        "L_open_cfw_runtime_am064_d06b4_0020:\n"
        "pop {r4, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D09B4_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d09b4(void)
{
    __asm__ volatile(
        "push {lr}\n"
        "sub sp, #0xc\n"
        "str r1, [sp]\n"
        "str r2, [sp, #4]\n"
        "str r0, [sp, #8]\n"
        "mov r2, sp\n"
        "ldr r1, [pc, #0x10]\n"
        "movs r0, #0x18\n"
        "bkpt #0xab\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d09b4_001a\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00141b74\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d09b4_001a:\n"
        "add sp, #0xc\n"
        "pop {pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D09D8_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d09d8(void)
{
    __asm__ volatile(
        "push {r1, r2, r3, r4, r5, r6, r7, lr}\n"
        "movs r4, r0\n"
        "movs r5, r1\n"
        "movs r6, r2\n"
        "movs r7, r3\n"
        "ands r0, r6, #3\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d09d8_0016\n"
        "ldr r0, [pc, #0x5c]\n"
        "b L_open_cfw_runtime_am064_d09d8_0052\n"
        "L_open_cfw_runtime_am064_d09d8_0016:\n"
        "subs.w r6, r6, #0x400000\n"
        "lsrs r6, r6, #2\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00073940\n"
        "bl .\n"
        "str r0, [sp, #4]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0007f3c6\n"
        "bl .\n"
        "str r7, [sp]\n"
        "movs r3, r6\n"
        "movs r2, r5\n"
        "movs r1, #1\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00141b7c\n"
        "bl .\n"
        "movs r4, r0\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0007f418\n"
        "bl .\n"
        "ldr r0, [sp, #4]\n"
        "msr primask, r0\n"
        "cmp r4, #0\n"
        "bne L_open_cfw_runtime_am064_d09d8_0048\n"
        "movs r4, #0\n"
        "b L_open_cfw_runtime_am064_d09d8_0050\n"
        "L_open_cfw_runtime_am064_d09d8_0048:\n"
        "orr r4, r4, #0x8000000\n"
        "orrs r4, r4, #0x100\n"
        "L_open_cfw_runtime_am064_d09d8_0050:\n"
        "movs r0, r4\n"
        "L_open_cfw_runtime_am064_d09d8_0052:\n"
        "pop {r1, r2, r3, r4, r5, r6, r7, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0A2C_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0a2c(void)
{
    __asm__ volatile(
        "push {r4, lr}\n"
        "ands r4, r2, #0xf\n"
        "cmp r4, #0\n"
        "bne L_open_cfw_runtime_am064_d0a2c_0010\n"
        "tst.w r3, #3\n"
        "beq L_open_cfw_runtime_am064_d0a2c_0014\n"
        "L_open_cfw_runtime_am064_d0a2c_0010:\n"
        "ldr r0, [pc, #8]\n"
        "b L_open_cfw_runtime_am064_d0a2c_0018\n"
        "L_open_cfw_runtime_am064_d0a2c_0014:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d09d8\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0a2c_0018:\n"
        "pop {r4, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0B36_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0b36(void)
{
    __asm__ volatile(
        "push {r7, lr}\n"
        "movs r1, r0\n"
        "ldr r2, [pc, #0x1a0]\n"
        "ldr r0, [r2, #0x14]\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d0b36_002a\n"
        "uxth r1, r1\n"
        "ldr r0, [r2, #0x14]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0004994e\n"
        "bl .\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d0b36_001c\n"
        "movs r0, #1\n"
        "b L_open_cfw_runtime_am064_d0b36_002c\n"
        "L_open_cfw_runtime_am064_d0b36_001c:\n"
        "cmn.w r0, #2\n"
        "bne L_open_cfw_runtime_am064_d0b36_0026\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d0b36_002c\n"
        "L_open_cfw_runtime_am064_d0b36_0026:\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d0b36_002c\n"
        "L_open_cfw_runtime_am064_d0b36_002a:\n"
        "movs r0, #0\n"
        "L_open_cfw_runtime_am064_d0b36_002c:\n"
        "pop {r1, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0B64_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0b64(void)
{
    __asm__ volatile(
        "push {r0, r1, r2, r3, r4, r5, r6, lr}\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000490cc\n"
        "bl .\n"
        "movs r4, r0\n"
        "movs r0, #0\n"
        "movs r5, #0\n"
        "movs r0, #0\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d0b36\n"
        "bl .\n"
        "movs r6, r0\n"
        "movs r0, r6\n"
        "uxtb r0, r0\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d0b64_007a\n"
        "L_open_cfw_runtime_am064_d0b64_001c:\n"
        "uxtb r6, r6\n"
        "cmp r6, #0\n"
        "bne L_open_cfw_runtime_am064_d0b64_007a\n"
        "movs r0, #0xa\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d0b36\n"
        "bl .\n"
        "movs r6, r0\n"
        "movs r0, r6\n"
        "uxtb r0, r0\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d0b64_0038\n"
        "movs r0, #0xa\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00049376\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0b64_0038:\n"
        "adds r5, r5, #1\n"
        "movs r0, r5\n"
        "uxtb r0, r0\n"
        "cmp r0, #0x14\n"
        "blt L_open_cfw_runtime_am064_d0b64_001c\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1e\n"
        "bpl L_open_cfw_runtime_am064_d0b64_005e\n"
        "ldr r0, [pc, #0x14c]\n"
        "str r0, [sp, #4]\n"
        "movs r0, #0xd3\n"
        "str r0, [sp]\n"
        "ldr r3, [pc, #0x148]\n"
        "ldr r2, [pc, #0x12c]\n"
        "ldr r1, [pc, #0x130]\n"
        "movs r0, #2\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d574\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0b64_005e:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1f\n"
        "bmi L_open_cfw_runtime_am064_d0b64_006e\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1d\n"
        "bpl L_open_cfw_runtime_am064_d0b64_007a\n"
        "L_open_cfw_runtime_am064_d0b64_006e:\n"
        "ldr r1, [pc, #0x130]\n"
        "movs r2, r1\n"
        "movs.w r0, #0x8000000\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003ce9e\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0b64_007a:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000490cc\n"
        "bl .\n"
        "subs r4, r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1e\n"
        "bpl L_open_cfw_runtime_am064_d0b64_00a4\n"
        "movs r0, r5\n"
        "uxtb r0, r0\n"
        "str r0, [sp, #0xc]\n"
        "str r4, [sp, #8]\n"
        "ldr r0, [pc, #0x110]\n"
        "str r0, [sp, #4]\n"
        "movs r0, #0xd9\n"
        "str r0, [sp]\n"
        "ldr r3, [pc, #0x100]\n"
        "ldr r2, [pc, #0xe8]\n"
        "ldr r1, [pc, #0xe8]\n"
        "movs r0, #4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d574\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0b64_00a4:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1f\n"
        "bmi L_open_cfw_runtime_am064_d0b64_00b4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1d\n"
        "bpl L_open_cfw_runtime_am064_d0b64_00c6\n"
        "L_open_cfw_runtime_am064_d0b64_00b4:\n"
        "ldr r2, [pc, #0xf0]\n"
        "uxtb r5, r5\n"
        "str r5, [sp]\n"
        "movs r3, r4\n"
        "movs r1, r2\n"
        "movs.w r0, #0x10800000\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003ce9e\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0b64_00c6:\n"
        "pop {r0, r1, r2, r3, r4, r5, r6, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D0C36_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d0c36(void)
{
    __asm__ volatile(
        "push {r3, r4, r5, lr}\n"
        "sub sp, #0x10\n"
        "ldr r5, [pc, #0xa0]\n"
        "ldr r0, [r5, #0x14]\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d0c36_00a2\n"
        "ldr r0, [r5, #0x14]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00049a0e\n"
        "bl .\n"
        "movs r4, r0\n"
        "cmp r4, #0\n"
        "bne L_open_cfw_runtime_am064_d0c36_0066\n"
        "ldr r0, [r5, #0x14]\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000499b8\n"
        "bl .\n"
        "movs r5, r0\n"
        "cmp r5, #0\n"
        "beq L_open_cfw_runtime_am064_d0c36_00a2\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1e\n"
        "bpl L_open_cfw_runtime_am064_d0c36_0044\n"
        "str r4, [sp, #0xc]\n"
        "str r5, [sp, #8]\n"
        "ldr r0, [pc, #0xa8]\n"
        "str r0, [sp, #4]\n"
        "movs r0, #0xf2\n"
        "str r0, [sp]\n"
        "ldr r3, [pc, #0xa4]\n"
        "ldr r2, [pc, #0x74]\n"
        "ldr r1, [pc, #0x78]\n"
        "movs r0, #2\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d574\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0c36_0044:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1f\n"
        "bmi L_open_cfw_runtime_am064_d0c36_0054\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1d\n"
        "bpl L_open_cfw_runtime_am064_d0c36_0064\n"
        "L_open_cfw_runtime_am064_d0c36_0054:\n"
        "ldr r1, [pc, #0x8c]\n"
        "str r4, [sp]\n"
        "movs r3, r5\n"
        "movs r2, r1\n"
        "movs.w r0, #0x8800000\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003ce9e\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0c36_0064:\n"
        "b L_open_cfw_runtime_am064_d0c36_00a2\n"
        "L_open_cfw_runtime_am064_d0c36_0066:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1e\n"
        "bpl L_open_cfw_runtime_am064_d0c36_0084\n"
        "str r4, [sp, #8]\n"
        "ldr r0, [pc, #0x74]\n"
        "str r0, [sp, #4]\n"
        "movs r0, #0xf5\n"
        "str r0, [sp]\n"
        "ldr r3, [pc, #0x64]\n"
        "ldr r2, [pc, #0x34]\n"
        "ldr r1, [pc, #0x38]\n"
        "movs r0, #4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d574\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0c36_0084:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1f\n"
        "bmi L_open_cfw_runtime_am064_d0c36_0094\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003d0ce\n"
        "bl .\n"
        "lsls r0, r0, #0x1d\n"
        "bpl L_open_cfw_runtime_am064_d0c36_00a2\n"
        "L_open_cfw_runtime_am064_d0c36_0094:\n"
        "ldr r2, [pc, #0x54]\n"
        "movs r3, r4\n"
        "movs r1, r2\n"
        "movs.w r0, #0x10400000\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003ce9e\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d0c36_00a2:\n"
        "add sp, #0x14\n"
        "pop {r4, r5, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D15E8_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d15e8(void)
{
    __asm__ volatile(
        "mov r3, r0\n"
        "mov r0, r1\n"
        "movs r2, #1\n"
        "ldr r1, [r0, #0xc]\n"
        "adds r1, r1, #1\n"
        "str r1, [r0, #0xc]\n"
        "movs r1, #0\n"
        "ldr r0, [r0]\n"
        "bx r3\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D15FA_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d15fa(void)
{
    __asm__ volatile(
        "mov r3, r0\n"
        "mov r0, r1\n"
        "ldr r1, [r0, #0xc]\n"
        "ldr r2, [r0, #0x10]\n"
        "adds r1, r1, #1\n"
        "subs r2, r2, #1\n"
        "cmp r2, #0\n"
        "str r2, [r0, #0x10]\n"
        "str r1, [r0, #0xc]\n"
        "bmi L_open_cfw_runtime_am064_d15fa_001c\n"
        "ldr r0, [r0]\n"
        "movs r2, #1\n"
        "movs r1, #0\n"
        "bx r3\n"
        "L_open_cfw_runtime_am064_d15fa_001c:\n"
        "mov.w r0, #-1\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D161C_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d161c(void)
{
    __asm__ volatile(
        "mov r3, r0\n"
        "mov r0, r1\n"
        "mov r1, r2\n"
        "ldr r2, [r0, #0xc]\n"
        "subs r2, r2, #1\n"
        "cmn.w r1, #1\n"
        "str r2, [r0, #0xc]\n"
        "beq L_open_cfw_runtime_am064_d161c_0018\n"
        "ldr r0, [r0]\n"
        "movs r2, #0\n"
        "bx r3\n"
        "L_open_cfw_runtime_am064_d161c_0018:\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D1638_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d1638(void)
{
    __asm__ volatile(
        ".reloc ., R_ARM_THM_JUMP24, open_cfw_runtime_am064_addr_003e64d4\n"
        "b .\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D2112_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d2112(void)
{
    __asm__ volatile(
        ".reloc ., R_ARM_THM_JUMP24, open_cfw_runtime_am064_addr_003b714a\n"
        "b .\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
        "nop\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D2158_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d2158(void)
{
    __asm__ volatile(
        "push.w {r4, r5, r6, r7, r8, sb, sl, fp, lr}\n"
        "mov sl, r2\n"
        "movs r7, #0\n"
        "cmp.w sl, #0\n"
        "sub sp, #0xc\n"
        "mov r8, r0\n"
        "mov r6, r1\n"
        "mov.w fp, #0\n"
        "bpl L_open_cfw_runtime_am064_d2158_0064\n"
        "ldr r0, [r6, #8]\n"
        "adds r1, r0, #1\n"
        "str r1, [r6, #8]\n"
        "mov r0, r1\n"
        "ldrb r1, [r0]\n"
        "cmp r1, #0x5e\n"
        "ittte eq\n"
        "addeq r0, r0, #1\n"
        "streq r0, [r6, #8]\n"
        "ldrbeq sb, [r0, #-0x1]!\n"
        "movne sb, r7\n"
        "ldr r5, [r6, #8]\n"
        "ldrb r0, [r5]\n"
        "cmp r0, #0x5d\n"
        "ite eq\n"
        "addeq r0, r5, #1\n"
        "movne r0, r5\n"
        "movs r1, #0x5d\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00081818\n"
        "bl .\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d2158_0194\n"
        "subs r1, r0, r5\n"
        "str r1, [sp]\n"
        "str r0, [r6, #8]\n"
        "ldr r0, [sp]\n"
        "cmp r0, #3\n"
        "blt L_open_cfw_runtime_am064_d2158_0064\n"
        "subs r2, r0, #2\n"
        "movs r1, #0x2d\n"
        "adds r0, r5, #1\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d40e0\n"
        "bl .\n"
        "cbz r0, L_open_cfw_runtime_am064_d2158_0064\n"
        "mov.w fp, #1\n"
        "L_open_cfw_runtime_am064_d2158_0064:\n"
        "ldr r0, [r6, #0x14]\n"
        "cmp r0, #0\n"
        "bgt L_open_cfw_runtime_am064_d2158_0076\n"
        "cmp.w sl, #0\n"
        "ite ne\n"
        "mvnne r0, #0x80000000\n"
        "moveq r0, #1\n"
        "L_open_cfw_runtime_am064_d2158_0076:\n"
        "str r0, [r6, #0x10]\n"
        "ldrb r0, [r6, #0x1c]\n"
        "cmp r0, #0\n"
        "itttt eq\n"
        "ldreq r0, [r6, #4]\n"
        "ldreq r4, [r0], #4\n"
        "streq r0, [r6, #4]\n"
        "cmpeq r4, #0\n"
        "bne L_open_cfw_runtime_am064_d2158_009c\n"
        "mov.w r4, #-1\n"
        "ldr r0, [pc, #8]\n"
        "add r0, pc\n"
        "adds r0, r0, #4\n"
        "b L_open_cfw_runtime_am064_d2158_00ba\n"
        "nop\n"
        "cbz r4, L_open_cfw_runtime_am064_d2158_00c8\n"
        "movs r0, r5\n"
        "L_open_cfw_runtime_am064_d2158_009c:\n"
        "ldrb r0, [r6, #0x1c]\n"
        "cbnz r0, L_open_cfw_runtime_am064_d2158_00cc\n"
        "ldrb r0, [r6, #0x1f]\n"
        "cbz r0, L_open_cfw_runtime_am064_d2158_00cc\n"
        "ldr r1, [r6, #4]\n"
        "ldr r0, [r1], #4\n"
        "str r1, [r6, #4]\n"
        "cmp.w r0, #-0x80000000\n"
        "blo L_open_cfw_runtime_am064_d2158_00c2\n"
        "mov.w r4, #-1\n"
        "adr r0, #0x110\n"
        "L_open_cfw_runtime_am064_d2158_00ba:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d40a0\n"
        "bl .\n"
        "subs r0, r4, r0\n"
        "b L_open_cfw_runtime_am064_d2158_019e\n"
        "L_open_cfw_runtime_am064_d2158_00c2:\n"
        "ldr r1, [r6, #0x18]\n"
        "cmp r0, r1\n"
        "it hi\n"
        "L_open_cfw_runtime_am064_d2158_00c8:\n"
        "movhi r0, r1\n"
        "str r0, [r6, #0x18]\n"
        "L_open_cfw_runtime_am064_d2158_00cc:\n"
        "str.w sb, [sp, #4]\n"
        "str.w fp, [sp, #8]\n"
        "ldr.w sb, [sp]\n"
        "b L_open_cfw_runtime_am064_d2158_00dc\n"
        "L_open_cfw_runtime_am064_d2158_00da:\n"
        "movs r7, #2\n"
        "L_open_cfw_runtime_am064_d2158_00dc:\n"
        "ldr r0, [r6, #0xc]\n"
        "ldr r1, [r6, #0x10]\n"
        "adds r0, r0, #1\n"
        "subs r1, r1, #1\n"
        "cmp r1, #0\n"
        "str r1, [r6, #0x10]\n"
        "str r0, [r6, #0xc]\n"
        "bpl L_open_cfw_runtime_am064_d2158_00f2\n"
        "mov.w fp, #-1\n"
        "b L_open_cfw_runtime_am064_d2158_0164\n"
        "L_open_cfw_runtime_am064_d2158_00f2:\n"
        "ldr r0, [r6]\n"
        "movs r2, #1\n"
        "movs r1, #0\n"
        "blx r8\n"
        "mov fp, r0\n"
        "cmn.w fp, #1\n"
        "beq L_open_cfw_runtime_am064_d2158_0164\n"
        "cmp.w sl, #0\n"
        "bgt L_open_cfw_runtime_am064_d2158_0122\n"
        "bpl L_open_cfw_runtime_am064_d2158_0148\n"
        "ldr r0, [sp, #8]\n"
        "cmp r0, #0\n"
        "ldr r0, [sp, #4]\n"
        "beq L_open_cfw_runtime_am064_d2158_0128\n"
        "cmp r0, #0\n"
        "mov r2, sb\n"
        "mov r1, fp\n"
        "mov r0, r5\n"
        "beq L_open_cfw_runtime_am064_d2158_0142\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d2112\n"
        "bl .\n"
        "b L_open_cfw_runtime_am064_d2158_0136\n"
        "L_open_cfw_runtime_am064_d2158_0122:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d58ae\n"
        "bl .\n"
        "b L_open_cfw_runtime_am064_d2158_0136\n"
        "L_open_cfw_runtime_am064_d2158_0128:\n"
        "cmp r0, #0\n"
        "mov r2, sb\n"
        "mov r1, fp\n"
        "mov r0, r5\n"
        "beq L_open_cfw_runtime_am064_d2158_013a\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d40e0\n"
        "bl .\n"
        "L_open_cfw_runtime_am064_d2158_0136:\n"
        "cbz r0, L_open_cfw_runtime_am064_d2158_0148\n"
        "b L_open_cfw_runtime_am064_d2158_0164\n"
        "L_open_cfw_runtime_am064_d2158_013a:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000d40e0\n"
        "bl .\n"
        "cbz r0, L_open_cfw_runtime_am064_d2158_0164\n"
        "b L_open_cfw_runtime_am064_d2158_0148\n"
        "L_open_cfw_runtime_am064_d2158_0142:\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d2112\n"
        "bl .\n"
        "cbz r0, L_open_cfw_runtime_am064_d2158_0164\n"
        "L_open_cfw_runtime_am064_d2158_0148:\n"
        "ldrb r0, [r6, #0x1c]\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d2158_00da\n"
        "ldr r0, [r6, #0x18]\n"
        "cbz r0, L_open_cfw_runtime_am064_d2158_0162\n"
        "strb fp, [r4], #1\n"
        "movs r1, #1\n"
        "ldr r0, [r6, #0x18]\n"
        "strb r1, [r6, #0x1e]\n"
        "subs r0, r0, #1\n"
        "str r0, [r6, #0x18]\n"
        "b L_open_cfw_runtime_am064_d2158_00da\n"
        "L_open_cfw_runtime_am064_d2158_0162:\n"
        "movs r7, #1\n"
        "L_open_cfw_runtime_am064_d2158_0164:\n"
        "mov r0, r8\n"
        "mov r2, fp\n"
        "mov r1, r6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_d161c\n"
        "bl .\n"
        "cmp.w sl, #0\n"
        "beq L_open_cfw_runtime_am064_d2158_0178\n"
        "cmp r7, #2\n"
        "beq L_open_cfw_runtime_am064_d2158_018c\n"
        "L_open_cfw_runtime_am064_d2158_0178:\n"
        "cmp r7, #2\n"
        "beq L_open_cfw_runtime_am064_d2158_019c\n"
        "lsls r0, r7, #0x1f\n"
        "bmi L_open_cfw_runtime_am064_d2158_0186\n"
        "cmn.w fp, #1\n"
        "bne L_open_cfw_runtime_am064_d2158_0194\n"
        "L_open_cfw_runtime_am064_d2158_0186:\n"
        "mov.w r0, #-1\n"
        "b L_open_cfw_runtime_am064_d2158_019e\n"
        "L_open_cfw_runtime_am064_d2158_018c:\n"
        "ldrb r0, [r6, #0x1c]\n"
        "cbnz r0, L_open_cfw_runtime_am064_d2158_019c\n"
        "ldr r0, [r6, #0x18]\n"
        "cbnz r0, L_open_cfw_runtime_am064_d2158_0198\n"
        "L_open_cfw_runtime_am064_d2158_0194:\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d2158_019e\n"
        "L_open_cfw_runtime_am064_d2158_0198:\n"
        "movs r0, #0\n"
        "strb r0, [r4]\n"
        "L_open_cfw_runtime_am064_d2158_019c:\n"
        "movs r0, #1\n"
        "L_open_cfw_runtime_am064_d2158_019e:\n"
        "add sp, #0xc\n"
        "pop.w {r4, r5, r6, r7, r8, sb, sl, fp, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D293C_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d293c(void)
{
    __asm__ volatile(
        "push {r4, lr}\n"
        "movs r4, r0\n"
        "movs r2, #6\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_00039be4\n"
        "bl .\n"
        "pop {r4, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D294A_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d294a(void)
{
    __asm__ volatile(
        "push {r7, lr}\n"
        "movs r2, #6\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000751c8\n"
        "bl .\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d294a_0010\n"
        "movs r0, #1\n"
        "b L_open_cfw_runtime_am064_d294a_0012\n"
        "L_open_cfw_runtime_am064_d294a_0010:\n"
        "movs r0, #0\n"
        "L_open_cfw_runtime_am064_d294a_0012:\n"
        "uxtb r0, r0\n"
        "pop {r1, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D2960_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d2960(void)
{
    __asm__ volatile(
        "push {r3, r4, r5, lr}\n"
        "movs r4, r0\n"
        "movs r1, #6\n"
        "movs r2, #0\n"
        "movs r5, r4\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003c0e4\n"
        "bl .\n"
        "adds r0, r4, #6\n"
        "pop {r1, r4, r5, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D2974_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d2974(void)
{
    __asm__ volatile(
        "push {r1, r2, r3, r4, r5, lr}\n"
        "movs r4, r0\n"
        "movs r1, #6\n"
        "movs r2, #0\n"
        "mov r5, sp\n"
        "movs r0, r5\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_0003c0e4\n"
        "bl .\n"
        "movs r2, #6\n"
        "mov r1, sp\n"
        "movs r0, r4\n"
        ".reloc ., R_ARM_THM_CALL, open_cfw_runtime_am064_addr_000751c8\n"
        "bl .\n"
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d2974_0022\n"
        "movs r0, #1\n"
        "b L_open_cfw_runtime_am064_d2974_0024\n"
        "L_open_cfw_runtime_am064_d2974_0022:\n"
        "movs r0, #0\n"
        "L_open_cfw_runtime_am064_d2974_0024:\n"
        "uxtb r0, r0\n"
        "pop {r1, r2, r3, r4, r5, pc}\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D34C4_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d34c4(void)
{
    __asm__ volatile(
        "push {r4, r5}\n"
        "movs r3, r0\n"
        "cmp r2, #0\n"
        "bne L_open_cfw_runtime_am064_d34c4_000e\n"
        "movs.w r0, #-1\n"
        "b L_open_cfw_runtime_am064_d34c4_0012\n"
        "L_open_cfw_runtime_am064_d34c4_000e:\n"
        "ldr r0, [r2]\n"
        "mvns r0, r0\n"
        "L_open_cfw_runtime_am064_d34c4_0012:\n"
        "movs r4, #0\n"
        "b L_open_cfw_runtime_am064_d34c4_002a\n"
        "L_open_cfw_runtime_am064_d34c4_0016:\n"
        "ldr r2, [pc, #0x50]\n"
        "ldrb r5, [r3, r4]\n"
        "eors r5, r0\n"
        "and r5, r5, #0xff\n"
        "ldr.w r2, [r2, r5, lsl #2]\n"
        "eors.w r0, r2, r0, lsr #8\n"
        "adds r4, r4, #1\n"
        "L_open_cfw_runtime_am064_d34c4_002a:\n"
        "cmp r4, r1\n"
        "blo L_open_cfw_runtime_am064_d34c4_0016\n"
        "mvns r0, r0\n"
        "pop {r4, r5}\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D34F8_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d34f8(void)
{
    __asm__ volatile(
        "push {r4, r5}\n"
        "movs r3, r0\n"
        "cmp r2, #0\n"
        "bne L_open_cfw_runtime_am064_d34f8_000e\n"
        "movs.w r0, #-1\n"
        "b L_open_cfw_runtime_am064_d34f8_0012\n"
        "L_open_cfw_runtime_am064_d34f8_000e:\n"
        "ldr r0, [r2]\n"
        "mvns r0, r0\n"
        "L_open_cfw_runtime_am064_d34f8_0012:\n"
        "movs r4, #0\n"
        "b L_open_cfw_runtime_am064_d34f8_002a\n"
        "L_open_cfw_runtime_am064_d34f8_0016:\n"
        "ldr r2, [pc, #0x20]\n"
        "ldrb r5, [r3, r4]\n"
        "eors r5, r0\n"
        "and r5, r5, #0xff\n"
        "ldr.w r2, [r2, r5, lsl #2]\n"
        "eors.w r0, r2, r0, lsr #8\n"
        "adds r4, r4, #1\n"
        "L_open_cfw_runtime_am064_d34f8_002a:\n"
        "cmp r4, r1\n"
        "blo L_open_cfw_runtime_am064_d34f8_0016\n"
        "mvns r0, r0\n"
        "pop {r4, r5}\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D3534_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d3534(void)
{
    __asm__ volatile(
        "uxtb r0, r0\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d3534_000c\n"
        "cmp r0, #1\n"
        "beq L_open_cfw_runtime_am064_d3534_0014\n"
        "b L_open_cfw_runtime_am064_d3534_001c\n"
        "L_open_cfw_runtime_am064_d3534_000c:\n"
        "movs r0, #0xd4\n"
        "ldr r1, [pc, #0xbc]\n"
        "str r0, [r1]\n"
        "L_open_cfw_runtime_am064_d3534_0012:\n"
        "b L_open_cfw_runtime_am064_d3534_0012\n"
        "L_open_cfw_runtime_am064_d3534_0014:\n"
        "movs r0, #0x1b\n"
        "ldr r1, [pc, #0xb8]\n"
        "str r0, [r1]\n"
        "L_open_cfw_runtime_am064_d3534_001a:\n"
        "b L_open_cfw_runtime_am064_d3534_001a\n"
        "L_open_cfw_runtime_am064_d3534_001c:\n"
        "movs r0, #6\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D3554_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d3554(void)
{
    __asm__ volatile(
        "cmp r0, #0\n"
        "bne L_open_cfw_runtime_am064_d3554_0008\n"
        "movs r0, #6\n"
        "b L_open_cfw_runtime_am064_d3554_00a8\n"
        "L_open_cfw_runtime_am064_d3554_0008:\n"
        "ldr r2, [pc, #0xa8]\n"
        "ldr r1, [r2]\n"
        "cmp r1, #0\n"
        "bne L_open_cfw_runtime_am064_d3554_0016\n"
        "ldr r1, [pc, #0xa4]\n"
        "ldr r1, [r1]\n"
        "str r1, [r2]\n"
        "L_open_cfw_runtime_am064_d3554_0016:\n"
        "ldr r1, [r2]\n"
        "lsls r1, r1, #0x13\n"
        "lsrs r1, r1, #0x13\n"
        "str r1, [r2]\n"
        "ldr r1, [r2]\n"
        "strh r1, [r0]\n"
        "ldrb r1, [r2]\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #2]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #1\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #3]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #2\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #4]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #3\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #5]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #4\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #6]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #5\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #7]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #6\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #8]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #7\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #9]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #8\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #0xa]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #9\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #0xb]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #0xa\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #0xc]\n"
        "movs r1, #0\n"
        "strb r1, [r0, #0xd]\n"
        "ldr r1, [r2]\n"
        "lsrs r1, r1, #0xc\n"
        "ands r1, r1, #1\n"
        "strb r1, [r0, #0xe]\n"
        "ldr r0, [r2]\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d3554_00a6\n"
        "movs r0, #0\n"
        "b L_open_cfw_runtime_am064_d3554_00a8\n"
        "L_open_cfw_runtime_am064_d3554_00a6:\n"
        "movs r0, #1\n"
        "L_open_cfw_runtime_am064_d3554_00a8:\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D3610_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d3610(void)
{
    __asm__ volatile(
        "ldr r3, [pc, #0xc]\n"
        "str r3, [r0]\n"
        "ldr r0, [pc, #0xc]\n"
        "str r0, [r1]\n"
        "mov.w r0, #0x1000\n"
        "str r0, [r2]\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D391E_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d391e(void)
{
    __asm__ volatile(
        "uxtb r0, r0\n"
        "cmp r0, #0\n"
        "beq L_open_cfw_runtime_am064_d391e_000a\n"
        "movs r0, #1\n"
        "b L_open_cfw_runtime_am064_d391e_000c\n"
        "L_open_cfw_runtime_am064_d391e_000a:\n"
        "movs r0, #0\n"
        "L_open_cfw_runtime_am064_d391e_000c:\n"
        "ldr r1, [pc, #0xdc]\n"
        "ldr r2, [r1]\n"
        "bfi r2, r0, #0, #1\n"
        "str r2, [r1]\n"
        "movs r0, #0\n"
        "bx lr\n"
    );
}
#endif

#if defined(OPEN_CFW_AM064_D3938_ONLY)
__attribute__((used, naked))
void open_cfw_runtime_am064_d3938(void)
{
    __asm__ volatile(
        "orrs r0, r0, #1\n"
        "ldr r1, [pc, #0xcc]\n"
        "str r0, [r1]\n"
        "movs r0, #0\n"
        "bx lr\n"
    );
}
#endif
