from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x484ba4;end=0x484c38
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21467/fresh';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Flag-selected object parameter and signed scaled dimensions\n\nPartial/unaccepted. Exact 148 instruction bytes 484BA4..484C38, continuing 32-byte frame at 484A98 with object R4. Fresh byte+36 bit0 set: call 48834C(18,2,live R2/R3); clear: call 488290(R0=18,R1 live from previous helper,R2/R3 live). Move helper result to R1 and call 4D48AA(object+76,result,live R2/R3). Set R5=32767; call 4D4A6E(object+76,32767,live R2/R3).\n\nCompute q7 = signed_divide(signed32(wrap32(7*word[object+44]+80)),160), truncating toward zero. If signed q7<2 choose R1=1; otherwise freshly reload word+44 and repeat wrap multiply/add/signed division into R1. Call 484A26(object+76,R1,live R2/R3). That wrapper restores its entry R3 into R0; its return is ignored here.\n\nCompute q5 analogously with multiplier5 and same +80/divisor160. Signed q5<2 chooses1; otherwise freshly reload word+44 and recompute R1. Call 4D481A(object+76,R1,live R2/R3). Then call 4D48C4(object+76,102,live R2/R3). These clamps are branch decisions with independently repeated reads, not a single cached max expression; preserve 32-bit wrapping before signed division. Frame remains open and continuation starts484C38. Helper contracts unresolved. No C, freeze, whole coverage or equality claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
