from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47ed76;end=0x47ee26
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21019/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Linked-node mask matching with deferred aggregate clear\n\nPartial/unaccepted;176instructionbytes47ED76..47EE26,twoentries.\nED76 PUSH R4,R5,R6,R7,R8,LR24;R7=entryR1,R5=0,R4=entryR0,R1=0. NullobjectorentrymaskFF000000nonzero→distinct5FA0A4/write0toFFFFFFFF/selfloopfatalbranches. Maskzeroallowed. R8=object+4,R6=object+12sentinel;454D7C(liveargs). R2=freshwordobject16head;freshwordobject0ORentrymaskstoredobject0. LoopwhileR2!=sentinel;no nullnodecheck.\nEachnodeR7=freshword[node+4]next;R1=freshword[node]fullflags/mask;R0=0;R3=R1&FF000000;R1&=00FFFFFF. Flagsbit26set→freshobjectword&R1equalR1→match1;otherwise0 (zeromaskmatches). Bit26clear→freshobjectwordTSTR1nonzero→match1;otherwise0. Match:flagsbit24set→R5|=R1;freshobjectwordOR02000000→R1;45547C(node,R1,liveR2,R3). RegardlessmatchR2=savednextR7,repeat. Helperscanmutatelinksafterpreloadednext;do notre-readnextorsimplifycurrentobjectword.\nAfterlistendfreshobjectword&~R5storedobject0;454DCC(liveargs);independentlyfreshobjectwordreturnedfullR0. POP R4/R5/R6/R7/R8/PC24 restoreframe. Nodeflagsandmaskremainseparate,aggregateclearafterallmatches. No loopbound/cyclehandlingrecovered.\nEE1E PUSH R7,LR8;47ED76(liveargs);POP R0,PC returnsownsavedentryR7,discardinginnerobjectwordreturn. No C/freeze/completenessclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
