from pathlib import Path
import json,hashlib,subprocess,shutil
P=Path('g2/analysis/bootloader-completion-2026-10-06/inventory-worker/startup-initialize');OLDN=P/'logger-native-integrated';N=P/'update-log-literals-integrated';N.mkdir(exist_ok=True);old=json.loads((OLDN/'current-candidate.json').read_text());OLD=Path(old['directory']);T=Path('/tmp/opencfw-update-log-literals-integrated');T.mkdir(exist_ok=True);src=Path('g2/components/bootloader/update_core/log_literals/log_literals.c');h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();flags=['--target=arm-none-eabi','-mcpu=cortex-m33','-mthumb','-mfloat-abi=softfp','-O1','-ffreestanding','-fno-builtin'];obj=T/'update_log_literals.o';subprocess.run(['clang',*flags,'-c',str(src),'-o',str(obj)],check=True);m=json.loads((OLD/'input-hashes.json').read_text());objs=[OLD/r['path'] for r in m['inputs']];assert all(h(OLD/r['path'])==r['sha256'] for r in m['inputs']);objs.append(obj);s=(OLD/'source/module.ld').read_text();literal=json.loads(Path('g2/analysis/bootloader-completion-2026-10-06/inventory-worker/update-log-literals/literal-manifest.json').read_text())['literals'];ph='';sections=''
for row in literal:
 a=row['address'];name=f'update_log_{a:x}';ph+=f'  {name} PT_LOAD FLAGS(4);\n';sections+=f'  . = 0x{a:x};\n  {row["section"]} : {{ KEEP(*({row["section"]})) }} :{name}\n'
s=s.replace('PHDRS\n{','PHDRS\n{'+ph) if 'PHDRS\n{' in s else s.replace('PHDRS {','PHDRS {\n'+ph)
# Existing script has an explicit SECTIONS closing brace before linker aliases.
pos=s.index('\n}\n',s.index('SECTIONS'));s=s[:pos]+ '\n'+sections+s[pos:];ld=T/'module.ld';ld.write_text(s);elf=T/'candidate.elf';r=subprocess.run(['/opt/homebrew/bin/arm-none-eabi-ld','--gc-sections','-T',str(ld),'-o',str(elf),*[str(p) for p in objs]],capture_output=True,text=True);(N/'link.log').write_text(r.stderr);assert r.returncode==0,r.stderr;sha=h(elf);B=Path('g2/build/bootloader-completion/update-log-literals-integrated')/sha;B.mkdir(parents=True,exist_ok=True);shutil.copy2(elf,B/'candidate.elf');shutil.copytree(OLD/'source',B/'source',dirs_exist_ok=True);shutil.copy2(ld,B/'source/module.ld');shutil.copy2(src,B/'source/update_log_literals.c')
for row in m['inputs']:
 p=B/row['path'];p.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(OLD/row['path'],p)
p=B/'inputs/240/update_log_literals.o';p.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(obj,p);m['inputs'].append({'path':str(p.relative_to(B)),'original':str(obj),'sha256':h(obj)});m['elf_sha256']=sha;m['linked_objects']=241;(B/'input-hashes.json').write_text(json.dumps(m,indent=2)+'\n');(N/'current-candidate.json').write_text(json.dumps({'directory':str(B),'sha256':sha,'objects':241,'previous_sha256':old['sha256'],'predecessor_acceptance_pending_at_build':not (OLDN/'completion-receipt.json').exists()},indent=2)+'\n');(N/'build-inputs.json').write_text(json.dumps({'flags':flags,'source':str(src),'source_sha256':h(src),'object_sha256':h(obj),'unchanged_predecessor_objects':240},indent=2)+'\n');(B/'validation/regressions').mkdir(parents=True,exist_ok=True)
for p in OLDN.glob('*.py'):
 if p.name in ['build.py','verify_task_logger.py','verify_native_elog.py','verify_time_producer.py']:continue
 z=p.read_text().replace(old['directory'],str(B)).replace(str(OLDN),str(N)).replace("'logger-native-integrated'","'update-log-literals-integrated'").replace(old['sha256'],sha);(N/p.name).write_text(z)
for f in ['native-selector-bindings.json','initialized_data.c']:shutil.copy2(OLDN/f,N/f)
shutil.copy2(ld,N/'module.ld');(N/'build.py').write_bytes(Path('/tmp/opencfw-build-literals-integrated.py').read_bytes());print('built241',sha)
