from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47e7b0;end=0x47e83a
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-20991/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Signed-mode dispatch structure and repeated callback loop\n\nPartial/unaccepted;138instructionbytes47E7B0..47E83A,twoentries.\nE7B0 PUSH R0,R1,R2,R3,R4,R5,R6,LR32;R4=entryR0,R5=entryR3,R0=0. FullR4zero→5FA0A4(liveargs),ifreturnsstoreword0toFFFFFFFFthenE7C8selfloopifstorecompletes. Nonzero→R6=literalEB6Cpointer;freshwordintoR3zero→returnR0=0. Nonzero→SP0=entryR1,SP4=entryR2,SP8=entryR0;SP12retainssavedentryR3subjectcallee writes. SIGNEDentryR1>=6→441952(freshword[R6],SP,entryR3,0). Signed<6→4558A4(liveargs)fullresult==2→4417EE(freshword[R6],SP,freshSP32callerfiftharg,0);otherwise4417EE(freshword[R6],SP,0,0). ReturnfullselectedcalleeR0;SP+=16discardsfourlocalsandsavedentryargs;POP R4,R5,R6,PC16. Signednegativevaluesfollow<6path,noLOW8modeconversion.\nE812 PUSH R4,R5,R6,LR16;R4=entryR0,R5=entryR1,R6=entryR2. Initiallyandaftereachcallback47E93C(R4,(freshobjectword24+R5)modulo2^32,R6,R5). Fullzero exitsreturn0. Fullnonzero→independentlyfreshobjectword24 addedR5modulo2^32;R0=R4,R1=freshobjectword32;BLX R1 indirectcallbackwithliveR2/R3;callbackreturnignored. Thenrepeatfreshword24/readand47E93C. No nullcallback/objectcheck or terminationbound recovered. POP R4,R5,R6,PC restorespreservedregs. No C/freeze/completenessclaim;47E93C/externalhelpersstillunresolved.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
