from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x480ad4;end=0x480b66
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-mode-three-discarded-mask-snapshot-conditional-word-write-21544-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Mode three discarded masked snapshot and conditional word write\n\nPartial/unaccepted;146 instruction bytes480AD4..480B66. Dispatch mode3 of4809C4;16-byte frame;R4entryR1 optional pointer. R1=pointer480EB4;freshword→SP0;reload intoR2 ANDliteral480EB8→SP0. Crucially R2 is then overwritten by fresh byte from pointer480EBC masked63: the masked original word is discarded, not ORed into final configuration. Freshword from pointer480EC0 shifted6mod2^32 AND960 ORR2; ORliteral480EC4 (value, not dereferenced)→SP0;reload storeword[R1]. Initial masked read/scratch stores remain observable despite discarded result.\n\nR1=pointer480EC8;freshword→SP0;reload clear0x22→SP0;reload OR0x22→SP0;reload storeword[R1]. Separate freshword OR1 store; then another freshword→SP0. If R4nonnull and freshbyte[R4]==1: reloadSP0 ANDliteral480ED0→SP0;reload OR256→SP0. Otherwise reloadSP0 clear0x28→SP0;reload OR8→SP0. Both arms reloadSP0 and storeword[R1], without late source reread. Branch480A18 returnsR0=0 thenPOP R1,R4,R5,PC releases16;R1 finalscratchSP0,not entryR3. Preserve read/store order and potential pointer/stack aliasing. No helper calls or validation failure return. No C/freeze/fullcoverage/equality claim; remaining dispatch modes unresolved.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
