from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x46931c;end=0x469388
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-saved-input-byte-change-child-result-diagnostics-and-live-return-19492-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Comparison and return 0x46931C..0x469388\n\nPartial/unaccepted;108 instruction bytes. Inherit32-byte frame, R5 earlier bool, SP16 original R0 word. Load unsigned byteSP16 toR0; truncateR5 in place low8; compareR5 toR0. Equalbranches sharedreturn469384 withR0 originalinputbyte. UnequalsetsSP0=4, R3=0, R2=1, R1=SP16, R0=266; call464F76. Thus child receives pointer tosavedinputword plus stackextra4; do not infer immutable input or childcontract. SaveFULLchildresultR4; FULLzero branchesreturn withR0=0.\n\nNonzero child: fresh43D0CE bit1 enables SP8=R4, SP4=literal469B60, SP0=126, R3=literal469B4C, R2=literal469B38, R1=literal469B3C, R0=1 ->43D574. Separatefreshbit0 orconditional thirdfreshbit2 enables R1=literal469B64, R3=R4 fullsavedchildresult, R2=R1, R0=0x04400000 ->43CE9E.\n\nShared469384 ADD SP20 skips16 localbytes AND savedoriginalR0word, thenPOP R4/R5/PC consumesremaining12, restoring32-byteframe. R0 remains live; no blanket bool/zero return: earlier globalguard diagnosticpath also reachesreturn, equality path returnsinputbyte, childzero path returns0, otherpaths retain mask-shift orlastchildresult. Savedinputword may be writable via464F76. No C, acceptance, runtimeorwholecorpusclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
