/* SPDX-License-Identifier: Apache-2.0 */
#include "runtime_cordio_dm_dev_priv.h"
struct open_cfw_cordio_dm_dev_priv_control open_cfw_cordio_dm_dev_priv_control;
uint8_t open_cfw_cordio_dm_dev_priv_local_address[6],open_cfw_cordio_dm_dev_priv_handler_id,open_cfw_cordio_dm_dev_priv_ll_enabled;
open_cfw_cordio_dm_dev_priv_event_callback_t open_cfw_cordio_dm_dev_priv_callback;
open_cfw_cordio_dm_dev_priv_adv_address_callback_t open_cfw_cordio_dm_dev_priv_adv_callback;
static uint8_t open_cfw_dm_dev_priv_interface_installed;
static void z(void*p,size_t n){uint8_t*q=p;while(n--)*q++=0;}static void cp(uint8_t*d,const uint8_t*s,size_t n){while(n--)*d++=*s++;}
uint8_t open_cfw_cordio_dm_device_privacy_advertising(uint8_t nonconnectable){unsigned i;if(open_cfw_cordio_dm_dev_priv_control.advertising)return 1;for(i=0;i<2;i++){struct open_cfw_cordio_dm_dev_priv_adv*a=&open_cfw_cordio_dm_dev_priv_control.extended[i];if(a->configured&&a->advertising&&(a->connectable||nonconnectable))return 1;}return 0;}
void open_cfw_cordio_dm_device_privacy_timer_start(void){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;if(!open_cfw_cordio_dm_dev_priv_ll_enabled&&(open_cfw_cordio_dm_device_privacy_advertising(1)||c->scanning||c->connected)){c->timer_started=1;open_cfw_cordio_wsf_timer_start_seconds(c,c->change_interval);}}
void open_cfw_cordio_dm_device_privacy_address_calculate(void){uint8_t b[16];open_cfw_cordio_security_random(b,3);b[2]=(uint8_t)((b[2]&0x3fU)|0x40U);z(b+3,13);open_cfw_cordio_security_aes(open_cfw_cordio_dm_security_local_irk(),b,open_cfw_cordio_dm_dev_priv_handler_id,0,3);cp(open_cfw_cordio_dm_dev_priv_control.prand,b,3);}
void open_cfw_cordio_dm_device_privacy_set_rpa(uint8_t*a){unsigned i;if(!a)return;cp(open_cfw_cordio_dm_dev_priv_local_address,a,6);open_cfw_cordio_hci_set_random_address(open_cfw_cordio_dm_dev_priv_local_address);if(open_cfw_cordio_dm_dev_priv_adv_callback)for(i=0;i<2;i++)if(open_cfw_cordio_dm_dev_priv_control.extended[i].configured)open_cfw_cordio_dm_dev_priv_adv_callback((uint8_t)i,open_cfw_cordio_dm_dev_priv_local_address);}
void open_cfw_cordio_dm_device_privacy_set_pending_rpa(void){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;unsigned i;uint8_t any=0;for(i=0;i<6;i++)any|=c->pending_address[i];if(!open_cfw_cordio_dm_device_privacy_advertising(0)&&!c->scanning&&!c->connecting&&any){open_cfw_cordio_dm_device_privacy_set_rpa(c->pending_address);z(c->pending_address,6);}}
void open_cfw_cordio_dm_device_privacy_action_start(struct open_cfw_cordio_dm_dev_priv_message*m){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;if(!m)return;c->use_resolvable=1;c->change_interval=m->change_interval;open_cfw_cordio_dm_advertising_set_address_type(1);open_cfw_cordio_dm_scanning_set_address_type(1);open_cfw_cordio_dm_connection_master_set_address_type(1);if(c->change_interval){open_cfw_cordio_dm_device_privacy_timer_start();if(open_cfw_cordio_hci_ll_privacy_supported())open_cfw_cordio_dm_privacy_set_timeout(c->change_interval);}if(!c->address_initialized)open_cfw_cordio_dm_device_privacy_address_calculate();}
void open_cfw_cordio_dm_device_privacy_action_stop(struct open_cfw_cordio_dm_dev_priv_message*m){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;(void)m;c->timer_started=0;open_cfw_cordio_wsf_timer_stop(c);c->use_resolvable=0;z(c->pending_address,6);open_cfw_cordio_dm_advertising_set_address_type(0);open_cfw_cordio_dm_scanning_set_address_type(0);open_cfw_cordio_dm_connection_master_set_address_type(0);if(open_cfw_cordio_hci_ll_privacy_supported())open_cfw_cordio_dm_privacy_clear_resolving_list();}
void open_cfw_cordio_dm_device_privacy_action_timeout(struct open_cfw_cordio_dm_dev_priv_message*m){(void)m;if(open_cfw_cordio_dm_dev_priv_control.use_resolvable){open_cfw_cordio_dm_dev_priv_control.timer_started=0;open_cfw_cordio_dm_device_privacy_timer_start();open_cfw_cordio_dm_device_privacy_address_calculate();}}
void open_cfw_cordio_dm_device_privacy_action_aes_complete(struct open_cfw_cordio_dm_dev_priv_message*m){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;uint8_t a[6];if(!m||!c->use_resolvable)return;cp(a,m->ciphertext,3);cp(a+3,c->prand,3);a[5]=(uint8_t)((a[5]&0x3fU)|0x40U);if(!open_cfw_cordio_dm_device_privacy_advertising(0)&&!c->scanning&&!c->connecting)open_cfw_cordio_dm_device_privacy_set_rpa(a);else cp(c->pending_address,a,6);}
void open_cfw_cordio_dm_device_privacy_action_rpa_start(struct open_cfw_cordio_dm_dev_priv_message*m){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;if(!m)return;switch(m->parameter){case OPEN_CFW_DEV_PRIV_ADV_START:c->advertising=1;break;case OPEN_CFW_DEV_PRIV_ADV_SET_START:if(m->advertising_handle<2)c->extended[m->advertising_handle].advertising=1;break;case OPEN_CFW_DEV_PRIV_SCAN_START:case OPEN_CFW_DEV_PRIV_EXT_SCAN_START:c->scanning=1;break;case OPEN_CFW_DEV_PRIV_CONN_OPEN:c->connected=1;break;default:break;}if(c->use_resolvable&&!c->timer_started)open_cfw_cordio_dm_device_privacy_timer_start();}
void open_cfw_cordio_dm_device_privacy_action_rpa_stop(struct open_cfw_cordio_dm_dev_priv_message*m){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;if(!m)return;switch(m->parameter){case OPEN_CFW_DEV_PRIV_ADV_STOP:c->advertising=0;open_cfw_cordio_dm_device_privacy_set_pending_rpa();break;case OPEN_CFW_DEV_PRIV_ADV_SET_STOP:if(m->advertising_handle<2)c->extended[m->advertising_handle].advertising=0;open_cfw_cordio_dm_device_privacy_set_pending_rpa();break;case OPEN_CFW_DEV_PRIV_SCAN_STOP:case OPEN_CFW_DEV_PRIV_EXT_SCAN_STOP:c->scanning=0;open_cfw_cordio_dm_device_privacy_set_pending_rpa();break;case OPEN_CFW_DEV_PRIV_CONN_CLOSE:c->connected=0;break;default:if(c->timer_started){c->timer_started=0;open_cfw_cordio_wsf_timer_stop(c);}break;}}
void open_cfw_cordio_dm_device_privacy_action_control(struct open_cfw_cordio_dm_dev_priv_message*m){struct open_cfw_cordio_dm_dev_priv_control*c=&open_cfw_cordio_dm_dev_priv_control;if(!m)return;switch(m->parameter){case OPEN_CFW_DEV_PRIV_CONN_INIT_START:c->connecting=1;break;case OPEN_CFW_DEV_PRIV_CONN_INIT_STOP:c->connecting=0;open_cfw_cordio_dm_device_privacy_set_pending_rpa();break;case OPEN_CFW_DEV_PRIV_ADV_SET_ADD:if(m->advertising_handle<2){struct open_cfw_cordio_dm_dev_priv_adv*a=&c->extended[m->advertising_handle];a->configured=1;a->connectable=m->connectable;if(c->use_resolvable&&c->address_initialized&&open_cfw_cordio_dm_dev_priv_adv_callback)open_cfw_cordio_dm_dev_priv_adv_callback(m->advertising_handle,open_cfw_cordio_dm_dev_priv_local_address);}break;case OPEN_CFW_DEV_PRIV_ADV_SET_REMOVE:if(m->advertising_handle<2)z(&c->extended[m->advertising_handle],sizeof(c->extended[0]));break;case OPEN_CFW_DEV_PRIV_ADV_SETS_CLEAR:z(c->extended,sizeof(c->extended));break;default:break;}}
void open_cfw_cordio_dm_device_privacy_hci_handler(struct open_cfw_cordio_dm_dev_priv_message*m){struct{uint16_t parameter;uint8_t event,status,address[6],first;}e;if(!m||!open_cfw_cordio_dm_dev_priv_control.use_resolvable||m->event!=1)return;z(&e,sizeof(e));e.event=1;e.status=m->status;cp(e.address,open_cfw_cordio_dm_dev_priv_local_address,6);e.first=(uint8_t)!open_cfw_cordio_dm_dev_priv_control.address_initialized;if(open_cfw_cordio_dm_dev_priv_callback)open_cfw_cordio_dm_dev_priv_callback(&e);open_cfw_cordio_dm_dev_priv_control.address_initialized=1;}
void open_cfw_cordio_dm_device_privacy_message_handler(struct open_cfw_cordio_dm_dev_priv_message*m){static void(*const a[7])(struct open_cfw_cordio_dm_dev_priv_message*)={open_cfw_cordio_dm_device_privacy_action_start,open_cfw_cordio_dm_device_privacy_action_stop,open_cfw_cordio_dm_device_privacy_action_timeout,open_cfw_cordio_dm_device_privacy_action_aes_complete,open_cfw_cordio_dm_device_privacy_action_rpa_start,open_cfw_cordio_dm_device_privacy_action_rpa_stop,open_cfw_cordio_dm_device_privacy_action_control};if(m&&(m->event&7U)<7U)a[m->event&7U](m);}
void open_cfw_cordio_dm_device_privacy_reset(void){if(open_cfw_cordio_dm_dev_priv_control.use_resolvable)open_cfw_cordio_wsf_timer_stop(&open_cfw_cordio_dm_dev_priv_control);z(&open_cfw_cordio_dm_dev_priv_control,sizeof(open_cfw_cordio_dm_dev_priv_control));}
void open_cfw_cordio_dm_device_privacy_initialize(void){open_cfw_cordio_wsf_task_lock();open_cfw_dm_dev_priv_interface_installed=1;open_cfw_cordio_dm_dev_priv_adv_callback=0;open_cfw_cordio_wsf_task_unlock();}
void open_cfw_cordio_dm_device_privacy_start(uint16_t interval){struct open_cfw_cordio_dm_dev_priv_message*m=open_cfw_cordio_wsf_message_allocate(sizeof(*m));if(m){z(m,sizeof(*m));m->event=0;m->change_interval=interval;open_cfw_cordio_wsf_message_send(open_cfw_cordio_dm_dev_priv_handler_id,m);}}
void open_cfw_cordio_dm_device_privacy_stop(void){struct open_cfw_cordio_dm_dev_priv_message*m=open_cfw_cordio_wsf_message_allocate(4);if(m){z(m,4);m->event=1;open_cfw_cordio_wsf_message_send(open_cfw_cordio_dm_dev_priv_handler_id,m);}}
