from pathlib import Path
import argparse,subprocess,json,hashlib
D=Path(__file__).resolve().parent;S=D.parent/'dependency-followup-2026-10-08/touch-source';p=argparse.ArgumentParser();p.add_argument('--gcc',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--flash-source',type=Path);p.add_argument('--providers-source',type=Path);p.add_argument('--extended-source',type=Path);a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
pdl=S/'mtb-pdl-cat2-35f1714623cfea682d5e285af80d50416b4c7bbc';core=S/'core-lib-ca57d1e519e08badec6891d1776c7b4f05e09561';inc=['-I'+str(i) for i in [D,S,S/'cmsis',pdl/'drivers/include',pdl/'devices/include',core/'include']];flags=['-mcpu=cortex-m0plus','-mthumb','-Og','-fshort-enums','-ffreestanding','-fno-builtin','-DCY8C4046FNI_T412','-ffunction-sections'];objects=[]
F=D.parent/'touch-flash-provider-2026-10-08'
inc.append('-I'+str(F))
for src,name in [(a.flash_source or F/'flash.c','flash.o'),(a.providers_source or F/'providers.c','providers.o'),(a.extended_source or D/'extended.c','extended.o'),(D/'boundaries.S','boundaries.o'),(pdl/'drivers/source/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy_syslib_gcc.S','asm.o')]:
 obj=a.output/name;subprocess.run([str(a.gcc),*flags,*inc,'-c',str(src),'-o',str(obj)],check=True);objects.append(obj)
elf=a.output/'provider.elf';subprocess.run([str(a.gcc.with_name('arm-none-eabi-ld')),'--gc-sections','-Ttext=0x100000','-e','touch_extended_write','-u','touch_row_checksum','-u','touch_storage_zero','-u','touch_storage_program','-u','touch_storage_no_erase','-u','touch_storage_copy','-u','touch_flash_status',*[str(o) for o in objects],'-o',str(elf)],check=True)
r=dict(elf_sha256=hashlib.sha256(elf.read_bytes()).hexdigest(),objects={i.name:hashlib.sha256(i.read_bytes()).hexdigest() for i in objects},sources={i.name:hashlib.sha256(i.read_bytes()).hexdigest() for i in [a.flash_source or F/'flash.c',a.providers_source or F/'providers.c',a.extended_source or D/'extended.c',D/'boundaries.S']},compiler=subprocess.check_output([str(a.gcc),'--version'],text=True).splitlines()[0],flags=flags,limits='Independent flash/provider control flow; SROM external synthetic boundary; not safe deployable firmware.')
(a.output/'receipt.json').write_text(json.dumps(r,indent=2)+'\n');print('Built',r['elf_sha256'])
