from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47f294;end=0x47f3c6
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-two-stage-mask-write-fresh-field-check-tail-21442-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Two-stage mask update, fresh field comparisons and record tail\n\nPartial/unaccepted;306instructionbytes47F294..47F3C6,continuation21440 with40frameactive,R4record,R6mask,SP4othermask,R5setupindicator. R7=FAD4pointer;SP4==freshword[R7] jumpsF376, bypassingupdate,checksandR5cleanup. Otherwise independentlyfreshword[R7]&SP4→R3;R8=FADCpointer;freshword[R8]&R6 stored[R8]. R9=FAD4pointer;SP0=1 overwrites savedentryR1;480826(5,R9,207,R3,fifthstack1) fullnonzero exitsunchanged, withoutR5cleanup. Zero→480312(5,1,SP+4,liveR3);helpermayalterSP4;storeR6[R8];SP0=1;480826(5,R9,207,freshSP4,fifth1). LOW8(R5)!=0 independentlyfreshwordthroughFAD8 clearsbit0beforetestingsecondhelperfullresult; nonzeroresult exitsunchanged.\n\nSecondhelperzero→successivefreshcomparisonpairs,shortcircuitfirstmismatch: word[R7]&7 versus word[R8]&7; bit3 versusbit3; bit6ofsecondfresh[R7] AND bit3offirstfresh[R7] versus fresh[R8]bit4; fresh[R7]bit7 versusfresh[R8]bit5; freshwordthroughFAE0bit27 versusfreshwordthroughFAE4bit27. No caching across reads. Any mismatch returns1. Allmatch→F376. F376freshrecordbyte4 nonzero independentlyfreshwordthroughFE94 clearsbit1, zero independentlyfreshword setsbit1. Then freshrecordbyte2==1 independentlyfreshwordthroughFE94 setsbit0 andreturns0. Otherwise independentlyreloadrecordbyte2:zero independentlyfreshwordFE94clearsbit0returns0;nonzeroreturns5. Thus bit1canchangeeveniffinalstatus5,andbyte2canchangebetweenreads. CommonF3AA POP R1..R9,PC releases40; restoredR1 reflectsSP0writes onupdatepath,R2reflectsSP4constructedmask/helpermutations. No PRIMASK restoreinthisroutine. Prefixconditionalbitsetcanremain oninitialequality/firsthelperfailure; do not inventcleanup. Externalhelpers/pointedownershipunresolved,noMMIO/C/freeze/fullcoverageclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
