"""Rebuild offline clock/preparation comparators; no production/index writes."""
from pathlib import Path
import argparse,subprocess,json,hashlib
p=argparse.ArgumentParser();p.add_argument('--gcc',type=Path,required=True);p.add_argument('--public-object',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();D=Path(__file__).resolve().parent;root=D.parents[2];touch=root/'g2/components/touch';a.output.mkdir(parents=True,exist_ok=True);link=a.output/'link.ld';link.write_text('SECTIONS { . = 0x100000; .text : { *(.text*) *(.rodata*) } /DISCARD/ : { *(.ARM.exidx*) *(.comment*) } }\n')
common=['scan_preparation_offline/prepare.c','clock_selection_offline/clock.c','auto_dither_offline/dither.c','base_frame_offline/base.c','all_slot_offline/slots.c','frame_generation_offline/generator.c','mode_offline/mode.c','mode_offline/cpu.c','pin_control_offline/pins.c','config_bootstrap_offline/bootstrap.c','saturated_scan_offline/scan.c','max_raw_offline/max_raw.c','scan_frame_offline/frame.c','scan_watchdog_offline/watchdog.c'];receipt={};h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
for name,paths,roots in [('clock',[touch/'clock_selection_offline/clock.c'],['touch_poly_period','touch_dither_value','touch_dither_limit','touch_ssc_run','touch_prs_auto','touch_ssc_auto','touch_lfsr_auto','touch_initialize_source_clock','touch_timer_cycles']),('prepare',[*[touch/s for s in common],D/'callback_probe.c'],['touch_prepare_scan','touch_prepare_scan_fields','touch_dither_scale','touch_dither_measure','touch_test_init_callback'])]:
 flags=['-mcpu=cortex-m0plus','-mthumb','-Og','-ffreestanding','-fno-builtin','-ffunction-sections','-nostdlib','-Wl,--gc-sections',*['-Wl,-u,'+r for r in roots]];elf=a.output/(name+'.elf');cmd=[str(a.gcc),*flags,'-T',str(link),'-I'+str(touch/'eeprom_offline'),'-I'+str(touch/'eeprom_init_offline'),*[str(s) for s in paths]]
 if name=='prepare':cmd.append(str(a.public_object))
 subprocess.run([*cmd,'-lgcc','-o',str(elf)],check=True);receipt[name]={'elf':str(elf),'elf_sha256':h(elf),'sources':{str(s):h(s) for s in paths},'flags':flags}
receipt['public_object']={'path':str(a.public_object),'sha256':h(a.public_object),'pdl_pin':'35f1714623cfea682d5e285af80d50416b4c7bbc'};receipt['gcc']={'path':str(a.gcc),'sha256':h(a.gcc),'version':subprocess.check_output([str(a.gcc),'--version'],text=True).splitlines()[0]};(a.output/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print('Built clock and preparation offline comparators')
