from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47e674;end=0x47e712
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-fatal-initialization-forty-four-byte-allocation-wrapper-21384-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text("# Initialization with fatal failure and forty-four-byte allocation wrapper\n\nPartial/unaccepted;158instructionbytes47E674..47E712,twoentries.\nE674 PUSH R3,R4,R5,LR16;SP-=24,total40;R4=0;47EAB8(liveentryargs). Freshword[pointerliteralEB6C]zero→failure. Nonzero→SP16=0,SP12=0;4D3610(SP+16,SP+12,SP+20,liveR3). R5=literalEB70pointer;SP8=freshSP16,SP4=freshSP12,SP0=54;454820(address47E879,literalEB74,freshSP20,0) withthree stackwords. AddressE879 formed ADDW alignedPC(E6B4)+453,not decodeddatahere. Storefullresultword[R5],freshreloadwordnonzero→R4=1. FailureR4zero→5FA0A4(liveargs);ifreturnsstoreword0toFFFFFFFF thenE6D4selfbranchifstorecompletes. SuccessR0=1,SP+=28discard24localsandsavedentryR3;POP R4,R5,PC12.\nE6DC PUSH R2,R3,R4,R5,R6,R7,R8,LR32;R5/R6/R7/R8=fullentryR0/R1/R2/R3.456110(44,liveR1,R2,R3)→R4. Fullzero skipswrites/helperandreturns0. Nonzero→byte[R4+40]=0;SP4=R4 overwritessavedentryR3;SP0=freshwordSP32 (caller'sfifthstackargument) overwritessavedentryR2;47E75A(entryR0,entryR1,entryR2,entryR3) withstackargsfifthcallerword,sixthR4. ReturnR0=R4,discardhelperresult;POP R1,R2,R4,R5,R6,R7,R8,PC32 returnsR1=SP0,R2=SP4 (savedentryR2/R3onallocationfailure,rewrittenslotsonsuccesssubjectcallee writes). No allocationownership/helpermeaningbeyondexactbehavior. No C/freeze/completenessclaim.\n")
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
