/* SPDX-License-Identifier: MIT */
/* Clean-room reconstruction of the G2 introspective qsort runtime. */

typedef __SIZE_TYPE__ open_cfw_mq_size;
typedef int (*open_cfw_mq_compare)(const void *, const void *);

#if defined(__arm__) || defined(__thumb__)
extern void open_cfw_bootloader_memory_sort3_423972(void);
extern void open_cfw_bootloader_memory_rotate3_4238ba(void);
extern void open_cfw_bootloader_memory_swap_423864(void);
extern void open_cfw_bootloader_memcpy_41568c(void);
extern void open_cfw_bootloader_memory_heap_sift_4239c2(void);
extern void open_cfw_bootloader_memory_rotate_front_423928(void);

__attribute__((used, naked, noinline))
void open_cfw_bootloader_memory_qsort_core_423a48(void)
{
    __asm__ volatile(
        "90:\n"
        "push.w {r0, r2, r4, r5, r6, r7, r8, r9, r10, r11, lr}\n"
        "sub sp, #0x8c\n"
        "mov r9, r1\n"
        "ldr r6, [sp, #0xb8]\n"
        "mov r5, r3\n"
        "b 18f\n"
        "2:\n"
        "lsrs r7, r7, #3\n"
        "adds r7, r7, #1\n"
        "ldr r0, [sp, #0x8c]\n"
        "str r6, [sp]\n"
        "muls r7, r5, r7\n"
        "mov r3, r5\n"
        "add.w r2, r0, r7, lsl #1\n"
        "adds r1, r0, r7\n"
        "bl open_cfw_bootloader_memory_sort3_423972\n"
        "rsb.w r11, r7, #0\n"
        "str r6, [sp]\n"
        "mov r3, r5\n"
        "adds r2, r4, r7\n"
        "mov r1, r4\n"
        "add.w r0, r4, r11\n"
        "bl open_cfw_bootloader_memory_sort3_423972\n"
        "lsls r0, r7, #1\n"
        "add r11, r10\n"
        "rsbs r0, r0, #0\n"
        "str r6, [sp]\n"
        "mov r3, r5\n"
        "mov r2, r10\n"
        "mov r1, r11\n"
        "add r0, r10\n"
        "bl open_cfw_bootloader_memory_sort3_423972\n"
        "ldr r0, [sp, #0x8c]\n"
        "str r6, [sp]\n"
        "mov r3, r5\n"
        "mov r2, r11\n"
        "mov r1, r4\n"
        "adds r0, r0, r7\n"
        "34:\n"
        "bl open_cfw_bootloader_memory_sort3_423972\n"
        "ldr r4, [sp, #8]\n"
        "b 4f\n"
        "3:\n"
        "mov r4, r7\n"
        "4:\n"
        "ldr r0, [sp, #0x8c]\n"
        "cmp r0, r4\n"
        "bhs 5f\n"
        "ldr r1, [sp, #4]\n"
        "adds r7, r4, r1\n"
        "mov r1, r4\n"
        "mov r0, r7\n"
        "blx r6\n"
        "cmp r0, #0\n"
        "beq 3b\n"
        "5:\n"
        "cmp r8, r9\n"
        "bhs 6f\n"
        "mov r1, r4\n"
        "mov r0, r8\n"
        "blx r6\n"
        "cmp r0, #0\n"
        "it eq\n"
        "addeq r8, r5\n"
        "beq 5b\n"
        "6:\n"
        "mov r7, r8\n"
        "mov r10, r4\n"
        "b 10f\n"
        "7:\n"
        "mov r3, r5\n"
        "mov r2, r8\n"
        "mov r1, r4\n"
        "mov r0, r7\n"
        "bl open_cfw_bootloader_memory_rotate3_4238ba\n"
        "b 9f\n"
        "8:\n"
        "cmp r8, r7\n"
        "bne 7b\n"
        "mov r2, r5\n"
        "mov r1, r4\n"
        "mov r0, r7\n"
        "bl open_cfw_bootloader_memory_swap_423864\n"
        "9:\n"
        "adds r7, r7, r5\n"
        "add r4, r5\n"
        "add r8, r5\n"
        "10:\n"
        "cmp r7, r9\n"
        "bhs 12f\n"
        "mov r1, r7\n"
        "mov r0, r4\n"
        "blx r6\n"
        "cmp r0, #0\n"
        "bmi 11f\n"
        "bgt 12f\n"
        "mov r2, r5\n"
        "mov r1, r7\n"
        "mov r0, r8\n"
        "bl open_cfw_bootloader_memory_swap_423864\n"
        "add r8, r5\n"
        "11:\n"
        "adds r7, r7, r5\n"
        "b 10b\n"
        "12:\n"
        "str r5, [sp]\n"
        "str r6, [sp, #0xb8]\n"
        "b 16f\n"
        "13:\n"
        "mov r5, r0\n"
        "14:\n"
        "mov.w r11, #0x80\n"
        "cmp r5, #0x80\n"
        "it ls\n"
        "movls r11, r5\n"
        "mov r2, r11\n"
        "mov r1, r10\n"
        "add r0, sp, #8\n"
        "bl open_cfw_bootloader_memcpy_41568c\n"
        "mov r2, r11\n"
        "mov r1, r6\n"
        "mov r0, r10\n"
        "bl open_cfw_bootloader_memcpy_41568c\n"
        "mov r2, r11\n"
        "add r1, sp, #8\n"
        "mov r0, r6\n"
        "bl open_cfw_bootloader_memcpy_41568c\n"
        "subs.w r5, r5, r11\n"
        "add r10, r11\n"
        "add r6, r11\n"
        "bne 14b\n"
        "15:\n"
        "ldr.w r10, [sp, #4]\n"
        "16:\n"
        "ldr.w r11, [sp, #0x8c]\n"
        "cmp r11, r10\n"
        "bhs 17f\n"
        "ldr r0, [sp]\n"
        "ldr r2, [sp, #0xb8]\n"
        "rsbs r0, r0, #0\n"
        "add r0, r10\n"
        "str r0, [sp, #4]\n"
        "mov r1, r4\n"
        "blx r2\n"
        "cmp r0, #0\n"
        "bmi 15b\n"
        "bgt 17f\n"
        "ldr r0, [sp]\n"
        "ldr r6, [sp, #4]\n"
        "rsbs r0, r0, #0\n"
        "add r4, r0\n"
        "ldr r0, [sp]\n"
        "cmp r0, #0x40\n"
        "mov r10, r4\n"
        "bhs 13b\n"
        "cmp r0, #0\n"
        "beq 15b\n"
        "36:\n"
        "ldrb.w r1, [r10]\n"
        "ldrb r2, [r6]\n"
        "strb r2, [r10], #1\n"
        "subs r0, r0, #1\n"
        "strb r1, [r6], #1\n"
        "bne 36b\n"
        "b 15b\n"
        "17:\n"
        "ldr r0, [sp, #0x8c]\n"
        "ldr r5, [sp]\n"
        "ldr r6, [sp, #0xb8]\n"
        "cmp r10, r0\n"
        "bne 19f\n"
        "cmp r7, r9\n"
        "bne 8b\n"
        "ldr r0, [sp, #0x90]\n"
        "str r6, [sp]\n"
        "lsrs r0, r0, #1\n"
        "add.w r0, r0, r0, lsr #1\n"
        "sub.w r4, r4, r11\n"
        "sub.w r9, r9, r8\n"
        "str r0, [sp, #0x90]\n"
        "udiv r4, r4, r5\n"
        "udiv r9, r9, r5\n"
        "cmp r9, r4\n"
        "ldr r2, [sp, #0x90]\n"
        "mov r3, r5\n"
        "blo 22f\n"
        "ldr r0, [sp, #0x8c]\n"
        "mov r1, r4\n"
        "bl 90b\n"
        "str.w r8, [sp, #0x8c]\n"
        "18:\n"
        "ldr r0, [sp, #0x90]\n"
        "cmp r0, #0\n"
        "beq 23f\n"
        "cmp.w r9, #0x21\n"
        "blo 23f\n"
        "ldr r0, [sp, #0x8c]\n"
        "lsr.w r1, r9, #1\n"
        "mul r9, r5, r9\n"
        "add r9, r0\n"
        "muls r1, r5, r1\n"
        "adds r4, r0, r1\n"
        "rsbs r0, r5, #0\n"
        "str r0, [sp, #4]\n"
        "add.w r10, r9, r0\n"
        "ldr r0, [sp, #0x8c]\n"
        "str r4, [sp, #8]\n"
        "sub.w r0, r10, r0\n"
        "udiv r7, r0, r5\n"
        "cmp r7, #0x29\n"
        "add.w r8, r4, r5\n"
        "bhs.w 2b\n"
        "ldr r0, [sp, #0x8c]\n"
        "str r6, [sp]\n"
        "mov r3, r5\n"
        "mov r2, r10\n"
        "mov r1, r4\n"
        "b 34b\n"
        "19:\n"
        "rsbs r0, r5, #0\n"
        "cmp r7, r9\n"
        "add r10, r0\n"
        "bne 21f\n"
        "add r4, r0\n"
        "cmp r10, r4\n"
        "add r8, r0\n"
        "bne 20f\n"
        "mov r2, r5\n"
        "mov r1, r8\n"
        "mov r0, r4\n"
        "bl open_cfw_bootloader_memory_swap_423864\n"
        "b 10b\n"
        "20:\n"
        "mov r3, r5\n"
        "mov r2, r4\n"
        "mov r1, r8\n"
        "mov r0, r10\n"
        "bl open_cfw_bootloader_memory_rotate3_4238ba\n"
        "b 10b\n"
        "21:\n"
        "mov r2, r5\n"
        "mov r1, r10\n"
        "mov r0, r7\n"
        "bl open_cfw_bootloader_memory_swap_423864\n"
        "b 11b\n"
        "22:\n"
        "mov r1, r9\n"
        "mov r0, r8\n"
        "bl 90b\n"
        "mov r9, r4\n"
        "b 18b\n"
        "23:\n"
        "cmp.w r9, #0x21\n"
        "blo 28f\n"
        "lsrs.w r4, r9, #1\n"
        "beq 25f\n"
        "ldr r7, [sp, #0x8c]\n"
        "24:\n"
        "subs r4, r4, #1\n"
        "str r6, [sp]\n"
        "mov r3, r5\n"
        "mov r2, r9\n"
        "mov r1, r4\n"
        "mov r0, r7\n"
        "bl open_cfw_bootloader_memory_heap_sift_4239c2\n"
        "cmp r4, #0\n"
        "bne 24b\n"
        "str r7, [sp, #0x8c]\n"
        "25:\n"
        "ldr r0, [sp, #0x8c]\n"
        "mul r1, r5, r9\n"
        "adds r4, r0, r1\n"
        "rsb.w r8, r5, #0\n"
        "mov r7, r0\n"
        "26:\n"
        "add r4, r8\n"
        "mov r2, r5\n"
        "mov r1, r4\n"
        "mov r0, r7\n"
        "bl open_cfw_bootloader_memory_swap_423864\n"
        "sub.w r9, r9, #1\n"
        "str r6, [sp]\n"
        "mov r3, r5\n"
        "mov r2, r9\n"
        "movs r1, #0\n"
        "mov r0, r7\n"
        "bl open_cfw_bootloader_memory_heap_sift_4239c2\n"
        "cmp.w r9, #1\n"
        "bhi 26b\n"
        "27:\n"
        "add sp, #0x94\n"
        "pop.w {r4, r5, r6, r7, r8, r9, r10, r11, pc}\n"
        "28:\n"
        "cmp.w r9, #1\n"
        "bls 27b\n"
        "ldr r7, [sp, #0x8c]\n"
        "mov r8, r7\n"
        "mov r4, r9\n"
        "rsb.w r11, r5, #0\n"
        "b 30f\n"
        "29:\n"
        "mov r2, r5\n"
        "mov r1, r7\n"
        "mov r0, r8\n"
        "37:\n"
        "bl open_cfw_bootloader_memory_rotate_front_423928\n"
        "30:\n"
        "subs r4, r4, #1\n"
        "beq 27b\n"
        "adds r7, r7, r5\n"
        "mov r1, r8\n"
        "mov r0, r7\n"
        "blx r6\n"
        "cmp r0, #0\n"
        "bmi 29b\n"
        "mov r9, r7\n"
        "mov r10, r7\n"
        "b 32f\n"
        "31:\n"
        "mov r9, r10\n"
        "32:\n"
        "add r10, r11\n"
        "mov r1, r10\n"
        "mov r0, r7\n"
        "blx r6\n"
        "cmp r0, #0\n"
        "bmi 31b\n"
        "cmp r9, r7\n"
        "beq 30b\n"
        "mov r2, r5\n"
        "mov r1, r7\n"
        "mov r0, r9\n"
        "b 37b\n");
}

__attribute__((used, naked, noinline))
void open_cfw_bootloader_memory_qsort_423d08(void)
{
    __asm__ volatile(
        "cmp r0, #0\n"
        "bne 1f\n"
        "bx lr\n"
        "1:\n"
        "push {r2, r3, r4, lr}\n"
        "movs r4, r3\n"
        "beq 2f\n"
        "str r3, [sp]\n"
        "mov r3, r2\n"
        "mov r2, r1\n"
        "bl open_cfw_bootloader_memory_qsort_core_423a48\n"
        "2:\n"
        "pop {r0, r1, r4, pc}\n");
}
#else
static void open_cfw_mq_swap(unsigned char *left, unsigned char *right,
                             open_cfw_mq_size width)
{
    while (width-- != 0U) {
        unsigned char value = *left;
        *left++ = *right;
        *right++ = value;
    }
}

void open_cfw_bootloader_memory_qsort_423d08(
    void *base_pointer, open_cfw_mq_size count, open_cfw_mq_size width,
    open_cfw_mq_compare compare)
{
    unsigned char *base = (unsigned char *)base_pointer;
    open_cfw_mq_size index;

    if (base == (unsigned char *)0 || compare == (open_cfw_mq_compare)0 ||
        width == 0U || count < 2U) return;
    for (index = 1U; index < count; ++index) {
        open_cfw_mq_size position = index;
        while (position != 0U &&
               compare(base + position * width,
                       base + (position - 1U) * width) < 0) {
            open_cfw_mq_swap(base + position * width,
                             base + (position - 1U) * width, width);
            --position;
        }
    }
}
#endif
