/* SPDX-License-Identifier: BSD-3-Clause */
/* Apollo510 SPOT-manager stimulus update pipeline at 0x0042A878. */

typedef __UINT32_TYPE__ open_cfw_spotmgr_update_u32;
typedef __UINT8_TYPE__ open_cfw_spotmgr_update_u8;

#if defined(__arm__) || defined(__thumb__)

__attribute__((used, noinline, naked, visibility("default")))
open_cfw_spotmgr_update_u32
open_cfw_bootloader_spotmgr_power_state_update_42a878(
    open_cfw_spotmgr_update_u32 stimulus __attribute__((unused)),
    open_cfw_spotmgr_update_u32 on __attribute__((unused)),
    void *arguments __attribute__((unused)))
{
    __asm volatile(
        "push.w {r4, r5, r6, r7, r8, r9, r10, lr}\n"
        "sub sp, #0x20\n"
        "movs r7, r1\n"
        "movs r4, r2\n"
        "movs r5, #0\n"
        "movs r1, #0\n"
        "str r1, [sp, #0x18]\n"
        "movs r1, #0\n"
        "str r1, [sp, #0x14]\n"
        "movs.w r8, #0\n"
        "movs r6, #1\n"
        "ldr.w r1, [pc, #0x44c]\n"
        "ldr r1, [r1]\n"
        "ubfx r1, r1, #4, #2\n"
        "cmp r1, #3\n"
        "bne.n .Lupdate_not_ready\n"
        "ldr.w r1, [pc, #0x3ac]\n"
        "ldr r1, [r1]\n"
        "ldr.w r2, [pc, #0x43c]\n"
        "cmp r1, r2\n"
        "bne.n .Lupdate_bad_magic\n"
        "mov r9, r0\n"
        "bl open_cfw_bootloader_critical_enter_41b8ec\n"
        "str r0, [sp, #0x1c]\n"
        "mov r0, r9\n"
        "uxtb r0, r0\n"
        "cmp r0, #0\n"
        "bne.n .Lupdate_after_reset\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_after_reset\n"
        "ldrb r0, [r4]\n"
        "strb.w r0, [sp, #0x11]\n"
        "ldr.w r1, [pc, #0x41c]\n"
        "ldrb r0, [r1]\n"
        "cmp r0, #4\n"
        "beq.n .Lupdate_reset_valid\n"
        "ldrb r0, [r1]\n"
        "cmp r0, #3\n"
        "beq.n .Lupdate_reset_valid\n"
        "ldrb r0, [r1]\n"
        "cmp r0, #2\n"
        "bne.n .Lupdate_after_reset\n"
        ".Lupdate_reset_valid:\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "cmp r0, #0\n"
        "beq.n .Lupdate_reset_commit\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "cmp r0, #1\n"
        "bne.n .Lupdate_after_reset\n"
        ".Lupdate_reset_commit:\n"
        "movs.w r8, #1\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "strb r0, [r1]\n"
        ".Lupdate_after_reset:\n"
        "uxtb.w r8, r8\n"
        "cmp.w r8, #0\n"
        "bne.w .Lupdate_restore\n"
        "ldr.w r0, [pc, #0x3e4]\n"
        "ldr r0, [r0]\n"
        "str r0, [sp]\n"
        "ldr.w r0, [pc, #0x3e0]\n"
        "ldr r0, [r0]\n"
        "str r0, [sp, #4]\n"
        "ldr.w r0, [pc, #0x3dc]\n"
        "ldr r0, [r0]\n"
        "str r0, [sp, #8]\n"
        "ldr.w r0, [pc, #0x3d8]\n"
        "ldr r0, [r0]\n"
        "str r0, [sp, #0xc]\n"
        "ldr.w r10, [pc, #0x3d4]\n"
        "ldrb.w r0, [r10]\n"
        "strb.w r0, [sp, #0x10]\n"
        "ldr r0, [sp]\n"
        "lsls r0, r0, #0xd\n"
        "bpl.n .Lupdate_cpu_zero\n"
        "ldr.w r0, [pc, #0x3c8]\n"
        "ldrb r0, [r0]\n"
        "cmp r0, #0\n"
        "bne.n .Lupdate_cpu_two\n"
        "movs r0, #1\n"
        "b.n .Lupdate_cpu_store\n"
        ".Lupdate_not_ready:\n"
        "movs r0, #0\n"
        "b.n .Lupdate_return\n"
        ".Lupdate_bad_magic:\n"
        "movs r0, #1\n"
        "b.n .Lupdate_return\n"
        ".Lupdate_cpu_two:\n"
        "movs r0, #2\n"
        "b.n .Lupdate_cpu_store\n"
        ".Lupdate_cpu_zero:\n"
        "movs r0, #0\n"
        ".Lupdate_cpu_store:\n"
        "strb.w r0, [sp, #0x12]\n"
        "ldr.w r8, [pc, #0x390]\n"
        "ldrb.w r0, [r8]\n"
        "strb.w r0, [sp, #0x11]\n"
        "uxtb.w r9, r9\n"
        "cmp.w r9, #0\n"
        "beq.n .Lupdate_cpu_stimulus\n"
        "cmp.w r9, #2\n"
        "beq.n .Lupdate_temperature\n"
        "blo.w .Lupdate_gpu_stimulus\n"
        "cmp.w r9, #4\n"
        "beq.n .Lupdate_audio\n"
        "blo.n .Lupdate_device\n"
        "cmp.w r9, #6\n"
        "beq.n .Lupdate_ssram\n"
        "blo.n .Lupdate_memory\n"
        "b.n .Lupdate_invalid_stimulus\n"
        ".Lupdate_device:\n"
        "uxtb r7, r7\n"
        "cmp r7, #0\n"
        "beq.n .Lupdate_device_done\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_device_missing\n"
        "ldr r1, [sp]\n"
        "ldr r0, [r4]\n"
        "orrs r1, r0\n"
        "str r1, [sp]\n"
        "b.n .Lupdate_device_done\n"
        ".Lupdate_device_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_device_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_audio:\n"
        "uxtb r7, r7\n"
        "cmp r7, #0\n"
        "beq.n .Lupdate_audio_done\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_audio_missing\n"
        "ldr r1, [sp, #4]\n"
        "ldr r0, [r4]\n"
        "orrs r1, r0\n"
        "str r1, [sp, #4]\n"
        "b.n .Lupdate_audio_done\n"
        ".Lupdate_audio_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_audio_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_memory:\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_memory_missing\n"
        "ldr r0, [r4]\n"
        "str r0, [sp, #8]\n"
        "b.n .Lupdate_memory_done\n"
        ".Lupdate_memory_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_memory_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_ssram:\n"
        "uxtb r7, r7\n"
        "cmp r7, #0\n"
        "beq.n .Lupdate_ssram_done\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_ssram_missing\n"
        "ldr r0, [r4]\n"
        "str r0, [sp, #0xc]\n"
        "b.n .Lupdate_ssram_done\n"
        ".Lupdate_ssram_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_ssram_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_temperature:\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_temperature_missing\n"
        "vldr s0, [r4]\n"
        "bl open_cfw_bootloader_float_range_classify_427e0c\n"
        "strb.w r0, [sp, #0x10]\n"
        "ldrb.w r0, [sp, #0x10]\n"
        "strb.w r0, [r10]\n"
        "ldrb.w r0, [r10]\n"
        "cmp r0, #3\n"
        "bge.n .Lupdate_temp_flag_clear\n"
        "movs r0, #1\n"
        "ldr.w r1, [pc, #0x304]\n"
        "strb r0, [r1]\n"
        "b.n .Lupdate_temp_ranges\n"
        ".Lupdate_temp_flag_clear:\n"
        "movs r0, #0\n"
        "ldr r1, [pc, #0x2fc]\n"
        "strb r0, [r1]\n"
        ".Lupdate_temp_ranges:\n"
        "ldrb.w r0, [r10]\n"
        "cmp r0, #0\n"
        "beq.n .Lupdate_temp_vlow\n"
        "cmp r0, #2\n"
        "beq.n .Lupdate_temp_mid\n"
        "blo.n .Lupdate_temp_low\n"
        "cmp r0, #4\n"
        "beq.n .Lupdate_temp_invalid\n"
        "blo.n .Lupdate_temp_high\n"
        "b.n .Lupdate_temp_done\n"
        ".Lupdate_temp_vlow:\n"
        "ldr r0, [pc, #0x2e4]\n"
        "str r0, [r4, #4]\n"
        "ldr r0, [pc, #0x2e4]\n"
        "str r0, [r4, #8]\n"
        "b.n .Lupdate_temp_done\n"
        ".Lupdate_temp_low:\n"
        "ldr r0, [pc, #0x2e4]\n"
        "str r0, [r4, #4]\n"
        "movs r0, #0\n"
        "str r0, [r4, #8]\n"
        "b.n .Lupdate_temp_done\n"
        ".Lupdate_temp_mid:\n"
        "movs.w r0, #-0x40000000\n"
        "str r0, [r4, #4]\n"
        "ldr r0, [pc, #0x2d8]\n"
        "str r0, [r4, #8]\n"
        "b.n .Lupdate_temp_done\n"
        ".Lupdate_temp_high:\n"
        "ldr r0, [pc, #0x2d4]\n"
        "str r0, [r4, #4]\n"
        "ldr r0, [pc, #0x2d4]\n"
        "str r0, [r4, #8]\n"
        "b.n .Lupdate_temp_done\n"
        ".Lupdate_temp_invalid:\n"
        "movs r0, #0\n"
        "str r0, [r4, #4]\n"
        "movs r0, #0\n"
        "str r0, [r4, #8]\n"
        "movs r5, #6\n"
        "b.n .Lupdate_temp_done\n"
        ".Lupdate_temperature_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_temp_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_cpu_stimulus:\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_cpu_missing\n"
        "ldrb r0, [r4]\n"
        "strb.w r0, [sp, #0x11]\n"
        "ldrb.w r0, [r8]\n"
        "ldrb.w r1, [sp, #0x11]\n"
        "cmp r0, r1\n"
        "beq.n .Lupdate_cpu_done\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "cmp r0, #2\n"
        "bne.n .Lupdate_cpu_transitions\n"
        "mov r0, sp\n"
        "bl open_cfw_bootloader_spotmgr_buck_deepsleep_state_42a08c\n"
        "ldr r0, [pc, #0x2a0]\n"
        "ldr r0, [r0]\n"
        "subs r0, #9\n"
        "cmp r0, #3\n"
        "bhs.n .Lupdate_buck_flag_clear\n"
        "ldr r0, [pc, #0x128]\n"
        "ldrb r0, [r0]\n"
        "cmp r0, #7\n"
        "beq.n .Lupdate_buck_flag_clear\n"
        "movs r0, #1\n"
        "ldr r1, [pc, #0x290]\n"
        "strb r0, [r1]\n"
        "b.n .Lupdate_cpu_transitions\n"
        ".Lupdate_buck_flag_clear:\n"
        "movs r0, #0\n"
        "ldr r1, [pc, #0x288]\n"
        "strb r0, [r1]\n"
        ".Lupdate_cpu_transitions:\n"
        "ldrb.w r0, [r8]\n"
        "cmp r0, #0\n"
        "bne.n .Lupdate_cpu_one_to_zero\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "cmp r0, #1\n"
        "bne.n .Lupdate_cpu_one_to_zero\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "strb.w r0, [r8]\n"
        "b.n .Lupdate_cpu_done\n"
        ".Lupdate_cpu_one_to_zero:\n"
        "ldrb.w r0, [r8]\n"
        "cmp r0, #1\n"
        "bne.n .Lupdate_cpu_zero_to_deep\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "cmp r0, #0\n"
        "bne.n .Lupdate_cpu_zero_to_deep\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "strb.w r0, [r8]\n"
        "b.n .Lupdate_cpu_done\n"
        ".Lupdate_cpu_zero_to_deep:\n"
        "ldrb.w r0, [r8]\n"
        "cmp r0, #0\n"
        "bne.n .Lupdate_cpu_domain\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "cmp r0, #2\n"
        "bne.n .Lupdate_cpu_domain\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "strb.w r0, [r8]\n"
        "b.n .Lupdate_cpu_done\n"
        ".Lupdate_cpu_domain:\n"
        "ldrb.w r1, [r8]\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "bl open_cfw_bootloader_spotmgr_internal_power_domain_42a19c\n"
        "movs r6, #0\n"
        "ldrb.w r0, [sp, #0x11]\n"
        "strb.w r0, [r8]\n"
        "b.n .Lupdate_cpu_done\n"
        ".Lupdate_cpu_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_cpu_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_gpu_stimulus:\n"
        "cmp r4, #0\n"
        "beq.n .Lupdate_gpu_missing\n"
        "ldrb r0, [r4]\n"
        "strb.w r0, [sp, #0x12]\n"
        "b.n .Lupdate_gpu_done\n"
        ".Lupdate_gpu_missing:\n"
        "movs r5, #6\n"
        ".Lupdate_gpu_done:\n"
        "b.n .Lupdate_classify\n"
        ".Lupdate_invalid_stimulus:\n"
        "movs r5, #6\n"
        ".Lupdate_classify:\n"
        "cmp r5, #0\n"
        "bne.n .Lupdate_restore\n"
        "uxtb r6, r6\n"
        "cmp r6, #0\n"
        "beq.n .Lupdate_restore\n"
        "add r2, sp, #0x14\n"
        "add r1, sp, #0x18\n"
        "mov r0, sp\n"
        "bl open_cfw_bootloader_spotmgr_power_state_determine_42a550\n"
        "movs r5, r0\n"
        "cmp r5, #0\n"
        "bne.n .Lupdate_restore\n"
        "ldr r4, [pc, #0x1e8]\n"
        "ldr r0, [sp, #0x18]\n"
        "ldr r1, [r4]\n"
        "cmp r0, r1\n"
        "bne.n .Lupdate_apply\n"
        "ldr r0, [sp, #0x14]\n"
        "ldr r1, [pc, #0x1e4]\n"
        "ldr r1, [r1]\n"
        "cmp r0, r1\n"
        "beq.n .Lupdate_commit\n"
        ".Lupdate_apply:\n"
        "ldr r0, [pc, #0x1dc]\n"
        "ldr r3, [r0]\n"
        "ldr r2, [sp, #0x14]\n"
        "ldr r1, [r4]\n"
        "ldr r0, [sp, #0x18]\n"
        "bl open_cfw_bootloader_spotmgr_power_trims_update_42a4bc\n"
        ".Lupdate_commit:\n"
        "ldr r0, [sp, #0x18]\n"
        "str r0, [r4]\n"
        "ldr r0, [sp, #0x14]\n"
        "ldr r1, [pc, #0x1c8]\n"
        "str r0, [r1]\n"
        ".Lupdate_restore:\n"
        "ldr r0, [sp, #0x1c]\n"
        "msr primask, r0\n"
        "movs r0, r5\n"
        ".Lupdate_return:\n"
        "add sp, #0x20\n"
        "pop.w {r4, r5, r6, r7, r8, r9, r10, pc}\n"
    );
}

#else

typedef struct open_cfw_spotmgr_update_status {
    open_cfw_spotmgr_update_u32 device_power;
    open_cfw_spotmgr_update_u32 audio_power;
    open_cfw_spotmgr_update_u32 memory_power;
    open_cfw_spotmgr_update_u32 ssram_power;
    open_cfw_spotmgr_update_u8 temperature_range;
    open_cfw_spotmgr_update_u8 cpu_state;
    open_cfw_spotmgr_update_u8 gpu_state;
} open_cfw_spotmgr_update_status;

__attribute__((used, noinline, visibility("default")))
open_cfw_spotmgr_update_u32
open_cfw_bootloader_spotmgr_power_state_update_42a878_portable(
    open_cfw_spotmgr_update_status *status,
    open_cfw_spotmgr_update_u32 stimulus,
    open_cfw_spotmgr_update_u32 on,
    const void *arguments)
{
    const open_cfw_spotmgr_update_u32 *word =
        (const open_cfw_spotmgr_update_u32 *)arguments;
    const open_cfw_spotmgr_update_u8 *byte =
        (const open_cfw_spotmgr_update_u8 *)arguments;
    switch (stimulus & 0xFFU) {
    case 0U:
        if (byte == (const open_cfw_spotmgr_update_u8 *)0) return 6U;
        status->cpu_state = *byte;
        return 0U;
    case 1U:
        if (byte == (const open_cfw_spotmgr_update_u8 *)0) return 6U;
        status->gpu_state = *byte;
        return 0U;
    case 2U:
        if (byte == (const open_cfw_spotmgr_update_u8 *)0) return 6U;
        status->temperature_range = *byte;
        return status->temperature_range == 4U ? 6U : 0U;
    case 3U:
        if (on != 0U) {
            if (word == (const open_cfw_spotmgr_update_u32 *)0) return 6U;
            status->device_power |= *word;
        }
        return 0U;
    case 4U:
        if (on != 0U) {
            if (word == (const open_cfw_spotmgr_update_u32 *)0) return 6U;
            status->audio_power |= *word;
        }
        return 0U;
    case 5U:
        if (word == (const open_cfw_spotmgr_update_u32 *)0) return 6U;
        status->memory_power = *word;
        return 0U;
    case 6U:
        if (on != 0U) {
            if (word == (const open_cfw_spotmgr_update_u32 *)0) return 6U;
            status->ssram_power = *word;
        }
        return 0U;
    default:
        return 6U;
    }
}

#endif
