/* SPDX-License-Identifier: MIT */
/* Named dispatch policy; no numeric function addresses or binary payload. */
#include "runtime_gx8002_flash_interface_table.h"
struct open_cfw_gx8002_flash_interface_table open_cfw_gx8002_flash_interface = {
    .init = open_cfw_gx8002_flash_interface_initialize,
    .readdata = open_cfw_gx8002_flash_read,
    .chiperase = open_cfw_gx8002_flash_chip_erase,
    .erasedata = open_cfw_gx8002_flash_erase,
    .pageprogram = open_cfw_gx8002_flash_page_program,
    .sync = open_cfw_gx8002_flash_sync,
    .test = 0,
    .calcblockrange = open_cfw_gx8002_flash_block_range,
    .badinfo = 0,
    .pageprogram_yaffs2 = 0,
    .readoob = 0,
    .writeoob = 0,
    .gettype = open_cfw_gx8002_flash_gettype,
    .getinfo = open_cfw_gx8002_flash_getinfo,
    .write_protect_mode = open_cfw_gx8002_flash_write_protect_mode,
    .write_protect_status = open_cfw_gx8002_flash_write_protect_status,
    .write_protect_lock = open_cfw_gx8002_flash_write_protect_lock,
    .write_protect_unlock = open_cfw_gx8002_flash_write_protect_unlock,
    .otp_lock = open_cfw_gx8002_flash_otp_lock,
    .otp_status = open_cfw_gx8002_flash_otp_status,
    .otp_erase = open_cfw_gx8002_flash_otp_erase,
    .otp_write = open_cfw_gx8002_flash_otp_write,
    .otp_read = open_cfw_gx8002_flash_otp_read,
    .otp_get_region = open_cfw_gx8002_flash_otp_get_region,
    .otp_set_region = open_cfw_gx8002_flash_otp_set_region,
    .otp_get_current_region = open_cfw_gx8002_flash_otp_get_current_region,
    .otp_get_region_size = open_cfw_gx8002_flash_otp_get_region_size,
    .block_isbad = 0,
    .calc_phy_offset = 0,
    .uid_read = open_cfw_gx8002_flash_uid_read,
};
