from pathlib import Path
import json,struct,hashlib
f=Path('g2/analysis/coverage-audit-parallel-2026-10-09/followup_verify.py').read_text();exec(f[:f.index('out={}')]);P=R/'g2/analysis/touch-crtstuff-source-rebuild-2026-10-09';prev=R/'g2/analysis/touch-crt-array-binding-2026-10-09';v=json.loads((P/'results.json').read_text());l=json.loads((P/'linked-results.json').read_text());end=json.loads((P/'crtend-results.json').read_text());a=json.loads((P/'acquisition.json').read_text());acq=hashes({str((P/'source'/x['path']).relative_to(R)):x['sha256'] for x in a['files']});mounts={'/tool/':T,'/source/':P/'source','/previous/':prev,'/out/':P/'outputs'};inputs=hashes(v['consumed_inputs'],mounts);outputs=hashes(v['outputs']);li=hashes(l['inputs'],mounts)
assert (P/'outputs/tconfig.h').read_text()=='#ifndef GCC_TCONFIG_H\n#define GCC_TCONFIG_H\n#ifndef USED_FOR_TARGET\n# define USED_FOR_TARGET\n#endif\n#include "auto-host.h"\n#ifdef IN_GCC\n# include "ansidecl.h"\n#endif\n#endif /* GCC_TCONFIG_H */\n';assert (P/'outputs/libgcc_tm.h').read_text()=='#ifndef LIBGCC_TM_H\n#define LIBGCC_TM_H\n/* Automatically generated by mkheader.sh.  */\n#include "arm/bpabi-lib.h"\n#endif /* LIBGCC_TM_H */\n';assert v['target_selection']['tm_file'].split()==['arm/bpabi-lib.h'];assert not v['target_selection']['tm_defines'];assert json.loads((P/'gcc-target-selection.json').read_text())['stdout'].startswith('xm_file=\nxm_defines=\n');cmd=json.loads((P/'commands.json').read_text());assert all(x['exit_code']==0 for x in cmd)
def rel(p,sec):
 b,ss,ns,sy=elf(p);idx=ns.index(sec);out=[]
 for r in ss:
  if r[1]==9 and r[7]==idx:
   for off in range(r[4],r[4]+r[5],8):
    a,i=struct.unpack_from('<II',b,off);n,v,z,k=sy[i>>8];out.append((a,i&255,n,v,ns[k] if k<len(ns) else k))
 return out
installed=T/'lib/gcc/arm-none-eabi/14.2.1/thumb/v6-m/nofp/crtbegin.o';assert sha(installed.read_bytes())==v['installed_provider_sha256'];rows=[]
for x in v['sections']:
 sec=x['section'];s=section(P/'outputs/crtbegin.o',sec)[0];b=section(installed,sec)[0];assert s==b;assert rel(P/'outputs/crtbegin.o',sec)==rel(installed,sec);rows.append({'section':sec,'bytes':len(s),'raw_and_relocations_equal':True})
fw=(R/'g2/blobs/official/g2-2.2.6.10/firmware_touch.bin').read_bytes();stock=lambda a,n:fw[32+a-0x3300:32+a-0x3300+n]
assert sha((P/'outputs/linked-source.elf').read_bytes())==l['linked_source_elf_sha256'];linked=[]
for x in l['sections']:
 sec=x['section'];s,a=section(P/'outputs/linked-source.elf',sec);p,pa=section(prev/'outputs/linked.elf',sec);assert s==p and a==pa;assert s==stock(int(x['image_flash'],16),len(s));linked.append({'section':sec,'bytes':len(s),'source_equals_audited_provider_and_stock':True})
assert sha((prev/'original-results.json').read_bytes())==l['reused_original_receipt_sha256'];assert json.loads((prev/'original-results.json').read_text())['cases']==32
ie=T/'lib/gcc/arm-none-eabi/14.2.1/thumb/v6-m/nofp/crtend.o';assert sha(ie.read_bytes())==end['installed_provider_sha256'];assert sha((P/'outputs/crtend.o').read_bytes())==end['source_provider_sha256']
for x in end['sections']:assert section(P/'outputs/crtend.o',x['section'])[0]==section(ie,x['section'])[0]
assert section(P/'outputs/crtend.o','.eh_frame')[0]==stock(0xb56c,4)==bytes(4)
assert sha((P/'outputs/crtbegin.o').read_bytes())!=sha(installed.read_bytes());res={'status':'PASS','acquired_source_hashes':acq,'consumed_inputs_verified':len(inputs),'outputs_verified':outputs,'link_inputs_verified':li,'raw_sections_and_relocations':rows,'linked_sections':linked,'headers_match_authentic_generator_logic':True,'crt_end_terminator_data_bytes':4,'source_upgrade_bytes':152,'array_data_bytes_separate':8,'unique_binary_coverage_increment':0,'runtime_source_subtotal':1074,'reused_saved_instruction_pairs':32,'full_object_identity':False,'boundary':'No build/emulation rerun; source provenance/commands/generated dependencies/raw relocations and linked exactness independently inspected. Vendor full configure/debug identity and live reachability not proved.'};(O/'CRT-SOURCE-VERIFICATION.json').write_text(json.dumps(res,indent=2)+'\n');print('PASS genuine CRT source152upgrade,8arraydata,4terminatordata;78inputs and32case reuse')
