from pathlib import Path
import json,hashlib,struct,itertools
R=Path.cwd();O=R/'g2/analysis/coverage-audit-parallel-2026-10-09';src=(O/'seven_verify.py').read_text();exec(src[:src.index("names=['")]);G=R/'g2/analysis/touch-libgcc14-source-rebuild-2026-10-09';N=R/'g2/analysis/touch-newlib14-memcpy-2026-10-09';S=R/'g2/analysis/source-discovery-parallel-2026-10-09/acquisitions/gcc-arm14-runtime';g=json.loads((G/'results.json').read_text());n=json.loads((N/'results.json').read_text());prov=json.loads((S/'provenance.json').read_text());checks=[]
for f in g['provider_compilations']:
 b,ss,ns,sy=elf(G/'outputs'/(f['member']+'.o'));x=ss[ns.index('.text')];data=b[x[4]:x[4]+x[5]];ab,ass,ans,asy=elf(R/'g2/analysis/touch-libgcc14-division-2026-10-09/outputs'/(f['member']+'.o'));ax=ass[ans.index('.text')];rs=relocs(b,ss,ns,sy,ns.index('.text'));checks.append({'member':f['member'],'input_hashes_verified':all(sha((S/k[len('/source/'):]).read_bytes())==v for k,v in f['consumed_inputs'].items()),'object_hash_verified':sha(b)==f['object_sha256'],'preprocessed_hash_verified':sha((G/'outputs'/(f['member']+'.s')).read_bytes())==f['preprocessed_sha256'],'dependencies_hash_verified':sha((G/'outputs'/(f['member']+'.d')).read_bytes())==f['dependency_sha256'],'archive_raw_text_identical':data==ab[ax[4]:ax[4]+ax[5]],'relocations_verified':[{'offset':off,'type':typ,'symbol':sym[0]} for off,typ,sym in rs]==f['relocations']})
b,ss,ns,sy=elf(G/'outputs/linked.elf');sections=[]
for f in g['sections']:
 x=ss[ns.index('.'+f['section'])];v=b[x[4]:x[4]+x[5]];a=int(f['address'],16);sections.append({'section':f['section'],'exact':v==stock(a,len(v)),'hash_verified':sha(v)==f['sha256']==f['stock_sha256'],'extent_verified':x[3]==a and len(v)==f['bytes']})
argv=n['argv'];mounts={v.split(':')[1]:Path(v.split(':')[0]) for i,v in enumerate(argv) if i and argv[i-1]=='-v'};nb,nss,nns,nsy=elf(N/'outputs/public.o');idx=nns.index('.text.memcpy');x=nss[idx];v=nb[x[4]:x[4]+x[5]];mem={'source_files_verified':all(sha((N/f['local']).read_bytes())==f['sha256'] and len((N/f['local']).read_bytes())==f['bytes'] for f in json.loads((N/'acquisition.json').read_text())['files']),'consumed_inputs_verified':all(sha((mounts['/'+k.split('/')[1]]/'/'.join(k.split('/')[2:])).read_bytes())==val for k,val in n['consumed_inputs'].items()),'object_hash_verified':sha(nb)==n['object_sha256'],'preprocessed_hash_verified':sha((N/'outputs/public.i').read_bytes())==n['preprocessed_sha256'],'exact_target':v==stock(0xaa2c,18),'text_hash_verified':sha(v)==n['source_text_sha256']==n['stock_text_sha256'],'extent_verified':len(v)==18,'no_relocations':not relocs(nb,nss,nns,nsy,idx)}
meta=R/'g2/analysis/source-discovery-parallel-2026-10-09/acquisitions/arm-gnu14-release-metadata';metadata='\n'.join(p.read_text() for p in meta.glob('*.md'));out={'official_metadata_gcc_pin_present':g['source_revision']in metadata,'official_metadata_newlib_pin_present':n['source_revision']in metadata,'gcc_source_provenance_hash_verified':sha((S/'provenance.json').read_bytes())==g['source_provenance_sha256'],'gcc_provenance_files_verified':all(sha((R/f['path']).read_bytes())==f['sha256'] for f in prov['files']),'GPL3_hash_verified':sha((S/'COPYING3').read_bytes())==g['GPL3_sha256'],'runtime_exception_hash_verified':sha((S/'COPYING.RUNTIME').read_bytes())==g['runtime_exception_3_1_sha256'],'gcc_providers':checks,'gcc_linked_sections':sections,'gcc_linked_elf_hash_verified':sha(b)==g['linked_elf_sha256'],'gcc_script_hash_verified':sha((G/'outputs/link.ld').read_bytes())==g['link_script_sha256'],'memcpy':mem,'division_repeated_byte_increment':0,'new_memcpy_dependency_bytes':18,'census_increment':0}
c=json.loads((N/'original-results.json').read_text());expected=set(itertools.product(range(4),range(4),[0,1,2,3,4,15,16,128]));out['memcpy_128_case_grid_consistent']=len(c['results'])==128 and {(f['source_alignment'],f['destination_alignment'],f['length']) for f in c['results']}==expected and all(f['byte_reads']==f['length']==f['byte_writes'] and f['return_pointer']==hex(0x20001200+f['destination_alignment']) and f['guards_and_saved_register_match'] for f in c['results']);(O/'RUNTIME-SOURCES-VERIFICATION.json').write_text(json.dumps(out,indent=2)+'\n')
def scan(v,path=''):
 if isinstance(v,dict):
  for k,x in v.items():
   if x is False:print(path+'.'+k)
   else:scan(x,path+'.'+k)
 elif isinstance(v,list):
  for i,x in enumerate(v):scan(x,path+f'[{i}]')
scan(out)
