from pathlib import Path
import json,struct,hashlib
R=Path.cwd();O=R/'g2/analysis/coverage-audit-parallel-2026-10-09';P=R/'g2/analysis/touch-systick14-literal-extents-2026-10-09';S=R/'g2/analysis/touch-pdl14-system-interface-2026-10-09';sha=lambda b:hashlib.sha256(b).hexdigest();r=json.loads((P/'results.json').read_text());sr=json.loads((S/'results.json').read_text());u=next(x for x in sr['units'] if x['source_unit']=='cy_systick.c');src=(O/'finite_verify.py').read_text();exec(src[src.index('def elf('):src.index('checks=[]')]);obj=S/'outputs/cy_systick.c/public.o';b,ss,ns,syms=elf(obj);fw=(R/'g2/blobs/official/g2-2.2.6.10/firmware_touch.bin').read_bytes();checks=[]
for f in r['functions']:
 a,end=map(lambda x:int(x,16),f['runtime_extent']);idx=ns.index('.text.'+f['function']);x=ss[idx];data=b[x[4]:x[4]+x[5]];stock=fw[f['absolute_payload_offset']:f['absolute_payload_offset']+len(data)];maps=sorted((v,n) for n,v,_,k in syms if k==idx and n.startswith(('$t','$d')));pool=next(v for v,n in maps if n.startswith('$d'));refs=[]
 for off in range(0,f['historical_code_bytes'],2):
  hw=struct.unpack_from('<H',stock,off)[0]
  if hw&0xf800==0x4800:
   dest=((a+off+4)&~3)+(hw&255)*4;refs.append({'instruction':hex(a+off),'literal':hex(dest),'value':hex(struct.unpack_from('<I',stock,dest-a)[0])})
 checks.append({'function':f['function'],'exact':data==stock,'full_hash_verified':sha(data)==f['sha256'],'coordinate_verified':f['absolute_payload_offset']==32+a-0x3300 and end-a==len(data),'mapping_symbols':maps,'alignment_verified':stock[f['historical_code_bytes']:pool].hex()==f['alignment_bytes'],'literal_verified':stock[pool:].hex()==f['literal_bytes']=='10e000e0','literal_refs_verified':refs==f['literal_references'],'instruction_bytes_verified':all(stock[int(i['address'],16)-a:int(i['address'],16)-a+len(bytes.fromhex(i['bytes']))].hex()==i['bytes'] for i in f['instructions']),'return_before_pool':stock[f['historical_code_bytes']-2:f['historical_code_bytes']].hex()=='7047','relocation_free':not any(t[1] in (4,9) and t[7]==idx for t in ss),'extent':[a,end]})
sel=json.loads((R/'g2/analysis/touch-pdl14-finite-census-2026-10-09/selection.json').read_text());overlaps=[(x['function'],f['function']) for x in checks for f in sel['functions'] if f['function']!=x['function'] and max(x['extent'][0],f['address'])<min(x['extent'][1],f['address']+f['historical_code_bytes'])];out={'object_hash_verified':sha(obj.read_bytes())==r['object_sha256']==u['output_hashes']['public.o'],'payload_hash_verified':sha(fw)==r['payload_sha256'],'retained_device_macro':'-DCY8C4046FNI_T412' in u['argv'],'configuration_receipt_previously_verified':'SYSTEM-INTERFACE-VERIFICATION.json','checks':checks,'selected_extent_overlaps':overlaps,'adjacent_nonoverlapping':checks[0]['extent'][1]==checks[1]['extent'][0],'new_bytes':48,'aggregate_bytes':2320+48,'aggregate_functions':23+2,'remaining_counts':{'relocation_extent':23,'absent':5,'inline':1}};(O/'SYSTICK-EXTENTS-VERIFICATION.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
