from pathlib import Path
import json,hashlib,subprocess,shutil
P=Path('g2/analysis/bootloader-completion-2026-10-06/inventory-worker/startup-initialize');OLDN=P/'startup-caller-root-native';N=P/'runtime-delay-native-integrated';N.mkdir(exist_ok=True);old=json.loads((OLDN/'current-candidate.json').read_text());OLD=Path(old['directory']);T=Path('/tmp/opencfw-runtime-delay-integrated');T.mkdir(exist_ok=True);C=Path('g2/components/bootloader/thread_creation/task_delay_native');C.mkdir(exist_ok=True);src=C/'task_delay.c';shutil.copy2(P.parent/'task-delay-native/task_delay.c',src);h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();flags=['--target=arm-none-eabi','-mcpu=cortex-m33','-mthumb','-mfloat-abi=softfp','-O1','-ffreestanding','-fno-builtin'];obj=T/'task_delay_native.o';subprocess.run(['clang',*flags,'-c',str(src),'-o',str(obj)],check=True);assert h(obj)==h('/tmp/opencfw-task-delay.o')
m=json.loads((OLD/'input-hashes.json').read_text());objs=[OLD/r['path'] for r in m['inputs']];assert all(h(OLD/r['path'])==r['sha256'] for r in m['inputs']);objs.append(obj);s=(OLD/'source/module.ld').read_text();assert s.count('opencfw_bl_task_delay = 0x416379;')==1;s=s.replace('opencfw_bl_task_delay = 0x416379;','opencfw_bl_task_delay = opencfw_cmsis_delay;');s=s.replace('  } :source_idle','    . = ALIGN(4);\n    KEEP(*task_delay_native.o(.text* .rodata*))\n  } :source_idle');ld=T/'module.ld';ld.write_text(s);elf=T/'candidate.elf';r=subprocess.run(['/opt/homebrew/bin/arm-none-eabi-ld','--gc-sections','-T',str(ld),'-o',str(elf),*[str(p) for p in objs]],capture_output=True,text=True);assert r.returncode==0,r.stderr;(N/'link.log').write_text(r.stderr);sha=h(elf);B=Path('g2/build/bootloader-completion/runtime-delay-native-integrated')/sha;B.mkdir(parents=True,exist_ok=True);shutil.copy2(elf,B/'candidate.elf');shutil.copytree(OLD/'source',B/'source',dirs_exist_ok=True);shutil.copy2(ld,B/'source/module.ld');shutil.copy2(src,B/'source/task_delay.c')
for r in m['inputs']:
 p=B/r['path'];p.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(OLD/r['path'],p)
p=B/'inputs/237/task_delay_native.o';p.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(obj,p);m['inputs'].append({'path':str(p.relative_to(B)),'original':str(obj),'sha256':h(obj)});m['elf_sha256']=sha;m['linked_objects']=238;(B/'input-hashes.json').write_text(json.dumps(m,indent=2)+'\n');(N/'current-candidate.json').write_text(json.dumps({'directory':str(B),'sha256':sha,'objects':238,'previous_sha256':old['sha256']},indent=2)+'\n');(N/'build-inputs.json').write_text(json.dumps({'flags':flags,'source':str(src),'source_sha256':h(src),'object_sha256':h(obj),'unit_object_equal':True},indent=2)+'\n');(B/'validation/regressions').mkdir(parents=True,exist_ok=True)
# Reuse successor-specific fixtures; their expected identity changes, observables do not.
for p in OLDN.glob('*.py'):
 if p.name in ['build.py','verify_caller_root.py']:continue
 z=p.read_text().replace(old['directory'],str(B)).replace(str(OLDN),str(N)).replace("'startup-caller-root-native'","'runtime-delay-native-integrated'").replace(old['sha256'],sha);(N/p.name).write_text(z)
for f in ['native-selector-bindings.json','initialized_data.c']:shutil.copy2(OLDN/f,N/f)
shutil.copy2(ld,N/'module.ld');(N/'build.py').write_bytes(Path('/tmp/opencfw-build-delay-integrated.py').read_bytes());print('built238',sha)
