from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47de7a;end=0x47df28
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-20937/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Helper result clamp and iterative unsigned extrema aggregation\n\nPartial/unaccepted;174instructionbytes47DE7A..47DF28,twoentries.\nDE7A PUSH R3,R4,R5,LR16;474550(entryR0,address47E140,liveR2,R3)→R4. Fullzero returns0. OtherwiseR5=0;474814(R4,0,2,liveR3);fullzero→474870(R4,liveargs)→R5;nonzero skips. Always4745F4(R4,liveargs). SignedR5<1→R5=0;otherwise unchanged. R0=R5;POP R1,R4,R5,PC,R1=savedentryR3. Thusnonpositivefullsignedresults clamp0;positivevalues retain32bits.\nDEB4 PUSH R3,R4,R5,LR16;R5=entryR0 outputrecord;43C0E4(R5,12,0,liveR3);word4=FFFFFFFF.474B02(literal47E29C,liveargs)→R4. Fullzero→R0=FFFFFFFB (-5),return. Otherwiseloop474BB8(R4,liveargs)→R2. Fullzero exitsloop:474C66(R4,liveargs),R0=0,return. Nonzero→freshunsignedbyte[R2+256];!=8 repeats. Equal8→47DE18(R2,SP,liveR2,R3). Fullzero repeats;fullnonzero incrementsfreshword0 modulo2^32. ReadSP0 valueandfreshword4;unsignedvalue<word4→independentlyreloadSP0thenstoreword4. Readfreshword8 and independentlySP0value;unsignedword8>=value→repeat;otherwiseindependentlyreloadSP0thenstoreword8 andrepeat. Distinctvalue observations cannotcollapse. No loopbound or calleecontract inferred. SP0 initiallysavedentryR3,becomesparsedvaluewhenDE18success writesit. POP R1,R4,R5,PCreturnsR1=SP0 subjecthelperwrites,restorespreservedregs. Countinitialization/word8initialvalue dependonunresolved43C0E4;onlyexplicitword4sentinelguaranteed locallyafterreturn. No C/freeze/completenessclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
