from pathlib import Path
import argparse,subprocess,json,hashlib
D=Path(__file__).resolve().parent;S=D.parent/'dependency-followup-2026-10-08/touch-source';p=argparse.ArgumentParser();p.add_argument('--gcc',type=Path,required=True);p.add_argument('--output',type=Path,required=True);p.add_argument('--callback-source',type=Path);p.add_argument('--with-publish',action='store_true');a=p.parse_args();a.output.mkdir(parents=True,exist_ok=True)
cbsource=a.callback_source or D/'app_event.c';pdl=S/'mtb-pdl-cat2-35f1714623cfea682d5e285af80d50416b4c7bbc';core=S/'core-lib-ca57d1e519e08badec6891d1776c7b4f05e09561';inc=['-I'+str(i) for i in [S,S/'cmsis',pdl/'drivers/include',pdl/'devices/include',core/'include']];flags=['-mcpu=cortex-m0plus','-mthumb','-Og','-fshort-enums','-ffreestanding','-fno-builtin','-DCY8C4046FNI_T412','-ffunction-sections'];objects=[]
sources=[(pdl/'drivers/source/cy_scb_i2c.c','i2c.o'),(pdl/'drivers/source/cy_scb_common.c','scb.o'),(cbsource,'app.o'),(pdl/'drivers/source/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy_syslib_gcc.S','asm.o')]
if a.with_publish:sources.append((D/'report_publish.c','publish.o'))
for src,name in sources:
 obj=a.output/name;subprocess.run([str(a.gcc),*flags,*inc,'-c',str(src),'-o',str(obj)],check=True);objects.append(obj)
elf=a.output/'app-event.elf';subprocess.run([str(a.gcc.with_name('arm-none-eabi-ld')),'--gc-sections','-Ttext=0x100000','-e','app_event','-u','Cy_SCB_I2C_SlaveInterrupt',*(['-u','touch_report_publish_slice'] if a.with_publish else []),*[str(i) for i in objects],'-o',str(elf)],check=True)
r=dict(elf_sha256=hashlib.sha256(elf.read_bytes()).hexdigest(),objects={i.name:hashlib.sha256(i.read_bytes()).hexdigest() for i in objects},source_sha256=hashlib.sha256(cbsource.read_bytes()).hexdigest(),compiler=subprocess.check_output([str(a.gcc),'--version'],text=True).splitlines()[0],flags=flags,publish_source_sha256=hashlib.sha256((D/'report_publish.c').read_bytes()).hexdigest() if a.with_publish else None,public_source_provenance='../dependency-followup-2026-10-08/source-provenance.json',limits='Independent callback covers only commands0,1,3 or>=9; public helper code is a tested comparator, not exact firmware reconstruction.')
(a.output/'receipt.json').write_text(json.dumps(r,indent=2)+'\n');print('Built bounded callback/public-driver ELF',r['elf_sha256'])
