from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x4809c4;end=0x480a32
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21141/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Low-byte dispatch and first two word modes\n\nPartial/unaccepted;110 instruction bytes4809C4..480A32. PUSH R3,R4,R5,LR16;R4=entryR1 pointer;R0=UXTB(entryR0). Exact dispatch:0→4809E8,1→480A1C,2→480A32,3→480AD4,4→480B66,5→480BC2,6→480C2E,7..255→480C52. Other branches unresolved here.\n\nMode0: R0=pointer from literal480EB0; fresh word[R0] stored SP0 (overwriting saved entryR3). ReloadSP0 and clear low5bits via logical right5 then left5; storeSP0. If R4nonnull, read byte[R4]; if byte exactly1, reloadSP0 OR5 and storeSP0; otherwise (including null) reloadSP0 OR25 decimal and storeSP0. ReloadSP0 then store word[R0]. ReturnR0=0 at480A18;POP R1,R4,R5,PC releases16, R1 receives final scratchSP0 value, not entryR3. Only one initial source word read; no late reread before write. Preserve scratch loads/stores for aliasing with passed pointer and memory.\n\nMode1: load same literal pointer, fresh word storedSP0, reload and clear low2bits via logical right2 then left2, storeSP0; reloadSP0 and write sourceword. Branch480A18 returns0 with same POP/R1 scratch behavior. R4 not dereferenced. No helpercalls, nullguard for word pointer, physical semantics, C/freeze/fullcoverage/equality claim. Remaining dispatch arms require recovery.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
