// Seed exact Thumb function entries from a whole-image inventory CSV.
// The CSV is analysis evidence generated by R1WholeImageExport, not a name source.
// @category Firmware

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.math.BigInteger;

import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.lang.Register;
import ghidra.program.model.listing.Function;

public class R1SeedFunctionsFromCsv extends GhidraScript {
    @Override
    public void run() throws Exception {
        String[] arguments = getScriptArgs();
        if (arguments.length != 1) {
            throw new IllegalArgumentException("expected absolute functions.csv path");
        }
        File input = new File(arguments[0]);
        if (!input.isAbsolute() || !input.isFile()) {
            throw new IllegalArgumentException("functions.csv must exist and be absolute");
        }

        Register tMode = currentProgram.getRegister("TMode");
        int requested = 0;
        int created = 0;
        try (BufferedReader reader = new BufferedReader(new FileReader(input))) {
            String line = reader.readLine();
            if (line == null || !line.startsWith("entry,")) {
                throw new IllegalArgumentException("unexpected functions.csv header");
            }
            while ((line = reader.readLine()) != null) {
                int comma = line.indexOf(',');
                if (comma <= 0) {
                    continue;
                }
                long raw = Long.decode(line.substring(0, comma));
                Address address = toAddr(raw);
                requested++;
                if (tMode != null && getInstructionAt(address) == null) {
                    currentProgram.getProgramContext().setValue(
                        tMode, address, address, BigInteger.ONE
                    );
                }
                disassemble(address);
                Function function = getFunctionAt(address);
                if (function == null) {
                    function = createFunction(address, null);
                    if (function != null) {
                        created++;
                    }
                }
            }
        }
        println("R1_FUNCTION_CSV_SEED requested=" + requested + " created=" + created);
    }
}
