from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x484a7e;end=0x484b16
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21463/fresh';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Ordered helper pair and three-byte field initialization prefix\n\nPartial/unaccepted. Exact 152-byte span 484A7E..484B16. Wrapper at 484A7E saves R3,R4,R5,LR (16B), retains entry R0/R1 in R4/R5, calls 4D4892 then 4D489E with R0=R4,R1=R5 before each and live R2/R3; POP R0 returns saved entry R3. Zero halfword 484A96..484A98 is inter-function data/padding.\n\n484A98 opens a 32B frame saving entry R1..R7 and LR; R4 retains object. For each field, freshly read object byte+36 bit0 to select the value helper, store returned R0 at SP0 (overwriting saved entry R1), then call 439BE4(destination,SP,3), copying the low three bytes of the stack word on this little-endian image; copy-helper full contract remains unresolved.\n\nField +48: bit0 set calls 44104C with R0=word at literal48547C; bit0 clear calls 4882D2(18,4,live R2,R3). Field +51: bit0 set calls 4882D2(18,5,live R2,R3); clear calls 48834C(18,4,live R2,R3). Field +54: bit0 set calls 44104C with R0=word at literal485480; clear calls 441094 with R0 still zero from the preceding flag shift, and other registers live from prior copy. Each copy sets R2=3 and R1=SP. Prefix ends after third copy, frame still open; continuation and final return remain separate. Referenced literal words recorded in references.json. No C, freeze, whole coverage or equality claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
