from pathlib import Path
import json,hashlib,subprocess,shutil
R=Path.cwd();P=Path('g2/analysis/bootloader-completion-2026-10-06/inventory-worker/startup-initialize');N=P/'iar-format-native-integrated';N.mkdir(exist_ok=True);C=Path('g2/components/bootloader/initializer_callbacks/iar_format_native');T=Path('/tmp/opencfw-iar-format-integrated');T.mkdir(exist_ok=True);OLD=Path('g2/build/bootloader-completion/bounded-format-native/0b80d612fe52fd296eae01d1e304daf8769df2a6847f8649ebfe787c3108d419');h=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();old=json.loads((OLD/'input-hashes.json').read_text()); objects=[]
for i,row in enumerate(old['inputs']):
 src=OLD/row['path'];assert h(src)==row['sha256'];dst=T/'inputs'/str(i)/Path(row['original']).name;dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(src,dst);objects.append(dst)
flags=['--target=arm-none-eabi','-mcpu=cortex-m33','-mthumb','-mfloat-abi=softfp','-mfpu=fpv5-d16','-O2','-ffreestanding','-fno-builtin'];new=[]
for name in ['engine','entry','termination','fp_primitives','float_render','format_parser','integer_cursor','integer_render']:
 src=C/(name+'.c');dst=T/(name+'.o');subprocess.run(['clang',*flags,'-c',str(src),'-o',str(dst)],check=True);objects.append(dst);new.append({'source':str(src),'source_sha256':h(src),'object':str(dst),'object_sha256':h(dst)})
s=(OLD/'source/module.ld').read_text();assert s.count('opencfw_boot_format_engine = 0x41e47b;')==1;s=s.replace('opencfw_boot_format_engine = 0x41e47b;','opencfw_boot_format_engine = opencfw_iar_format_engine;'); insert='\n    . = ALIGN(4);\n'+''.join('    KEEP(*'+p.name+'(.text* .rodata*))\n' for p in objects[-8:]);s=s.replace('  } :source_idle',insert+'  } :source_idle');ld=T/'module.ld';ld.write_text(s);elf=T/'candidate.elf';subprocess.run(['/opt/homebrew/bin/arm-none-eabi-ld','--gc-sections','-T',str(ld),'-o',str(elf),*[str(p) for p in objects]],check=True);sha=h(elf);B=Path('g2/build/bootloader-completion/iar-format-native-integrated')/sha;B.mkdir(parents=True,exist_ok=True);shutil.copy2(elf,B/'candidate.elf');(B/'source').mkdir(exist_ok=True);shutil.copy2(ld,B/'source/module.ld');inputs=[]
for i,obj in enumerate(objects):
 dest=B/'inputs'/str(i)/obj.name;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(obj,dest);inputs.append({'path':str(dest.relative_to(B)),'original':str(obj),'sha256':h(obj)})
(B/'input-hashes.json').write_text(json.dumps({'elf_sha256':sha,'linked_objects':len(objects),'inputs':inputs},indent=2)+'\n');(N/'current-candidate.json').write_text(json.dumps({'directory':str(B),'sha256':sha,'objects':len(objects)},indent=2)+'\n');(N/'build-inputs.json').write_text(json.dumps({'flags':flags,'new_sources':new,'previous_candidate':old['elf_sha256'],'sources':{str(p):h(p) for p in C.iterdir() if p.suffix in ['.c','.h']},'linker_sha256':h(ld)},indent=2)+'\n');print('built',len(objects),sha)
