#!/bin/bash
# RTOS function identification — sed commands for function_map.txt
# Generated by decompiled code analysis against FreeRTOS v10.5 + CMSIS-RTOS2 + ARM AEABI
# Only confident SDK matches included.
#
# Usage: cd to the directory containing function_map.txt, then run this script.
# Or: bash rtos_sed_commands.sh

FILE="function_map.txt"
cd "$(dirname "$0")"

# ============================================================================
# CMSIS Core Atomic Primitives (cmsis_gcc.h / cmsis_armclang.h)
# These use LDREX/STREX (ExclusiveAccess/hasExclusiveAccess) + DMB instructions.
# Reference: CMSIS-Core cmsis_compiler.h atomic intrinsics
# ============================================================================

# FUN_004470b4: DMB(0x1f) then loads *param_1 — textbook atomic_load
sed -i '' "s|^0x004470b4\t.*|0x004470b4\tFUN_004470b4\tatomic_load_u32\trtos.cmsis_core\tHIGH\t# CMSIS core: DMB + load word (atomic_load pattern)|" "$FILE"

# FUN_004470bc: LDREX/STREX CAS loop with DMB — atomic compare-and-swap
sed -i '' "s|^0x004470bc\t.*|0x004470bc\tFUN_004470bc\tatomic_compare_exchange_u32\trtos.cmsis_core\tHIGH\t# CMSIS core: LDREX/STREX CAS loop + DMB|" "$FILE"

# FUN_004470f0: calls FUN_004470ac (store+DMB) — store with release semantics
sed -i '' "s|^0x004470f0\t.*|0x004470f0\tFUN_004470f0\tatomic_store_release\trtos.cmsis_core\tHIGH\t# CMSIS core: wrapper calling atomic store (FUN_004470ac)|" "$FILE"

# FUN_004470f8: calls FUN_004470b4 (load+DMB) — load with acquire semantics
sed -i '' "s|^0x004470f8\t.*|0x004470f8\tFUN_004470f8\tatomic_load_acquire\trtos.cmsis_core\tHIGH\t# CMSIS core: wrapper calling atomic load (FUN_004470b4)|" "$FILE"

# FUN_00447100: wraps atomic_compare_exchange_u32, returns old val + success flag
sed -i '' "s|^0x00447100\t.*|0x00447100\tFUN_00447100\tatomic_compare_exchange_weak\trtos.cmsis_core\tHIGH\t# CMSIS core: CAS wrapper returning old value + success flag|" "$FILE"

# ============================================================================
# Lock-Free Data Structures (Ambiq SDK / FreeRTOS extension)
# Pool allocator + queue using CAS loops with retry limits.
# ============================================================================

# FUN_0044711e: initializes 0xFE-entry pool of 0x110-byte blocks
sed -i '' "s|^0x0044711e\t.*|0x0044711e\tFUN_0044711e\tlockfree_pool_init\trtos\tHIGH\t# Lock-free pool init: 0xFE entries x 0x110 bytes, uses atomic store|" "$FILE"

# FUN_004471a8: initializes free-list head/tail pointers
sed -i '' "s|^0x004471a8\t.*|0x004471a8\tFUN_004471a8\tlockfree_freelist_init\trtos\tHIGH\t# Lock-free free-list init: sets head + tail pointers|" "$FILE"

# FUN_004471cc: CAS-loop alloc (1000 retry limit), returns block pointer
sed -i '' "s|^0x004471cc\t.*|0x004471cc\tFUN_004471cc\tlockfree_pool_alloc\trtos\tHIGH\t# Lock-free pool alloc: CAS loop with 1000 retry limit|" "$FILE"

# FUN_0044724e: CAS-loop free (1000 retry limit), returns block to pool
sed -i '' "s|^0x0044724e\t.*|0x0044724e\tFUN_0044724e\tlockfree_pool_free\trtos\tHIGH\t# Lock-free pool free: CAS loop with 1000 retry limit|" "$FILE"

# FUN_004472b0: CAS-loop FIFO enqueue (10000 retry), sets status byte = 2
sed -i '' "s|^0x004472b0\t.*|0x004472b0\tFUN_004472b0\tlockfree_queue_enqueue\trtos\tHIGH\t# Lock-free queue enqueue: CAS loop with 10000 retry limit|" "$FILE"

# FUN_00447356: CAS-loop FIFO dequeue (10000 retry), copies data from head
sed -i '' "s|^0x00447356\t.*|0x00447356\tFUN_00447356\tlockfree_queue_dequeue\trtos\tHIGH\t# Lock-free queue dequeue: CAS loop with 10000 retry limit, copies data|" "$FILE"

# FUN_00447434: one-time init guard (checks flag, calls pool_init + freelist_init + clear stats)
sed -i '' "s|^0x00447434\t.*|0x00447434\tFUN_00447434\tlockfree_subsystem_init\trtos\tHIGH\t# Lock-free subsystem one-time init: pool + freelist + statistics|" "$FILE"

# ============================================================================
# CMSIS-RTOS2 Kernel + Timer + Event API (cmsis_os2.h wrappers over FreeRTOS)
# ============================================================================

# FUN_00447800: checks ISR (FUN_004477a2), checks state==1, sets state=2, calls vTaskStartScheduler
sed -i '' "s|^0x00447800\t.*|0x00447800\tFUN_00447800\tosKernelStart\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: checks ISR ctx + state==osKernelReady, sets osKernelRunning, calls vTaskStartScheduler|" "$FILE"

# FUN_00447aea: gets callback ptr from FreeRTOS timer ID, invokes callback(arg)
sed -i '' "s|^0x00447aea\t.*|0x00447aea\tFUN_00447aea\tosTimerCallback_dispatch\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: retrieves callback+arg from timer ID via pvTimerGetTimerID, invokes callback|" "$FILE"

# FUN_00447c2a: checks ISR, calls xTimerIsTimerActive, then xTimerChangePeriod with action=3 (stop)
sed -i '' "s|^0x00447c2a\t.*|0x00447c2a\tFUN_00447c2a\tosTimerStop\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: osTimerStop — checks ISR ctx, validates timer, sends stop command|" "$FILE"

# FUN_00447c74: checks ISR, reads xTimerIsTimerActive
sed -i '' "s|^0x00447c74\t.*|0x00447c74\tFUN_00447c74\tosTimerIsRunning\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: osTimerIsRunning — checks ISR ctx + xTimerIsTimerActive flag|" "$FILE"

# FUN_00447dec: validates handle, checks ISR, calls xEventGroupSetBits/WaitBits with flags
sed -i '' "s|^0x00447dec\t.*|0x00447dec\tFUN_00447dec\tosEventFlagsWait\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: osEventFlagsWait — handles osFlagsWaitAll/osFlagsWaitAny + osFlagsNoClear|" "$FILE"

# FUN_00448f16: calls osEventFlagsSet on global event flags handle
sed -i '' "s|^0x00448f16\t.*|0x00448f16\tFUN_00448f16\tosEventFlagsSet_dispatch\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: thin wrapper calling osEventFlagsSet on global event group|" "$FILE"

# FUN_0059a482: periodic task pattern — counter < limit check, event flags wait, timer start
sed -i '' "s|^0x0059a482\t.*|0x0059a482\tFUN_0059a482\tosTimerPeriodic_handler\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: periodic timer handler — checks counter, waits event flags, starts timer|" "$FILE"

# FUN_004b4288: checks osTimerIsRunning, calls osTimerStop, calls app restart callback
sed -i '' "s|^0x004b4288\t.*|0x004b4288\tFUN_004b4288\tosTimer_check_and_restart\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: checks timer active, stops + calls restart callback|" "$FILE"

# FUN_004b42ac: calls osTimerStart with 4000ms period
sed -i '' "s|^0x004b42ac\t.*|0x004b42ac\tFUN_004b42ac\tosTimerStart_4s\trtos.cmsis\tHIGH\t# CMSIS-RTOS2: starts CMSIS timer with 4000ms period via osTimerStart|" "$FILE"

# ============================================================================
# FreeRTOS Port Layer (port.c / portmacro.h for ARM Cortex-M55 / Apollo510)
# ============================================================================

# FUN_00441134: reads basepri, enters infinite loop — configASSERT failure handler
sed -i '' "s|^0x00441134\t.*|0x00441134\tFUN_00441134\tconfigASSERT_handler\trtos.freertos\tHIGH\t# FreeRTOS port: configASSERT failure — enters critical section + infinite loop|" "$FILE"

# FUN_0044115e: sets CPACR bits (0xF00000) and FPCCR bits (0xC0000000) for FPU access
sed -i '' "s|^0x0044115e\t.*|0x0044115e\tFUN_0044115e\tvPortEnableVFP\trtos.freertos\tHIGH\t# FreeRTOS port: enables FPU — sets CPACR CP10+CP11 full access + FPCCR ASPEN+LSPEN|" "$FILE"

# FUN_0044129a: enables all IRQ masks, sets nesting=0, calls vPortStartFirstTask + SysTick setup
sed -i '' "s|^0x0044129a\t.*|0x0044129a\tFUN_0044129a\txPortStartScheduler\trtos.freertos\tHIGH\t# FreeRTOS port: xPortStartScheduler — enables IRQ, nesting=0, SysTick setup, SVC start|" "$FILE"

# FUN_005d6c90: SVC handler entry (Ghidra can't decode SVC entry — shows bad instruction)
sed -i '' "s|^0x005d6c90\t.*|0x005d6c90\tFUN_005d6c90\tvPortSVCHandler\trtos.freertos\tHIGH\t# FreeRTOS port: SVC exception handler entry (Ghidra shows bad instruction data)|" "$FILE"

# FUN_005d6cc4: sets MSP from vector table[0], enables IRQ+FIQ, DSB+ISB, SVC #2
sed -i '' "s|^0x005d6cc4\t.*|0x005d6cc4\tFUN_005d6cc4\tvPortStartFirstTask\trtos.freertos\tHIGH\t# FreeRTOS port: sets MSP, enables IRQ+FIQ, DSB+ISB, triggers SVC#2 to start first task|" "$FILE"

# FUN_004411ec: checks EXC_RETURN mode byte at *(*(param_1+0x18)-2)==0x02, then enables VFP + SVC
sed -i '' "s|^0x004411ec\t.*|0x004411ec\tFUN_004411ec\tprvRestoreContextOfFirstTask\trtos.freertos\tHIGH\t# FreeRTOS port: checks EXC_RETURN SPSEL, enables VFP, triggers SVC for context restore|" "$FILE"

# ============================================================================
# FreeRTOS tasks.c (core scheduler functions)
# ============================================================================

# FUN_00452f78: creates idle task (xTaskCreateStatic), sets xTickCount=-1, calls xPortStartScheduler
sed -i '' "s|^0x00452f78\t.*|0x00452f78\tFUN_00452f78\tvTaskStartScheduler\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: creates idle task, sets xTickCount=portMAX_DELAY, calls xPortStartScheduler|" "$FILE"

# FUN_00452dd8: checks scheduler not suspended, calls vTaskSuspendAll + dispatch + xTaskResumeAll
sed -i '' "s|^0x00452dd8\t.*|0x00452dd8\tFUN_00452dd8\tvTaskPriorityDisinheritAfterTimeout\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: disinherits mutex priority, suspends/resumes all, may yield|" "$FILE"

# FUN_00453264: adds param_1 to tick count, handles pended ready list in critical section
sed -i '' "s|^0x00453264\t.*|0x00453264\tFUN_00453264\txTaskIncrementTick\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: increments tick count by param_1, handles pended ready list|" "$FILE"

# FUN_004532d8: inner tick processing — increments tick, swaps delayed lists on overflow, unblocks tasks
sed -i '' "s|^0x004532d8\t.*|0x004532d8\tfun_004532d8\txTaskIncrementTick_inner\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: inner tick handler — delayed list processing, overflow swap, unblock|" "$FILE"

# ============================================================================
# ARM CMSIS NVIC intrinsics (core_cm55.h)
# ============================================================================

# FUN_00454308: writes (1 << IRQn) to NVIC->ISPR[(IRQn >> 5)] — sets pending IRQ
sed -i '' "s|^0x00454308\t.*|0x00454308\tFUN_00454308\tNVIC_SetPendingIRQ\trtos.cmsis_core\tHIGH\t# ARM CMSIS: NVIC_SetPendingIRQ — sets ISPR bit for IRQ number|" "$FILE"

# FUN_00454324: writes (1 << IRQn) to NVIC->ICPR[(IRQn >> 5)] — clears pending IRQ
sed -i '' "s|^0x00454324\t.*|0x00454324\tFUN_00454324\tNVIC_ClearPendingIRQ\trtos.cmsis_core\tHIGH\t# ARM CMSIS: NVIC_ClearPendingIRQ — clears ICPR bit for IRQ number|" "$FILE"

# FUN_00454340: writes (priority << 4) to NVIC->IPR[IRQn] or SCB->SHP for system handlers
sed -i '' "s|^0x00454340\t.*|0x00454340\tFUN_00454340\tNVIC_SetPriority\trtos.cmsis_core\tHIGH\t# ARM CMSIS: NVIC_SetPriority — sets IPR/SHP priority (handles negative=system handler)|" "$FILE"

# FUN_004543ee: sets SysTick reload=0x20, enables timer + compare, sets priority=0xFF
sed -i '' "s|^0x004543ee\t.*|0x004543ee\tFUN_004543ee\txPortSetupTimerInterrupt\trtos.freertos\tHIGH\t# FreeRTOS port: configures STIMER as tick source, sets IRQ priority, enables compare match|" "$FILE"

# ============================================================================
# FreeRTOS timers.c (software timer service)
# ============================================================================

# FUN_0047686a: stores callback, period, autoReload flag, sets count=0 in timer CB
sed -i '' "s|^0x0047686a\t.*|0x0047686a\tFUN_0047686a\tprvInitialiseNewTimer\trtos.freertos\tHIGH\t# FreeRTOS timers.c: initializes timer control block (callback, period, auto-reload)|" "$FILE"

# FUN_00476c5a: builds message with cmd=-2 (tmrCOMMAND_EXECUTE_CALLBACK), sends to timer queue
sed -i '' "s|^0x00476c5a\t.*|0x00476c5a\tFUN_00476c5a\txTimerPendFunctionCall\trtos.freertos\tHIGH\t# FreeRTOS timers.c: pends function call on timer queue (cmd=0xFFFFFFFE)|" "$FILE"

# FUN_00476784: creates timer service task at priority 0x36 via xTaskCreateStatic
sed -i '' "s|^0x00476784\t.*|0x00476784\tFUN_00476784\tprvCheckForValidListAndQueue\trtos.freertos\tHIGH\t# FreeRTOS timers.c: creates timer service task (priority=0x36) if not already created|" "$FILE"

# FUN_00476bc8: initializes two timer lists + creates timer command queue (0x32 items x 0x10 bytes)
sed -i '' "s|^0x00476bc8\t.*|0x00476bc8\tFUN_00476bc8\tprvInitialiseTimerLists\trtos.freertos\tHIGH\t# FreeRTOS timers.c: initializes active+overflow timer lists + creates command queue|" "$FILE"

# FUN_00476c06: reads ucStatus bit 0 at offset +0x28 in critical section
sed -i '' "s|^0x00476c06\t.*|0x00476c06\tFUN_00476c06\txTimerIsTimerActive\trtos.freertos\tHIGH\t# FreeRTOS timers.c: returns (ucStatus & tmrSTATUS_IS_ACTIVE) in critical section|" "$FILE"

# FUN_00476922: loops calling prvInsertTimerInActiveList + callback for auto-reload timers
sed -i '' "s|^0x00476922\t.*|0x00476922\tFUN_00476922\tprvReloadTimer\trtos.freertos\tHIGH\t# FreeRTOS timers.c: reloads auto-reload timer, calls callback in loop|" "$FILE"

# FUN_0047694a: gets head of active list, removes it, checks auto-reload flag, calls callback
sed -i '' "s|^0x0047694a\t.*|0x0047694a\tFUN_0047694a\tprvProcessExpiredTimer\trtos.freertos\tHIGH\t# FreeRTOS timers.c: processes single expired timer from active list head|" "$FILE"

# FUN_00476988: infinite loop — prvGetNextExpireTime, prvProcessReceivedCommands, process expired
sed -i '' "s|^0x00476988\t.*|0x00476988\tFUN_00476988\tprvTimerTask\trtos.freertos\tHIGH\t# FreeRTOS timers.c: timer daemon task entry — infinite service loop|" "$FILE"

# FUN_00476a02: checks if active list is empty, returns head item value (next expiry tick)
sed -i '' "s|^0x00476a02\t.*|0x00476a02\tFUN_00476a02\tprvGetNextExpireTime\trtos.freertos\tHIGH\t# FreeRTOS timers.c: returns next expiry tick from active timer list (0 if empty)|" "$FILE"

# FUN_00476a26: calls xTaskGetTickCount, detects overflow vs last sample, sets overflow flag
sed -i '' "s|^0x00476a26\t.*|0x00476a26\tFUN_00476a26\tprvSampleTimeNow\trtos.freertos\tHIGH\t# FreeRTOS timers.c: samples tick count, sets overflow flag if counter wrapped|" "$FILE"

# FUN_00476a4c: sets timer value, inserts into sorted list (active or overflow)
sed -i '' "s|^0x00476a4c\t.*|0x00476a4c\tFUN_00476a4c\tprvInsertTimerInActiveList\trtos.freertos\tHIGH\t# FreeRTOS timers.c: inserts timer into active or overflow list based on expiry|" "$FILE"

# FUN_00476a8a: receives from queue, dispatches start/stop/change/delete/callback commands
sed -i '' "s|^0x00476a8a\t.*|0x00476a8a\tFUN_00476a8a\tprvProcessReceivedCommands\trtos.freertos\tHIGH\t# FreeRTOS timers.c: processes timer commands from queue (start/stop/change/delete)|" "$FILE"

# FUN_00476ba0: processes all expired timers in active list, then swaps active<->overflow
sed -i '' "s|^0x00476ba0\t.*|0x00476ba0\tFUN_00476ba0\tprvSwitchTimerLists\trtos.freertos\tHIGH\t# FreeRTOS timers.c: fires all expired timers then swaps active and overflow lists|" "$FILE"

# ============================================================================
# FreeRTOS queue.c (queues, semaphores, mutexes)
# ============================================================================

# FUN_00477338: sets storage pointer (or self-ref if no items), item_size, length, calls xQueueGenericReset
sed -i '' "s|^0x00477338\t.*|0x00477338\tFUN_00477338\tprvInitialiseNewQueue\trtos.freertos\tHIGH\t# FreeRTOS queue.c: initializes queue fields (storage, item_size, length) + reset|" "$FILE"

# FUN_0047735a: resets 3 queue fields to 0, calls thread_mgmt(queue, 0, 0, 0)
sed -i '' "s|^0x0047735a\t.*|0x0047735a\tFUN_0047735a\txQueueCreateMutex\trtos.freertos\tHIGH\t# FreeRTOS queue.c: creates mutex — resets queue state + initializes holder|" "$FILE"

# FUN_004771b8: resets pcHead/pcTail/pcReadFrom/pcWriteTo, uxMessagesWaiting=0, wait lists
sed -i '' "s|^0x004771b8\t.*|0x004771b8\tFUN_004771b8\txQueueGenericReset\trtos.freertos\tHIGH\t# FreeRTOS queue.c: resets queue pointers, message count=0, reinitializes wait lists|" "$FILE"

# FUN_00477c00: advances pcReadFrom circularly, copies item_size bytes to destination
sed -i '' "s|^0x00477c00\t.*|0x00477c00\tFUN_00477c00\tprvCopyDataFromQueue\trtos.freertos\tHIGH\t# FreeRTOS queue.c: copies item from circular buffer, advances read pointer|" "$FILE"

# FUN_00477c2a: unblocks tasks on xTasksWaitingToSend + xTasksWaitingToReceive, sets lock=-1
sed -i '' "s|^0x00477c2a\t.*|0x00477c2a\tFUN_00477c2a\tprvUnlockQueue\trtos.freertos\tHIGH\t# FreeRTOS queue.c: unblocks waiting tasks on both send+receive lists, resets locks to -1|" "$FILE"

# FUN_00477c98: enters critical, checks uxMessagesWaiting==0, exits critical
sed -i '' "s|^0x00477c98\t.*|0x00477c98\tFUN_00477c98\txQueueIsQueueEmptyFromISR\trtos.freertos\tHIGH\t# FreeRTOS queue.c: checks uxMessagesWaiting==0 in critical section|" "$FILE"

# FUN_00477cb4: enters critical, checks uxMessagesWaiting==uxLength, exits critical
sed -i '' "s|^0x00477cb4\t.*|0x00477cb4\tFUN_00477cb4\txQueueIsQueueFullFromISR\trtos.freertos\tHIGH\t# FreeRTOS queue.c: checks uxMessagesWaiting==uxLength in critical section|" "$FILE"

# FUN_00477cd2: initializes lock counters, sends to xSemaphoreAcquire, calls prvUnlockQueue
sed -i '' "s|^0x00477cd2\t.*|0x00477cd2\tFUN_00477cd2\txQueueGenericSend\trtos.freertos\tHIGH\t# FreeRTOS queue.c: generic queue send — lock, copy, unlock, may yield|" "$FILE"

# FUN_004773b2: checks xTaskGetCurrentTaskHandle==holder, decrements recursive count, gives at 0
sed -i '' "s|^0x004773b2\t.*|0x004773b2\tFUN_004773b2\txQueueGiveMutexRecursive\trtos.freertos\tHIGH\t# FreeRTOS queue.c: recursive mutex give — decrements count, full give when count reaches 0|" "$FILE"

# FUN_004778e6: complex queue receive with timeout, mutex priority inheritance
sed -i '' "s|^0x004778e6\t.*|0x004778e6\tFUN_004778e6\txQueueSemaphoreTake\trtos.freertos\tHIGH\t# FreeRTOS queue.c: semaphore take with timeout + mutex priority inheritance|" "$FILE"

# ============================================================================
# FreeRTOS heap_4.c
# ============================================================================

# FUN_00476da4: clears allocated bit, adds freed bytes to counter, calls prvInsertBlockIntoFreeList
sed -i '' "s|^0x00476da4\t.*|0x00476da4\tFUN_00476da4\tvPortFree\trtos.heap\tHIGH\t# FreeRTOS heap_4.c: frees block, updates free byte count, coalesces into free list|" "$FILE"

# ============================================================================
# FreeRTOS Application Hooks
# ============================================================================

# FUN_004864a8: returns static TCB buffer, static stack buffer, stack size=0x400
sed -i '' "s|^0x004864a8\t.*|0x004864a8\tFUN_004864a8\tvApplicationGetIdleTaskMemory\trtos.freertos\tHIGH\t# FreeRTOS: vApplicationGetIdleTaskMemory — returns static TCB + stack (0x400 words)|" "$FILE"

# ============================================================================
# Ambiq Apollo510 HAL (NOT RTOS — reclassify to hal.ambiq)
# These are hardware timer/clock register operations on the Apollo510 SoC.
# ============================================================================

# FUN_004864c0: maps clock source enum {1,2}->4, {6}->0, else->7
sed -i '' "s|^0x004864c0\t.*|0x004864c0\tFUN_004864c0\tam_hal_stimer_clk_prescaler\thal.ambiq\tHIGH\t# Ambiq HAL: maps STIMER clock source to prescaler value|" "$FILE"

# FUN_004864d8: configures clock enables with sequencing delays, returns old config
sed -i '' "s|^0x004864d8\t.*|0x004864d8\tFUN_004864d8\tam_hal_stimer_config\thal.ambiq\tHIGH\t# Ambiq HAL: configures STIMER clock source with enable/disable sequencing|" "$FILE"

# FUN_004865a4: reads 64-bit STIMER counter register (coherent double-read pattern)
sed -i '' "s|^0x004865a4\t.*|0x004865a4\tFUN_004865a4\tam_hal_stimer_counter_get\thal.ambiq\tHIGH\t# Ambiq HAL: reads 64-bit STIMER counter with coherent double-read|" "$FILE"

# FUN_004865c0: sets STIMER compare register with race-avoidance spin
sed -i '' "s|^0x004865c0\t.*|0x004865c0\tFUN_004865c0\tam_hal_stimer_compare_delta_set\thal.ambiq\tHIGH\t# Ambiq HAL: sets STIMER compare register with race-avoidance loop|" "$FILE"

# FUN_0048662c: ORs enable mask into STIMER interrupt enable register
sed -i '' "s|^0x0048662c\t.*|0x0048662c\tFUN_0048662c\tam_hal_stimer_int_enable\thal.ambiq\tHIGH\t# Ambiq HAL: enables STIMER interrupt by OR-ing mask into enable register|" "$FILE"

# ============================================================================
# ARM AEABI Compiler Runtime (NOT RTOS — reclassify to compiler_rt)
# These are compiler-generated floating-point helper functions.
# ============================================================================

# FUN_004cdd30: checks if double operands are NaN/infinity
sed -i '' "s|^0x004cdd30\t.*|0x004cdd30\tFUN_004cdd30\t__aeabi_dcmpun_helper\tcompiler_rt\tHIGH\t# ARM AEABI: double NaN/infinity validity check|" "$FILE"

# FUN_004cdd64: float-to-double conversion wrapper
sed -i '' "s|^0x004cdd64\t.*|0x004cdd64\tFUN_004cdd64\t__aeabi_f2d_wrapper\tcompiler_rt\tHIGH\t# ARM AEABI: float-to-double conversion via ldexp|" "$FILE"

# FUN_004cdd78: ldexp — scale double by power of 2 (handles denormals, overflow)
sed -i '' "s|^0x004cdd78\t.*|0x004cdd78\tFUN_004cdd78\tldexp\tcompiler_rt\tHIGH\t# C runtime: ldexp — scales double by integer power of 2|" "$FILE"

# FUN_004cde68: double-to-signed-int truncation via VectorFloatToSigned
sed -i '' "s|^0x004cde68\t.*|0x004cde68\tFUN_004cde68\t__aeabi_d2iz\tcompiler_rt\tHIGH\t# ARM AEABI: double to signed int truncation (VCVT.S32.F64)|" "$FILE"

# FUN_004cde76: signed-int-to-double conversion via VectorSignedToFloat
sed -i '' "s|^0x004cde76\t.*|0x004cde76\tFUN_004cde76\t__aeabi_i2d\tcompiler_rt\tHIGH\t# ARM AEABI: signed int to double conversion (VCVT.F64.S32)|" "$FILE"

# FUN_004cde84: double subtraction (dsub)
sed -i '' "s|^0x004cde84\t.*|0x004cde84\tFUN_004cde84\t__aeabi_dsub\tcompiler_rt\tHIGH\t# ARM AEABI: double subtraction|" "$FILE"

# FUN_004cde96: double division (ddiv)
sed -i '' "s|^0x004cde96\t.*|0x004cde96\tFUN_004cde96\t__aeabi_ddiv\tcompiler_rt\tHIGH\t# ARM AEABI: double division|" "$FILE"

# FUN_004cdea8: double-to-unsigned-int truncation via VectorFloatToUnsigned
sed -i '' "s|^0x004cdea8\t.*|0x004cdea8\tFUN_004cdea8\t__aeabi_d2uiz\tcompiler_rt\tHIGH\t# ARM AEABI: double to unsigned int truncation (VCVT.U32.F64)|" "$FILE"

# FUN_004cdeb6: unsigned-int-to-double conversion via VectorUnsignedToFloat
sed -i '' "s|^0x004cdeb6\t.*|0x004cdeb6\tFUN_004cdeb6\t__aeabi_ui2d\tcompiler_rt\tHIGH\t# ARM AEABI: unsigned int to double conversion (VCVT.F64.U32)|" "$FILE"

# FUN_004cdec4: double multiplication (dmul)
sed -i '' "s|^0x004cdec4\t.*|0x004cdec4\tFUN_004cdec4\t__aeabi_dmul\tcompiler_rt\tHIGH\t# ARM AEABI: double multiplication|" "$FILE"

# FUN_004cdcc0: frexp wrapper — calls frexp then stores exponent via output param
sed -i '' "s|^0x004cdcc0\t.*|0x004cdcc0\tFUN_004cdcc0\tfrexp_wrapper\tcompiler_rt\tHIGH\t# C runtime: frexp wrapper — extracts exponent via output parameter|" "$FILE"

# FUN_004cdccc: frexp — extract significand and exponent from double
sed -i '' "s|^0x004cdccc\t.*|0x004cdccc\tFUN_004cdccc\tfrexp\tcompiler_rt\tHIGH\t# C runtime: frexp — extracts significand [0.5,1) and integer exponent from double|" "$FILE"

# ============================================================================
# C Standard Library (NOT RTOS — reclassify to libc)
# ============================================================================

# FUN_0047a6d4: scans string for character, returns pointer or NULL — strchr
sed -i '' "s|^0x0047a6d4\t.*|0x0047a6d4\tFUN_0047a6d4\tstrchr\tlibc\tHIGH\t# C stdlib: strchr — scans string for first occurrence of character|" "$FILE"

# FUN_0047a6ec: returns param | 0x20 — ASCII tolower
sed -i '' "s|^0x0047a6ec\t.*|0x0047a6ec\tFUN_0047a6ec\ttolower_fast\tlibc\tHIGH\t# C stdlib: fast ASCII tolower via OR 0x20|" "$FILE"

# FUN_0047b4e8: exponentiation by repeated squaring with double-multiply loop
sed -i '' "s|^0x0047b4e8\t.*|0x0047b4e8\tFUN_0047b4e8\tpow_int\tcompiler_rt\tHIGH\t# C math: integer-exponent power via repeated squaring (double base)|" "$FILE"

# ============================================================================
# BLE / Application — reclassify misattributed entries
# ============================================================================

# FUN_00477d1c: calls FUN_004cd198 + FUN_004cd81e + FUN_004cd63c (BLE SMP init chain)
sed -i '' "s|^0x00477d1c\t.*|0x00477d1c\tFUN_00477d1c\tble_smp_subsystem_init\tble\tHIGH\t# BLE: SMP subsystem initialization (not RTOS)|" "$FILE"

# FUN_00468f3e: thin wrapper calling FUN_004b8834 (assert/fault handler)
sed -i '' "s|^0x00468f3e\t.*|0x00468f3e\tFUN_00468f3e\tconfigASSERT_hook_a\trtos\tHIGH\t# Application: configASSERT hook — thin wrapper calling assert handler|" "$FILE"

# FUN_00468f80: identical thin wrapper calling FUN_004b8834
sed -i '' "s|^0x00468f80\t.*|0x00468f80\tFUN_00468f80\tconfigASSERT_hook_b\trtos\tHIGH\t# Application: configASSERT hook — thin wrapper calling assert handler (alternate)|" "$FILE"

# ============================================================================
# HIGH/MEDIUM entry corrections (wrong names detected by code analysis)
# ============================================================================

# FUN_00453b28 is labeled taskYIELD but actually returns *pxCurrentTCB — it's xTaskGetCurrentTaskHandle
sed -i '' "s|^0x00453b28\t.*|0x00453b28\tFUN_00453b28\txTaskGetCurrentTaskHandle\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: returns pxCurrentTCB (was incorrectly labeled taskYIELD)|" "$FILE"

# FUN_00453b02 is labeled taskYIELD_wrapper but updates xNextTaskUnblockTime — it's prvResetNextTaskUnblockTime
sed -i '' "s|^0x00453b02\t.*|0x00453b02\tFUN_00453b02\tprvResetNextTaskUnblockTime\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: updates xNextTaskUnblockTime from delayed list (was taskYIELD_wrapper)|" "$FILE"

echo "Done. Applied sed commands to $FILE."

# ============================================================================
# Additional HIGH entry corrections (detected during analysis)
# ============================================================================

# FUN_00453b30 was labeled osTimerStart_3b30 but returns scheduler state (0/1/2)
sed -i '' "s|^0x00453b30\t.*|0x00453b30\tFUN_00453b30\txTaskGetSchedulerState\trtos.freertos\tHIGH\t# FreeRTOS tasks.c: returns 0=NOT_STARTED, 1=RUNNING, 2=SUSPENDED (was osTimerStart_3b30)|" "$FILE"

# FUN_004768c0 was MEDIUM rtos_4768c0, identified as xTimerGenericCommand
sed -i '' "s|^0x004768c0\t.*|0x004768c0\tfun_004768c0\txTimerGenericCommand\trtos.freertos\tHIGH\t# FreeRTOS timers.c: sends command to timer queue — validates, checks scheduler, dispatches|" "$FILE"

# FUN_00486636 was MEDIUM rtos_486636, identified as Ambiq HAL STIMER status accessor
sed -i '' "s|^0x00486636\t.*|0x00486636\tfun_00486636\tam_hal_stimer_compare_status\thal.ambiq\tHIGH\t# Ambiq HAL: writes comparator select, returns STIMER interrupt status|" "$FILE"

# FUN_004542aa was LOW, upgraded to MEDIUM — TCB field accessor
sed -i '' "s|^0x004542aa\t.*|0x004542aa\tFUN_004542aa\txTaskGetTCBField_0x30\trtos.freertos\tMEDIUM\t# FreeRTOS tasks.c: returns *(pxCurrentTCB + 0x30) — likely pxStack or pcTaskName|" "$FILE"
