from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x482868;end=0x482900
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-21267/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Packed-key update reverse search and resize prefix\n\nPartial/unaccepted;152 instructionbytes482868..482900. PUSH{R1,R2,R3,R4,R5,R6,R7,LR}32bytes;R4=descriptor,R5=entrykey,R6=entryvalue. Call482708(R0=R4,liveothers). Nonzero loads482AC4→SP0(overwritessavedR1),482AC8→R3,R2=332,482AB4→R1,R0=3;call44D25C;branchunresolved482944 withreturnedR0. Zero predicate:UXTB(R5)==0 diagnostic loads482ACC→SP4(savedR2),482AD0→SP0,482AC8→R3,R2=336,482AB4→R1,R0=3;call44D25C then infinite4828AC loop R0=0,R1=FFFFFFFF,storeword0atFFFFFFFF,branchback;mayfault, no assumedtrapreplacement.\n\nNonzerokey: freshword[R4]testnull;null→4828E2. Nonnullindependentlyreloadbase, freshcount[R4+8] compute keybase=base+4*countmod;independentlyreloadcount,index=count-1mod. Loop signedindex<0→4828E2;elsefreshbyte[keybase+index] compareUXTB(R5);mismatchindex--repeat. Match freshword[R4]reloadbase,storefullR6 atbase+4*index,branch482944.\n\n4828E2 freshcountbyte+1mod→R0,R1=5*R0mod;freshbase[R4]→R0;call44F76A withliveR2/R3. ReturnedR0zero→482944;nonzero storebase[R4] beforefreshcountbyte→R1,keybaseR1=R0+4*countmod;freshcountbyte→R2 at4828FE. Fallthrough482900unresolved. Preserve independent freshcounts, reverse unsigned-byte key comparison, ordereddescriptorstore and rawcallreturns. No C,freeze,wholecoverage or equalityclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
