from pathlib import Path
import subprocess,json,hashlib
r=Path('/Users/kalani/Repo/evenRealities-openCFW');d=Path(Path('/tmp/opencfw-split-discriminator-path').read_text());prior=r/'g2/analysis/xuantie-csky-dsp-execution-20261009T201800Z';model=r/'g2/analysis/csky-inverse-split-negation-diagnostic-20261009T203251Z';orig=json.loads((model/'build-results.json').read_text());first=orig[0]['command'];k=first.index('/tool/bin/csky-abiv2-elf-gcc');base=first[:k];base[base.index('type=bind,src='+str(model)+',dst=/out')]='type=bind,src='+str(d)+',dst=/out';flags=first[k+1:first.index('-c')];rows=[]
def run(a):
 cmd=base+a;q=subprocess.run(cmd,capture_output=True,text=True);rows.append({'command':cmd,'returncode':q.returncode,'stdout':q.stdout,'stderr':q.stderr});assert q.returncode==0,q.stderr
for n in ['discriminator.c','mac-difference-probe.S']:run(['/tool/bin/csky-abiv2-elf-gcc']+flags+['-c','/out/'+n,'-o','/out/'+n+'.o'])
link=orig[-2]['command'];start=link.index('/out/diagnostic-harness.c.o');deps=link[start+1:];deps=[a if a.startswith('/repo/') else '/repo/'+str((model/a.removeprefix('/out/')).relative_to(r)) for a in deps]
run(['/tool/bin/csky-abiv2-elf-gcc','-mcpu=ck804ef','-mhard-float','-nostdlib','-nostartfiles','-Wl,-T,/out/harness.ld','-Wl,-Map,/out/discriminator.map','-o','/out/discriminator.elf','/repo/'+str((prior/'startup.o').relative_to(r)),'/out/discriminator.c.o','/out/mac-difference-probe.S.o','/repo/'+str((prior/'pneg-probe.S.o').relative_to(r)),'/repo/'+str((prior/'isa-probes.S.o').relative_to(r))]+deps)
(d/'build-results.json').write_text(json.dumps(rows,indent=2)+'\n');sub=d/'run';sub.mkdir();binary=r/'g2/build/offline-xuantie-csky-dsp-20261009T201800Z/qemu-system-cskyv2';cmd=['/opt/homebrew/bin/docker','run','--rm','--network=none','--read-only','--platform','linux/arm64','--mount',f'type=bind,src={binary},dst=/qemu,readonly','--mount',f'type=bind,src={d},dst=/out','--workdir','/out/run','opencfw/qemu-csky-builddeps:20261009t201800','timeout','20s','/qemu','-M','smartl','-cpu','ck804ef','-nographic','-monitor','none','-kernel','/out/discriminator.elf','-d','in_asm,int,guest_errors','-D','/out/run/qemu.log'];q=subprocess.run(cmd,capture_output=True,text=True,timeout=30);m=sub/'mem.log';j={'command':cmd,'returncode':q.returncode,'stdout':q.stdout,'stderr':q.stderr,'memlog':m.read_text() if m.exists() else None,'elf_sha256':hashlib.sha256((d/'discriminator.elf').read_bytes()).hexdigest()};(d/'execution.json').write_text(json.dumps(j,indent=2)+'\n');print(q.returncode);print(j['memlog'])
