from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x480874;end=0x480920
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-ordered-word-snapshot-fresh-index-table-prefix-21536-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Ordered snapshot and freshly indexed halfword tables: prefix\n\nPartial/unaccepted; 172 instruction bytes 480874..480920; routine continues beyond boundary. PUSH R3,R4,R5,LR allocates16; R4=entryR0 output pointer. In order, literal-pointer slots 480E70/E74/E78/E7C/E80 supply fresh word reads stored at output offsets0/4/8/12/16. Literal480E84 supplies source pointer: first fresh word stored at output20, then output24=1. A separate fresh read from the same source selects bits2..3; zero-extended halfword from table pointer480E88 plus2*index shifted left10 stored output44. Literal480E8C supplies a six-byte-stride table: three separate fresh source reads select bits0..1 independently for halfwords at table+6*index+0,+2,+4, each zero-extended then shifted10 and stored output32/36/40 respectively. Never merge these reads into a common snapshot: intervening output writes and aliasing may affect values. Output28 untouched in this prefix.\n\nFresh word from pointer literal480E90 masked255 stored output48. Invoke491102 with R0=10 and liveR1/R2/R3; result ignored. Load R5 pointer literal480E94, reload output48 and fresh word[R5]; OR low4 bits of word shifted8 into output48, without clearing its existing bits, then store. Invoke491102 again with R0=10 and live other arguments. No return or epilogue within prefix; saved-register/stack restoration and final status unresolved. Pointer/table identities in references.json; no pointer validation, MMIO timing, C, freeze, full-coverage, or equality claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
