from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47d9fc;end=0x47da78
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/review-isolated-P2-20915/fresh';o.mkdir(parents=True,exist_ok=True);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Length-guarded helper and global-record validation/reset\n\nPartial/unaccepted;124 instruction bytes, three entries 47D9FC,47DA16,47DA58.\nD9FC: PUSH R7,LR eight bytes. Read unsigned word [entryR0+12] once. If >=4501, R0=0; otherwise call 4D34C4(entryR0,20,0,liveR3) and retain full result. POP R1,PC sets R1=saved entry R7. Zero length is allowed by this routine.\nDA16: PUSH R4,LR eight bytes; R4=word literal47DC30 (record pointer). Fresh word0 must equal literal47DC34; fresh word4 must equal1; first fresh word12 must be nonzero; a second independent word12 must be unsigned <4501. Each failed guard returns0. Successful guards call D9FC(record,liveargs), which reads word12 a THIRD time and can return0 if that fresh value is >=4501. Afterwards fresh word20 is compared with full returned R0: equality returns1, inequality0. Thus zero helper return can still produce1 when fresh word20 is zero. POP R4,PC restores entryR4; no snapshot/atomicity assumption.\nDA58: PUSH R3,R4,R5,LR16 bytes. R4=literal47DC30 pointer; fresh word0 compared with literal47DC34. Equality skips all writes/helper calls. Inequality sets R1=4524,R2=0,R5=R4,R0=R5 then calls43C0E4(record,4524,0,liveR3); after normally returning helper, writes word8=0. POP R0,R4,R5,PC restores R0 from saved entryR3, so no boolean/helper-result return. External helpers remain opaque dependencies. No C/freeze/whole coverage claim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
