from pathlib import Path
import json,hashlib,re,subprocess,tempfile
b=Path('g2/build/pseudocode-first/20260930T190500Z');src=b/'attempts/P1-canonical-fixed-images-005/002/apollo_main-flash.bin';d=src.read_bytes();h=lambda x:hashlib.sha256(x).hexdigest();assert h(d)=='19044a72bdfeb04c6b1b104d87da7b98e13cc18928528d84d999b6bcc0ba9701';start=0x47f46a;end=0x47f56e
with tempfile.TemporaryDirectory() as td:
 t=Path(td);(t/'input.bin').write_bytes(d[start-0x438000:end-0x438000]);(t/'input.s').write_text('.syntax unified\n.cpu cortex-m55\n.thumb\n.text\n.incbin "'+str(t/'input.bin')+'"\n');subprocess.run(['/opt/homebrew/bin/arm-none-eabi-as',str(t/'input.s'),'-o',str(t/'input.o')],check=True);rawtext=subprocess.check_output(['/opt/homebrew/bin/arm-none-eabi-objdump','-D','-j','.text','-M','force-thumb','--adjust-vma='+hex(start),str(t/'input.o')],text=True)
rows=[];cursor=start
for line in rawtext.splitlines():
 m=re.match(r'\s*([0-9a-f]+):\s+([0-9a-f]{4}(?: [0-9a-f]{4})?)\s+([^\s]+)\s*(.*)',line)
 if not m:continue
 a=int(m[1],16)
 if not start<=a<end:continue
 raw=b''.join(int(v,16).to_bytes(2,'little') for v in m[2].split());assert a==cursor and raw==d[a-0x438000:a-0x438000+len(raw)];cursor+=len(raw);rows.append(dict(address=a,bytes=raw.hex(),mnemonic=m[3],operands=m[4]))
assert cursor==end,(hex(cursor),hex(end),rawtext)
o=b/'analysis/apollo-main-diagnostic-fixed-library-record-three-bit-field-update-ordered-mask-clears-21446-map/001';o.mkdir(parents=True,exist_ok=False);(o/'instructions.json').write_text(json.dumps([dict(start=start,end=end,instructions=rows)],indent=2)+'\n');(o/'disassembly.txt').write_text(rawtext);refs=sorted(set(int(m[1],16) for row in rows if (m:=re.search(r'@\s*\(?([0-9a-f]{6,8})',row['operands'])) and 'pc' in row['operands']))
(o/'references.json').write_text(json.dumps([dict(address=a,bytes=d[a-0x438000:a-0x438000+4].hex(),value=int.from_bytes(d[a-0x438000:a-0x438000+4],'little')) for a in refs],indent=2)+'\n')
(o/'pseudocode.md').write_text('# Record three-bit field update and ordered mask clears\n\nPartial/unaccepted;260instructionbytes47F46A..47F56E. PUSH R3,R4,R5,R6,R7,LR24;R4entrypointer,no nullguard;R5literalFE68pointer. Freshrecordbyte0 compared with freshword[R5]&7; equality skips toF4E6. Unequal independentlyfreshword[R5]&7 and freshrecordbyte0 signedcompare (both0..255): wordfield>=byte setsR6=1; less calls480312(6,1,R4,liveR3),setsR6=0. Freshrecordbyte0&7 ORwith independentlyfreshwordthroughFE98 clearedlow3,storedthere;R7FE98pointer. SP0=1 overwrites savedentryR3;480826(5,literalFE68pointer,7,freshword[R7],fifth1) fullnonzero exitsunchanged. Zero compares independentlyfresh[R5]&7 versusfresh[R7]&7; mismatchreturns1. Match andLOW8(R6)!=0 calls480312(6,0,0,liveR3);returnignored.\n\nF4E6 freshbyte1&7 replacesbits3..5infreshwordthroughFE9C; store. Independentlyfreshbyte2&7 replacesbits9..11innewfreshword,samepointer;store. Independentlyfreshbyte3&7 replacesbits12..14innewfreshword;store. Freshbyte4 determineslow3:0→freshwordOR7;1→freshwordBFI6;3→BFI4;7→freshwordclearlow3;others skiplow3write withoutreturnerror. Then literal4800E0pointer: independentlyfreshword&~0x3800 store, independentlyfreshword&~0x700store;return0. CommonPOP R1,R4,R5,R6,R7,PC releases24;R1SP0=1onupdatepath,entryR3oninitialequalitypath. Everyrecord/wordreaddistinct; do notcombineRMWs or cache priorfield. No PRIMASKoperation. Externalhelpersemantics/pointedownershipunresolved;noMMIO/timing/C/freeze/fullcoverageclaim.\n')
(o/'replay.py').write_bytes(Path(__file__).read_bytes());(o/'receipt.json').write_text(json.dumps(dict(accepted=False,status='partial',input_sha256=h(d),instruction_bytes=end-start,files={p.name:h(p.read_bytes()) for p in o.iterdir()}),indent=2)+'\n');print('PASS',end-start)
