"""Build unmodified pinned PDL comparator; preserve gitlinks/index."""
from pathlib import Path
import argparse,subprocess,json,hashlib
from elftools.elf.elffile import ELFFile
p=argparse.ArgumentParser();p.add_argument('--gcc',type=Path,required=True);p.add_argument('--pdl',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();D=Path(__file__).resolve().parent;root=D.parents[2];base=D.parent/'dependency-followup-2026-10-08/touch-source';core=base/'core-lib-ca57d1e519e08badec6891d1776c7b4f05e09561';includes=[base,base/'cmsis',a.pdl/'drivers/include',a.pdl/'devices/include',core/'include'];source=a.pdl/'drivers/source/cy_msclp.c';assert hashlib.sha256(source.read_bytes()).hexdigest()==json.loads((D/'receipt.json').read_text())['source_sha256'];a.output.mkdir(parents=True,exist_ok=True);flags=['-mcpu=cortex-m0plus','-mthumb','-Og','-ffreestanding','-fno-builtin','-DCY8C4046FNI_T412','-ffunction-sections'];obj=a.output/'public.o';elf=a.output/'public.elf';args=[str(a.gcc),*flags,*['-I'+str(i) for i in includes]]
subprocess.run([*args,'-c',str(source),'-o',str(obj)],check=True);script=a.output/'link.ld';script.write_text('SECTIONS { . = 0x100000; .text : { *(.text*) *(.rodata*) } /DISCARD/ : { *(.ARM.exidx*) *(.comment*) } }\n');subprocess.run([str(a.gcc),'-mcpu=cortex-m0plus','-mthumb','-nostdlib','-Wl,--gc-sections','-Wl,-u,Cy_MSCLP_Capture','-Wl,-u,Cy_MSCLP_Configure','-Wl,-u,Cy_MSCLP_ConfigureScan','-T',str(script),str(obj),'-o',str(elf)],check=True)
fw=(root/'g2/blobs/official/g2-2.2.6.10/firmware_touch.bin').read_bytes()[32:];matches=[]
with obj.open('rb') as f:
 e=ELFFile(f)
 for name,address,size in [('Cy_MSCLP_Capture',0x8fa0,48),('Cy_MSCLP_ConfigureScan',0x9178,160)]:
  b=e.get_section_by_name('.text.'+name).data();assert b==fw[address-0x3300:address-0x3300+size];matches.append({'function':name,'address':hex(address),'bytes':size,'sha256':hashlib.sha256(b).hexdigest()})
deps=subprocess.check_output([*args,'-M',str(source)],text=True).replace('\\\n',' ').split(':',1)[1].split();receipt={'source_pin':'35f1714623cfea682d5e285af80d50416b4c7bbc','compiler':subprocess.check_output([str(a.gcc),'--version'],text=True).splitlines()[0],'compiler_sha256':hashlib.sha256(a.gcc.read_bytes()).hexdigest(),'flags':flags,'consumed_source_hashes':{x:hashlib.sha256(Path(x).read_bytes()).hexdigest() for x in deps},'exact_matches':matches,'object_sha256':hashlib.sha256(obj.read_bytes()).hexdigest(),'elf_sha256':hashlib.sha256(elf.read_bytes()).hexdigest(),'limits':['Capture/ConfigureScan exact compiled sections; Configure only bounded behavioral equivalence.','No unique producer/compiler release or whole-payload source completeness.']};(a.output/'receipt.json').write_text(json.dumps(receipt,indent=2)+'\n');print('PASS208 exact compiled-source bytes')
