from pathlib import Path
import subprocess,json,hashlib
D=Path(__file__).resolve().parent;R=D.parents[2];O=Path('/tmp/opencfw-pcm21-reset');O.mkdir(exist_ok=True)
gcc=Path('/tmp/opencfw-arm-gnu/arm-gnu-toolchain-13.3.rel1-darwin-arm64-arm-none-eabi/bin/arm-none-eabi-gcc');src=R/'g2/components/audio/pcm21_children_offline/children.c';apply=src.with_name('apply.c');outer=R/'g2/components/audio/pcm21_control_offline/control.c';classifier=R/'g2/components/audio/platform_callbacks_offline/classify.c'
lifecycle=R/'g2/components/audio/pcm21_completion_offline/lifecycle.c'
reset=R/'g2/components/audio/pcm21_reset_offline/reset.c'
completion=R/'g2/components/audio/pcm21_completion_offline/completion.c'
bindings=dict(stock_peripheral_enable=0x47f5b9,stock_temperature_request=0x480029,stock_wait_status=0x4807fd,stock_info_read=0x4d3f3d,stock_timer_init=0x4801fd,stock_save_irq=0x473941,stock_stimer_running=0x48d621,stock_timer_start=0x480241,stock_timer_restart=0x48028b,stock_delay=0x4807a1,stock_cache_disable=0x474efb,stock_cache_enable=0x474eb5,stock_timer_stop=0x4802cf,)
link=O/'link.ld';link.write_text('pcm21_classify = audio_platform_classify; stock_prepare = pcm21_prepare; stock_change_state = pcm21_change_state; stock_plan = pcm21_plan; stock_apply = pcm21_apply; stock_ton = pcm21_ton; stock_timer_publish = pcm21_timer_publish; stock_completion = pcm21_buck_complete; stock_timer_clear = pcm21_boost_remove; '+' '.join(f'{n} = {v:#x};' for n,v in bindings.items())+' SECTIONS { . = 0x100000; .text : { *(.text*) *(.rodata*) } /DISCARD/ : { *(.ARM.exidx*) *(.comment*) } }')
flags=['-mcpu=cortex-m33','-mfpu=fpv5-sp-d16','-mfloat-abi=hard','-mthumb','-Og','-ffreestanding','-fno-builtin','-nostdlib','-fshort-enums'];elf=O/'control.elf';subprocess.run([str(gcc),*flags,'-T',str(link),str(src),str(apply),str(completion),str(reset),str(lifecycle),str(outer),str(classifier),'-o',str(elf)],check=True)
h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();(D/'reproduction-receipt.json').write_text(json.dumps(dict(sources={str(p.relative_to(R)):h(p) for p in [reset,reset.with_suffix('.h'),lifecycle,completion,completion.with_suffix('.h'),src,src.with_suffix('.h'),apply,outer,outer.with_suffix('.h'),classifier]},gcc=str(gcc),gcc_sha256=h(gcc),flags=flags,elf=str(elf),elf_sha256=h(elf),bindings=bindings,link_script=link.read_text()),indent=2)+'\n')
